/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
 */

@interface RMAdminPersistenceController : RMPersistenceController

+ (id)sharedController;

- (id)init;
- (id)newBackgroundContext;

@end
