/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
 */

@interface RMLocalization : NSObject

+ (void)fetchDisplayNameForUsageLimit:(id)arg1 completionHandler:(id /* block */)arg2;

@end
