/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
 */

@interface RMSCRTUtils : NSObject

+ (bool)deviceSupportsSCRT;
+ (void)retrieveClientCertificateWithCompletion:(id /* block */)arg1;

@end
