/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsCompositeSourceBuilder : NSObject

+ (id)buildCompositeSourceForDelegate:(id)arg1;

@end
