/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsSharedEventStore : NSObject

+ (id)sharedEventStore;

@end
