/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKBackgroundRasterTileSource : VKRasterTileSource

- (long long)defaultMaximumZoomLevel;
- (unsigned char)mapLayerForZoomLevelRange;
- (bool)maximumZoomLevelBoundsCamera;

@end
