/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKPolygonLabelTileSource : VKLabelTileSource

- (unsigned char)_labelTileType;

@end
