/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKSatelliteRasterTileSource : VKRasterTileSource

- (unsigned char)mapLayerForZoomLevelRange;

@end
