/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKVectorTileSource : VKTileSetBackedTileSource

- (long long)defaultMaximumZoomLevel;
- (bool)minimumZoomLevelBoundsCamera;

@end
