/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUAnimatableFilterImageView : UIImageView

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end
