/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUGridCellVibrancyEffect : UIVisualEffect

+ (id)vibrancyEffect;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)effectConfig;

@end
