/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenshotServices.framework/ScreenshotServices
 */

@interface SSOtherScreenSnapshotter : SSScreenSnapshotter

- (id)takeScreenshot;

@end
