/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentRequestShippingMethodUpdate : PKPaymentRequestUpdate <NSSecureCoding>

+ (bool)supportsSecureCoding;

@end
