/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentSetupFieldFooter : PKPaymentSetupFieldLabel

- (unsigned long long)fieldType;

@end
