/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentUnregisterRequest : PKPaymentWebServiceRequest

- (id)_urlRequestWithServiceURL:(id)arg1 deviceIdentifier:(id)arg2 companionSerialNumber:(id)arg3 appleAccountInformation:(id)arg4;

@end
