/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentCredentialMetadataText : PKPaymentCredentialMetadata

- (id)initWithConfiguration:(id)arg1;

@end
