/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentSetupFieldBuiltInLastName : PKPaymentSetupFieldText

- (id)initWithIdentifier:(id)arg1 type:(unsigned long long)arg2;
- (bool)isBuiltIn;

@end
