/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKWalletVisibility : NSObject

+ (bool)isWalletVisible;
+ (id)setOfActiveRestrictionUUIDs;
+ (void)updateWalletVisibility;

@end
