/* Generated by EzioChiu
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFNavigationBarURLButtonBackgroundView : UIImageView

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end
