/* Generated by EzioChiu
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface SFPasswordAlertController : UIAlertController

+ (bool)_preventsAppearanceProxyCustomization;

@end
