/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PBBridgeSupport.framework/PBBridgeSupport
 */

@interface PBBridgeAkashiReporter : NSObject

+ (id)descriptionForSetUpType:(unsigned long long)arg1;
+ (void)incrementSetUpEvent:(unsigned long long)arg1;

@end
