/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PBBridgeSupport.framework/PBBridgeSupport
 */

@interface PBBridgeAssetsReachabilityMonitor : NSObject

+ (void)checkServerReachabilityWithCompletion:(id /* block */)arg1;

@end
