/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreBookkeeper.framework/StoreBookkeeper
 */

@interface SBKPullValueRequest : SBKRequest

+ (id)propertyListBodyWithTransaction:(id)arg1;
+ (id)requestForTransaction:(id)arg1;

- (id)canonicalResponseForResponse:(id)arg1;

@end
