/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreParsec.framework/CoreParsec
 */

@interface PARSyncCard : SFCard <NSSecureCoding>

+ (id)cardWithTitle:(id)arg1 sections:(id)arg2;

@end
