/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CardServices.framework/CardServices
 */

@interface _CRSCardServiceBundleManager : _CRSServiceBundleManager

+ (Class)bundleClass;

@end
