/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
 */

@interface PLAssetsdLibraryClient : PLAssetsdBaseClient

- (void)launchAssetsd;

@end
