/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMAKAppleIDAuthenticationController : NSObject

+ (id)IMAKUserInfoChangedAltDSIDKey;
+ (id)IMAKUserInfoChangedNotification;
+ (id)IMAKUserInfoChangedSecurityLevelKey;

@end
