/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMBroadcastingKeyValueCollection : IMKeyValueCollection

- (void)_notifyListeners;

@end
