/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMDefaults : NSObject

+ (id)sharedInstance;

- (bool)getBoolFromDomain:(id)arg1 forKey:(id)arg2;
- (id)getValueFromDomain:(id)arg1 forKey:(id)arg2;
- (void)setBool:(bool)arg1 forDomain:(id)arg2 forKey:(id)arg3;
- (void)setValue:(id)arg1 forDomain:(id)arg2 forKey:(id)arg3;

@end
