/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMHTMLToSuperParserContext : IMToSuperParserContext

- (id)name;

@end
