/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUItemValidatorRatingTest : SUItemValidatorTest <NSCopying>

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (bool)validateItems:(id)arg1 error:(id*)arg2;

@end
