/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUItemCellConfiguration : SUArtworkCellConfiguration

+ (id)copyDefaultContext;

@end
