/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUScriptFamilySetupViewController : SUScriptViewController

- (id)newNativeViewController;

@end
