/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUScriptDonationViewController : SUScriptViewController {
    NSString * _charityIdentifier;
}

- (id)_className;
- (id)initWithCharityIdentifier:(id)arg1;
- (id)newNativeViewController;

@end
