/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
 */

@interface WBUCreditCardDataController : WBSCreditCardDataController

+ (id)sharedCreditCardDataController;

@end
