/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGContactSharingModelHelper : NSObject

+ (id)createTransformerForInstance:(id)arg1 andLanuage:(id)arg2 andTargetMapping:(id)arg3;

@end
