/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGCuratedChangeNotificationsAddressBookListener : SGCuratedChangeNotificationsBaseListener {
    <NSObject> * _notificationCenterToken;
}

- (void).cxx_destruct;
- (void)startListening;
- (void)stopListening;

@end
