/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGFirstPersonAddressSharingModel : SGModel

+ (id)newTransformerInstanceForLanguage:(id)arg1;

@end
