/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGHtmlEntities : NSObject

+ (id)decodeEntities:(id)arg1;

@end
