/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGIdentityEdge : NSObject {
    SGRecordId * a;
    SGRecordId * b;
    double  strength;
}

- (void).cxx_destruct;

@end
