/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGModelMappingHelper : NSObject

+ (id)loadMappingsForType:(id)arg1 andLanguage:(id)arg2;
+ (id)mappingsForType:(id)arg1 andLanguage:(id)arg2;

@end
