/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGNicknames : NSObject

+ (id)nicknamesForName:(id)arg1;

@end
