/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGQuickResponsesModelRules : NSObject

+ (bool)areModelsAvailableInLanguage:(id)arg1;
+ (id)rules;

@end
