/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGSignificantPhonenumberModel : SGModel

+ (id)newTransformerInstanceForLanguage:(id)arg1;
+ (id)temporaryKeyMap;

@end
