/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGSignificantEmailAddressModel : SGModel

+ (id)newTransformerInstanceForLanguage:(id)arg1;
+ (id)temporaryKeyMap;

@end
