/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosEditUI.framework/PhotosEditUI
 */

@interface PUEditViewController : UIViewController {
    UIImage * _placeholderImage;
}

@property (nonatomic, retain) UIImage *placeholderImage;

- (void).cxx_destruct;
- (id)placeholderImage;
- (void)setPlaceholderImage:(id)arg1;

@end
