/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/SoftwareUpdateServices
 */

@interface SUDefaultRoamingRestrictedDownloadPolicy : SUDefaultDownloadPolicy

- (bool)isDownloadAllowableForCellularRoaming;

@end
