/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ClockKit.framework/ClockKit
 */

@interface CLKComplicationTemplateCircularMediumSimpleText : CLKComplicationTemplateCircularSmallSimpleText

- (bool)isCompatibleWithFamily:(long long)arg1;

@end
