/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ClockKit.framework/ClockKit
 */

@interface CLKLocalizableSimpleTextProvider : CLKSimpleTextProvider

- (id)_localizedTextProviderWithBundle:(id)arg1 forLocalization:(id)arg2;
- (id)initWithTextKey:(id)arg1 shortTextKey:(id)arg2;

@end
