/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
 */

@interface MediaControlsAnalytics : NSObject

+ (void)postAnalyticKind:(long long)arg1;

@end
