/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
 */

@interface MediaControlsRouteLabel : MPRouteLabel

- (void)mc_applyVibrantStyling:(id)arg1;

@end
