/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
 */

@interface MediaControlsRoutingViewController : MPAVRoutingViewController

- (id)_createVolumeSlider;

@end
