/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
 */

@interface RKSentenceClassifier_el_GR : RKSentenceClassifier

- (id)addSentenceTerminatorQuestion:(id)arg1;
- (id)alternativeConjunctions;
- (void)analyzeSentence;
- (id)classifySentence;

@end
