/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardLegacyInstantMessagingLineGenerator : CNVCardLineGenerator

- (id)makeLineWithName:(id)arg1 value:(id)arg2;

@end
