/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardNameComponentPostProcessor : NSObject

+ (void)postProcessNameComponents:(id)arg1;
+ (void)takeNameComponentsFromFormattedName:(id)arg1;

@end
