/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardPhoneLineGenerator : CNVCardLineGenerator

- (id)standardLabelsForLabel:(id)arg1;

@end
