/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardParsedResultBuilderFactory : NSObject

+ (id)factoryWithBlock:(id /* block */)arg1;

@end
