/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardSerializationStorage : NSObject

+ (id)storageWithData:(id)arg1;
+ (id)storageWithString:(id)arg1;

@end
