/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardParameterDecoder : NSObject

+ (id)decodeParameterValue:(id)arg1;
+ (id)substitutions;

@end
