/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSServiceNames : NSObject

+ (id)systemAppProxyServiceName;
+ (id)workspaceServiceName;

@end
