/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDResetUserPrivacySettingsOperation : CKDOperation

+ (long long)isPredominatelyDownload;

- (id)activityCreate;
- (void)main;
- (bool)shouldCheckAppVersion;

@end
