/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKLStreamTrafficConsoleLogObserver : CKLStreamTrafficObserver

- (id)initWithLogTypes:(unsigned long long)arg1;

@end
