/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKApplicationState : NSObject

+ (bool)_isUIExtension;
+ (bool)isActive;
+ (bool)isBackground;
+ (void)setActive:(bool)arg1;

@end
