/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKAvatarShadowClippingLeftCollectionReusableView : CKAvatarShadowClippingCollectionReusableView

+ (id)decorationViewKind;
+ (struct CGSize { double x1; double x2; })shadowSize;

- (id)imageView;

@end
