/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKDateUtilities : NSObject

+ (id)relativeDateFormatterFromDate:(id)arg1 toDate:(id)arg2;
+ (id)thePastDateFormatter;
+ (id)thisWeekRelativeDateFormatter;
+ (id)thisYearDateFormatter;

@end
