/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKDetailsTableView : UITableView

- (bool)allowsFooterViewsToFloat;
- (bool)allowsHeaderViewsToFloat;

@end
