/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKGroupTitleChangeChatItem : CKMultilineStampChatItem

- (id)loadTranscriptText;
- (id)sender;
- (id)title;

@end
