/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKImmediatePanGestureRecognizer : UIPanGestureRecognizer

- (void)finishCurrentInteraction;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end
