/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKIMGroupHeaderRecipient : CKIMComposeRecipient

@property (nonatomic, retain) NSString *displayString;

- (id)displayString;
- (void)setDisplayString:(id)arg1;

@end
