/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKSharedQuickLookThumbnailCollectionViewCell : CKSharedContentsCollectionViewCell

+ (id)placeHolderImage;
+ (id)reuseIdentifier;

- (void)configureWithAttachmentItem:(id)arg1;

@end
