/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKStickerMediaObject : CKImageMediaObject

+ (id)attachmentSummary:(unsigned long long)arg1;
+ (bool)shouldShadePreview;

- (bool)generatePreviewOutOfProcess;

@end
