/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKStackedAvatarView : UIImageView {
    NSArray * _contacts;
}

@property (nonatomic, readonly, copy) NSArray *contacts;

- (void).cxx_destruct;
- (id)_stackWithMonograms:(id)arg1;
- (id)contacts;
- (id)initWithContacts:(id)arg1;

@end
