/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKTranscriptChatItemRules : IMTranscriptChatItemRules

- (bool)shouldShowRaiseMessageStatus;

@end
