/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKUIBehaviorPhone : CKUIBehavior

- (double)welcomeViewContentViewLeadingAnchorLayoutConstraintConstant;
- (double)welcomeViewContentViewTopAnchorLayoutConstraintConstant;
- (id)whatsNewViewApplePayImage;
- (double)whatsNewViewBulletPointSymbolLeadingAnchorLayoutConstraintConstant;
- (double)whatsNewViewBulletPointTextTrailingAnchorLayoutConstraintConstant;

@end
