/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKWBMPImageMediaObject : CKImageMediaObject

+ (id)UTITypes;
+ (Class)imageDataClass;

- (bool)generatePreviewOutOfProcess;

@end
