/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFoundation.framework/NewsFoundation
 */

@interface NFContainerContextMismatchException : NFContainerException

+ (id)exceptionWithContextKey:(id)arg1;

@end
