/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFoundation.framework/NewsFoundation
 */

@interface NFContainerDefinitionNotOverridableException : NFContainerException

+ (id)exceptionWithDefinitionKey:(id)arg1;

@end
