/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFoundation.framework/NewsFoundation
 */

@interface NFContainerCircularDependencyDetectedException : NFContainerException

+ (id)exception;

@end
