/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFoundation.framework/NewsFoundation
 */

@interface Void : NSObject <NSCopying>

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
