/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FMFUI.framework/FMFUI
 */

@interface FollowerDetailsLinkCell : PSTableCell

+ (long long)cellStyle;

- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
