/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UpNextWidget.framework/UpNextWidget
 */

@interface UpNextGeoServicesBridge : NSObject

+ (id)addressDictionaryFormattedAddressLinesKey;

@end
