/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoMusicSync.framework/NanoMusicSync
 */

@interface NMSPodcastMediaItemGroup : NMSMediaItemGroup

+ (id)_sharedPodcastSizeCache;

- (id)itemList;
- (id)libraryIdentifiersForContainerType:(unsigned long long)arg1;

@end
