/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoMusicSync.framework/NanoMusicSync
 */

@interface NMSRecommendationMediaItemGroup : NMSMediaItemGroup

- (bool)isEstimate;
- (id)itemList;
- (id)libraryIdentifiersForContainerType:(unsigned long long)arg1;
- (id)recommendation;

@end
