/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoMusicSync.framework/NanoMusicSync
 */

@interface NMSSequentialMediaItemGroupIterator : NMSMediaItemGroupIterator

- (void)_continueToNextIdentifier;
- (unsigned long long)iteratingOrder;

@end
