/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@interface SFAccountManager : NSObject

+ (void)appleAccountSignedIn;
+ (void)appleAccountSignedOut;

@end
