/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSPersonNameComponentsStyleFormatterNicknameVariant : _NSPersonNameComponentsStyleFormatter

- (id)abbreviatedKeys;
- (id)keysOfInterest;
- (id)orderedTemplate;

@end
