/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSEmojiCheckingResult : NSCorrectionCheckingResult

- (unsigned long long)resultType;

@end
