/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSIBPrototypingLayoutConstraint : NSLayoutConstraint

+ (id)classFallbacksForKeyedArchiver;

- (bool)_isIBPrototypingLayoutConstraint;

@end
