/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSISRestrictedToZeroMarkerVariable : NSISVariable

- (id)markedConstraint;
- (bool)shouldBeMinimized;
- (int)valueRestriction;

@end
