/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueNonmutatingSetMethodSet : NSKeyValueNonmutatingCollectionMethodSet {
    struct objc_method { } * count;
    struct objc_method { } * enumerator;
    struct objc_method { } * member;
}

@end
