/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSQuoteCheckingResult : NSSubstitutionCheckingResult

- (unsigned long long)resultType;

@end
