/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitConverter : NSObject

- (double)baseUnitValueFromValue:(double)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)valueFromBaseUnitValue:(double)arg1;

@end
