/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSURLFileTypeMappingsInternal : NSObject {
    NSDictionary * MIMETypeToExtensionList;
    NSDictionary * extensionToMIMEType;
}

- (id)init;

@end
