/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DCIMServices.framework/DCIMServices
 */

@interface CAMLightingCubeStyleGlowing : NSObject <CAMLightingCubeStyle>

+ (id)contourAppearance;
+ (id)naturalAppearance;
+ (id)stageAppearance;
+ (id)stageMonoAppearance;
+ (id)studioAppearance;

@end
