/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface GQDBGTheme : NSObject {
    struct __CFArray { } * mMasterSlides;
    GQDSStylesheet * mStylesheet;
}

- (void)dealloc;
- (id)stylesheet;

@end
