/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface GQDGraphic : GQDDrawable {
    GQDSStyle * mGraphicStyle;
}

- (void)dealloc;
- (id)graphicStyle;

@end
