/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface GQDTFormulaCell : GQDTCell {
    GQDTCell * mResultCell;
}

- (void)dealloc;
- (id)resultCell;
- (void)setResultCell:(id)arg1;

@end
