/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface GQDWPAttachment : NSObject {
    GQDDrawable * mDrawable;
}

- (void)dealloc;
- (id)drawable;

@end
