/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface GQDWPHeaderFooterStorage : GQDWPLayoutStorage {
    struct __CFString { } * mName;
}

- (void)dealloc;
- (id)initWithName:(struct __CFString { }*)arg1;
- (struct __CFString { }*)name;

@end
