/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface KNAnimationTools : NSObject

+ (bool)isAnimationEditorConnected;
+ (bool)isAnimationImageTesterConnected;
+ (void)startAnimationToolsIfNecessary;

@end
