/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface KNObjectPlaceholderLayout : KNPlaceholderLayout

- (bool)canFlip;
- (id)instructionalStorageForContainedStorage:(id)arg1 storageKind:(int)arg2;
- (bool)supportsRotation;

@end
