/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TNPagePlaceholderRep : TSDContainerRep

- (void)didUpdateLayer:(id)arg1;
- (bool)directlyManagesLayerContent;
- (Class)layerClass;

@end
