/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TPGilliganCompatibilityDelegate : TPBaseCompatibilityDelegate

- (Class)exporterClassForType:(id)arg1 options:(id)arg2;

@end
