/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCEUnpersistedStorage : TSWPStorage

+ (id)copyStorageUnpersisted:(id)arg1;

- (id)copyPersistedWithContext:(id)arg1;
- (void)willModify;

@end
