/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DChartDonutSceneObject : TSCH3DChartPieFamilySceneObject

+ (id)chartSeriesType;

@end
