/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DVertexShaderEffect : TSCH3DBaseVertexShaderEffect

- (void)inject:(id)arg1;

@end
