/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartBubbleElementsRenderer : TSCHChartAbstractLineElementsRenderer

- (bool)useBlendModeCopyForTransparencyLayer;

@end
