/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartStackedLineValueAxis : TSCHChartStackedValueAxis

- (id)p_orthogonalAxisForSeries:(id)arg1;

@end
