/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartLineElementsRenderer : TSCHChartAbstractLineElementsRenderer

- (bool)supportsSeparateLabelsRenderPass;

@end
