/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartStackedAreaElementsRenderer : TSCHChartAbstractLineElementsRenderer

@end
