/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartSeriesTypeMixedColumn : TSCHChartSeriesTypeColumn

- (bool)chunkedBuildsIncludeInterceptValues;
- (id)g_genericToSpecificPropertyMapMixedColumn;
- (id)genericToSpecificPropertyMap;

@end
