/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartBorderAxisLayoutItem : TSCHChartAxisLayoutItem

- (void)buildSubTree;
- (id)renderersWithRep:(id)arg1;

@end
