/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DTextureAtlasTextureResource : TSCH3DResource <TSCHUnretainedParent> {
    TSCH3DTextureAtlasTexture * mParent;
}

- (void)clearParent;
- (void)dealloc;
- (id)get;
- (id)initWithParent:(id)arg1;

@end
