/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DChartStagedAxisSceneOrthographicShadows : TSCH3DChartStagedAxisScene

- (id)shadowSceneObject;

@end
