/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHStackedBarElementBuilder : TSCHStackedBarColumnElementBuilder

- (id)init;

@end
