/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DVectorDataBuffer : TSCH3DDataBuffer

+ (id)bufferWithCapacity:(unsigned long long)arg1;
+ (id)bufferWithCapacity:(unsigned long long)arg1 dimension:(unsigned long long)arg2;

@end
