/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DChartShadowsShaderEffect : TSCH3DShaderEffect

- (void)inject:(id)arg1;

@end
