/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DChartColumnSceneObject : TSCH3DChartAbstractBarSceneObject

+ (id)chartSeriesType;
+ (bool)isHorizontalChart;
+ (bool)isStacked;

@end
