/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartSeriesTypeColumn3D : TSCHChartSeriesTypeColumn

+ (Class)sceneObjectClass;

- (id)g_genericToSpecificPropertyMap3DColumn;
- (id)genericToSpecificPropertyMap;
- (bool)supportsRoundedCorners;

@end
