/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartSeriesTypeStackedArea3D : TSCHChartSeriesTypeStackedArea

+ (Class)sceneObjectClass;

- (id)g_genericToSpecificPropertyMap3DStackedArea;
- (id)genericToSpecificPropertyMap;
- (int)legendBadgeType;
- (bool)supportsSymbolDrawing;

@end
