/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DChartElementSceneObjectProcessBoundsItems : TSCH3DChartElementSceneObjectProcessGeometryOnlyItems

- (bool)useBoundsGeometry;

@end
