/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DPhongMaterialShaderEffect : TSCH3DMaterialShaderEffect

- (void)inject:(id)arg1;

@end
