/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartPieAreaLayoutItem : TSCHChartRadialAreaLayoutItem

- (Class)bodyLayoutItemClass;

@end
