/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSDContainerLayout : TSDLayout

- (id)childInfosForLayout;
- (id)containerInfo;
- (id)initWithInfo:(id)arg1;
- (void)updateChildrenFromInfo;

@end
