/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSKAddedToDocumentContext_MigratingStyles : TSKAddedToDocumentContext

- (id)description;
- (bool)wasMigratingStyles;

@end
