/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKAddedToDocumentContext_ExportFootnotes : TSKAddedToDocumentContext

- (id)description;
- (bool)exportingFootnotes;

@end
