/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKAddedToDocumentContext_Unhiding : TSKAddedToDocumentContext

- (id)description;
- (id)undoContext;
- (bool)wasUnhidden;

@end
