/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSKAddedToDocumentContext_MoveSection : TSKAddedToDocumentContext_DragMove

- (id)description;
- (bool)preserveChangeTracking;

@end
