/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKAddedToDocumentContext_UndoDelete : TSKAddedToDocumentContext

- (id)description;
- (bool)wasUndoDelete;

@end
