/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSKOperationPropertiesUtils : NSObject

+ (void)initialize;
+ (bool)isFirstOneWinProperty:(id)arg1;

@end
