/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKRemovedFromDocumentContext_Moving : TSKRemovedFromDocumentContext

- (id)description;
- (id)undoContext;
- (bool)wasMoved;

@end
