/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKRemovedFromDocumentContext_Hiding : TSKRemovedFromDocumentContext

- (id)description;
- (id)undoContext;
- (bool)wasHidden;

@end
