/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKSelection : NSObject

+ (Class)archivedSelectionClass;

- (long long)compare:(id)arg1;

@end
