/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSPDocumentResourceLegacyTangierRegistry : TSPDocumentResourceLegacyRegistry

- (id)metadataDictionaryKeyForRelativePath:(id)arg1;

@end
