/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSPObjectSerializationAsPasteboardArchiver : TSPWeakAsStrongCopyArchiver

- (long long)targetType;

@end
