/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSSStyleDiff : TSPObject

@property (nonatomic, readonly) TSSStylePropertyChangeSet *changeSet;

- (id)changeSet;

@end
