/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSTArchivedRdar39989167CellSelection : TSTArchivedCellSelection

- (void)loadFromUnarchiver:(id)arg1;

@end
