/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSTTableNameSelection : TSKSelection

+ (Class)archivedSelectionClass;
+ (id)tableNameSelection;

@end
