/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface TSUCutting : NSObject

+ (void)beginCutting;
+ (void)endCutting;
+ (bool)isCutting;

@end
