/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSUtility.framework/TSUtility
 */

@interface TSUMutablePair : TSUPair

- (void)setFirst:(id)arg1;
- (void)setSecond:(id)arg1;

@end
