/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSUtility.framework/TSUtility
 */

@interface TSUPointerKeyDictionary : TSUNoCopyDictionary

- (id)initWithCapacity:(unsigned long long)arg1;

@end
