/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSUQuicklookResource : NSObject

+ (id)imagePathForQuicklookResource:(id)arg1;

@end
