/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSUUIImageAutoreleasePoolGuard : NSObject {
    UIImage * mImage;
}

- (void)dealloc;
- (id)initWithUIImage:(id)arg1;

@end
