/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsServer.framework/UserNotificationsServer
 */

@interface UNSNotificationRecordAddUpdate : UNSNotificationRecordUpdate

+ (id)updateWithNotificationRecord:(id)arg1;

@end
