/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentCamera.framework/DocumentCamera
 */

@interface DCSinglePixelHorizontalLineView : DCSinglePixelLineView

- (long long)sizeLayoutAttribute;

@end
