/* Generated by EzioChiu
   Image: /System/Library/Frameworks/NotificationCenter.framework/NotificationCenter
 */

@interface NCWidgetMetrics : NSObject

+ (void)_updateWidgetRowHeightForContentSizeCategory;
+ (double)defaultWidgetRowHeight;
+ (double)scaledValueForValue:(double)arg1;
+ (double)widgetRowHeight;

@end
