/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBLockScreenPluginEmergencyDialerAction : SBLockScreenPluginAction

- (bool)isEmergencyDialerAction;

@end
