/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUIIconForceTouchWindow : SBFWindow

- (bool)_shouldControlAutorotation;

@end
