/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUISecureIconForceTouchWindow : SBFSecureWindow

+ (bool)_isSecure;

- (bool)_shouldControlAutorotation;

@end
