/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface DevicePINKeypad : UIKeyboard

- (id)init;
- (bool)isMinimized;
- (void)setMinimized:(bool)arg1;

@end
