/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface DiagnosticDataController : PSListController

- (id)init;
- (id)specifiers;
- (void)viewDidLoad;

@end
