/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface FontSizeSliderCell : PSSliderTableCell

- (void)layoutSubviews;
- (id)newControl;

@end
