/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PopBackListItemsController : PSListItemsController

- (void)listItemSelected:(id)arg1;
- (void)prepareSpecifiersMetadata;

@end
