/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface ProblemReportingAboutController : UIViewController

- (void)donePressed;
- (id)initWithTitle:(id)arg1 content:(id)arg2;

@end
