/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSNonMovableTapGestureRecognizer : UITapGestureRecognizer

- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end
