/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSReversedSubtitleDisclosureTableCell : PSSubtitleDisclosureTableCell

- (void)_valueLabelForSpecifier:(id)arg1;

@end
