/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSTextView : UITextContentView {
    PSTextViewTableCell * _cell;
}

- (void).cxx_destruct;
- (void)setCell:(id)arg1;

@end
