/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSUsageBundleCell : PSTableCell

- (bool)canReload;
- (void)layoutSubviews;
- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
