/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSVideoSubscriberPrivacyCell : PSSwitchTableCell

+ (id)_accountStore;
+ (long long)cellStyle;
+ (id)identityProviderDisplayName;

- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
