/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface STMAppDynamicSizeCache : STMSizeCache

- (id)createCacheEntryForPath:(id)arg1;

@end
