/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface STMAppStaticSizeCache : STMSizeCache

- (id)createCacheEntryForPath:(id)arg1;

@end
