/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PDFKit.framework/PDFKit
 */

@interface PDFActionPrivate : NSObject {
    NSArray * nextActions;
    NSString * type;
}

- (void).cxx_destruct;

@end
