/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PDFKit.framework/PDFKit
 */

@interface PDFActionGoToPrivateVars : NSObject {
    PDFDestination * destination;
}

- (void).cxx_destruct;

@end
