/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PDFKit.framework/PDFKit
 */

@interface PDFAKOverlayAdaptorPrivate_ios : NSObject {
    AKRectAnnotation * editingAnnotaiton;
    bool  singleFingerScrollingDisabled;
}

- (void).cxx_destruct;

@end
