/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PDFKit.framework/PDFKit
 */

@interface PDFCoachMarkManagerPrivate : NSObject {
    NSMutableDictionary * coachMarks;
    PDFRenderingProperties * renderingProperties;
    PDFTimer * timer;
}

- (void).cxx_destruct;

@end
