/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebContentAnalysis.framework/WebContentAnalysis
 */

@interface WFSlangTag : WFTagFlyweight

+ (id)sixtyNineTag;

- (id)tagWithWebpage:(id)arg1;

@end
