/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebContentAnalysis.framework/WebContentAnalysis
 */

@interface WFUSC2257Tag : WFTagFlyweight

+ (id)twoTwoFiveSevenTag;
+ (id)unitedStatesCodeTag;

- (id)tagWithWebpage:(id)arg1;

@end
