/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchReplies.framework/WatchReplies
 */

@interface WRCalendarReplyStoreInfo : WRReplyStoreInfo

- (unsigned long long)defaultCount;

@end
