/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchReplies.framework/WatchReplies
 */

@interface WRThirdPartyReplyStoreInfo : WRReplyStoreInfo

- (unsigned long long)defaultCount;

@end
