/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCAudioAccessoryHostingView : UIView

+ (Class)layerClass;

- (id)initWithContextId:(unsigned int)arg1;

@end
