/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationManagementPromotionAlertController : NCNotificationManagementAlertController

- (void)_configureView;

@end
