/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationRequestHiddenPreviewContentProvider : NCNotificationRequestCoalescingContentProvider

@end
