/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationListPhoneCoalescingManager : NCNotificationListCoalescingManager

- (id)coalescingIdentifierForNotificationRequest:(id)arg1;

@end
