/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationListHiddenPreviewCoalescingManager : NCNotificationListCoalescingManager

- (id)_newContentProviderForNotificationRequest:(id)arg1;
- (id)coalescingIdentifierForNotificationRequest:(id)arg1;

@end
