/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCUIMappedImageCache : BSUIMappedImageCache

+ (id)sharedCache;

@end
