/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriUICore.framework/SiriUICore
 */

@interface SUICHandsOffAutoDismissalStrategy : SUICAutoDismissalStrategy

- (double)idleTimeInterval;
- (bool)shouldDismiss;

@end
