/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
 */

@interface GKOOBMessageFactory : NSObject

+ (id)newMessageFromData:(id)arg1;

@end
