/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateServicesUI.framework/SoftwareUpdateServicesUI
 */

@interface SUSUIFakeSUDownload : SUDownload

- (id)descriptor;
- (id)metadata;
- (id)progress;

@end
