/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateServicesUI.framework/SoftwareUpdateServicesUI
 */

@interface SUSUIFakeDocumentation : SUDocumentation

- (id)licenseAgreement;

@end
