/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateServicesUI.framework/SoftwareUpdateServicesUI
 */

@interface SUSUIFakeSUDownloadMetadata : SUDownloadMetadata

- (bool)isAutoDownload;
- (int)termsAndConditionsAgreementStatus;

@end
