/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface _MPCPrivateListeningStateLocalDeviceSource : MPCPrivateListeningStateSource

- (id)currentValue;

@end
