/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface _MPModelMediaRemotePodcastEpisodeAuthor : MPModelPodcastAuthor

@end
