/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface AirPortAssistantUINavigationController : UINavigationController

- (bool)disablesAutomaticKeyboardDismissal;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;

@end
