/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface DiagsPrivacyHelpViewController : UIViewController

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;

@end
