/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface PPPoEConnectionUIViewController : AssistantSubUIViewController <TableViewManagerDelegate>

- (void)loadView;
- (void)touchInCellAtIndexPath:(id)arg1;

@end
