/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface PrivateIPFormatter : MinMaxIntFormatter

+ (id)privateIPFormatter;

@end
