/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface StepByStepUIViewController_ExtendWired_Connections : InternetViewController

- (void)loadView;

@end
