/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@interface StepByStepUIViewController_ReplaceChoice : StepByStepUIViewController <TableViewManagerDelegate>

- (void)loadView;
- (void)setupTable;
- (void)touchInCellAtIndexPath:(id)arg1;
- (void)viewWillAppear:(bool)arg1;

@end
