/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreBookkeeperClient.framework/StoreBookkeeperClient
 */

@interface SBCMusicLibraryPlaybackPositionDomain : SBCPlaybackPositionDomain

@end
