/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreBookkeeperClient.framework/StoreBookkeeperClient
 */

@interface SBCPlaybackPositionServiceInterface : SBCXPCServiceInterface

+ (id)serviceClientInterface;
+ (id)serviceInterface;
+ (id)serviceName;

@end
