/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreRecognition.framework/CoreRecognition
 */

@interface CRCameraReaderOutputIDCard : CRCameraReaderOutput

@property (readonly) UIImage *imageValue;

- (id)imageValue;

@end
