/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BridgePreferences.framework/BridgePreferences
 */

@interface BPSNTKFacesViewController : UIViewController

+ (void)setDisplayDevice:(id)arg1;

@end
