/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNANEProcessingDevice : VNProcessingDevice

- (int)espressoStorageType;
- (bool)targetsANE;

@end
