/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreAccessories.framework/CoreAccessories
 */

@interface ACCUserDefaults : NSUserDefaults

+ (id)sharedDefaults;

- (id)init;

@end
