/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface CustomCompositorUtils : NSObject

+ (void)SetupVideoCompositionContext:(id)arg1;

@end
