/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroFeedbackTableCell : UITableViewCell

- (void)layoutSubviews;
- (void)setSelected:(bool)arg1 animated:(bool)arg2;

@end
