/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroAssetSuggestionsNavigationController : UINavigationController

- (unsigned long long)supportedInterfaceOrientations;

@end
