/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface PlaybackCapabilities : NSObject

+ (bool)canDropFrameWhenSpeedUp;
+ (bool)canPlaybackThree1080P30Streams;
+ (bool)canPlaybackThree1080P60Streams;

@end
