/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@interface IMIDSLog : NSObject

+ (id)daemon;
+ (id)dataDetector;
+ (id)encryption;

@end
