/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimerUI.framework/MobileTimerUI
 */

@interface MTLegacyNavigationBar : UINavigationBar

+ (bool)_forceLegacyVisualProvider;

@end
