/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WiFiKitUI.framework/WiFiKitUI
 */

@interface WFHotspotAlertController : WFPromptAlertController

+ (id)hotspotAlertControllerWithNetworkName:(id)arg1 completionHandler:(id /* block */)arg2;

@end
