/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PASampling.framework/PASampling
 */

@interface PAAggregatedMainThread : PAAggregatedThread

- (id)debugDescription;
- (bool)isMainThread;

@end
