/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SetupAssistantUI.framework/SetupAssistantUI
 */

@interface BFFAssistantOptInUtilities : NSObject

+ (id)aboutSiriController;

@end
