/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IDS.framework/IDS
 */

@interface IDSLogging : NSObject

+ (id)IDSDataChannels;
+ (id)_IDSGroupSession;
+ (id)_IDSGroupSession_oversize;
+ (id)transactionLog;

@end
