/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTSystemModuleSimpleMaterialSettings : MTSystemModuleMaterialSettings

+ (id)sharedMaterialSettings;

- (double)baseOverlayBrightness;
- (id)baseOverlayColor;
- (double)baseOverlaySaturation;

@end
