/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTSystemWidgetPlatterMaterialSettings : MTSystemPlatterMaterialSettings

+ (id)sharedMaterialSettings;

- (Class)vibrantStylingProviderClass;

@end
