/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTVibrantListTintDarkStyling : MTPlusDStyling

- (double)alpha;
- (id)color;

@end
