/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTVibrantSecondaryDarkHighContrastStyling : MTVibrantHighContrastStyling

- (id)color;
- (long long)style;

@end
