/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTVibrantWidgetSecondaryHighlightStyling : MTPlusDStyling

- (double)alpha;
- (id)color;
- (long long)style;

@end
