/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ParsecModel.framework/ParsecModel
 */

@interface PAREvent : NSManagedObject

@property (nonatomic, copy) NSDate *timestamp;

+ (id)fetchRequest;

@end
