/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
 */

@interface SiriUIAnimationUtilities : NSObject

+ (double)defaultAnimationDuration;
+ (id)defaultTimingFunction;

@end
