/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
 */

@interface SiriRoutePickerAlertController : UIAlertController

- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;

@end
