/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
 */

@interface SiriUIPrivateViewControllerOverrides : NSObject

+ (id)viewControllerForSnippet:(id)arg1;

@end
