/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface NUImageDataClient : NURenderClient

- (void)submitRequest:(id)arg1 completion:(id /* block */)arg2;

@end
