/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface NUPlatform_iOS : NUPlatform

- (bool)defaultSupportsLiveVideoRendering;
- (id)displays;
- (id)init;
- (id)mainDevice;

@end
