/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface NUVideoPropertiesClient : NURenderClient

- (void)submitPropertiesRequestForComposition:(id)arg1 completion:(id /* block */)arg2;

@end
