/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface NUVideoPlaybackCompositor : NUVideoCompositor

- (void)fulfillVideoCompositionRequest:(id)arg1;

@end
