/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Radio.framework/Radio
 */

@interface RadioStationMatchMetadata : NSObject

+ (id)metadataKey;

- (id)copyMetadataDictionary;

@end
