/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSFollowUpMetricsEvent : AMSMetricsEvent

+ (id)eventFromMetricsDictionary:(id)arg1;

@end
