/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSFeatureEnabler : NSObject

+ (id)_fetchEnabledFeatures;
+ (void)clear;
+ (id)cookie;

@end
