/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSLookupDecoder : NSObject <AMSResponseDecoding>

- (id)resultFromResult:(id)arg1 error:(id*)arg2;

@end
