/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSRemoteNotification : NSObject

+ (id)_parsables;
+ (void)handleNotification:(id)arg1;
+ (bool)shouldHandleNotification:(id)arg1;

@end
