/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WeatherFoundation.framework/WeatherFoundation
 */

@interface WFResourceManager : NSObject

+ (id)sharedManager;

- (id)frameworkBundle;
- (id)localizedStringForKey:(id)arg1;
- (id)tableName;

@end
