/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface _SFAsymmetricKeySpecifier : _SFKeySpecifier {
    id  _asymmetricKeySpecifierInternal;
}

- (void).cxx_destruct;

@end
