/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFCiphertext_Ivars : NSObject {
    NSData * ciphertext;
}

- (void).cxx_destruct;

@end
