/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFCMACOperation_Ivars : NSObject {
    SFSymmetricEncryptionOperation * encryptionOperation;
}

- (void).cxx_destruct;

@end
