/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFHMACPseudoRandomFunction_Ivars : NSObject {
    <SFDigestOperation> * digestOperation;
}

- (void).cxx_destruct;

@end
