/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFKeychainManager_Ivars : NSObject {
    _SFCredentialStore * credentialStore;
}

- (void).cxx_destruct;

@end
