/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFRSASigningOperation_Ivars : NSObject {
    <SFDigestOperation> * digestOperation;
    _SFRSAKeySpecifier * keySpecifier;
}

- (void).cxx_destruct;

@end
