/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFRSAKeySpecifier_Ivars : NSObject {
    long long  bitSize;
}

@end
