/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFRSAEncryptionOperation_Ivars : NSObject {
    _SFRSAKeySpecifier * keySpecifier;
}

- (void).cxx_destruct;

@end
