/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFSSLClientTrustPolicy_Ivars : NSObject {
    NSString * clientName;
}

- (void).cxx_destruct;

@end
