/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFSymmetricKey_Ivars : NSObject {
    NSData * keyData;
}

- (void).cxx_destruct;

@end
