/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFWrappedKeyCiphertext_Ivars : NSObject {
    _SFCiphertext * ciphertextKey;
}

- (void).cxx_destruct;

@end
