/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoMailKitServer.framework/NanoMailKitServer
 */

@interface NNMKProtectedSyncServiceServer : NNMKMessagesSyncServiceServer

- (id)initWithQueue:(id)arg1;

@end
