/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

@interface TPFavoritesCollectionViewFlowLayout : UICollectionViewFlowLayout

- (double)caption2FontScaledValueForValue:(double)arg1;
- (id)init;

@end
