/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

@interface TPSetPINKeyPadButton : TPSimpleNumberPadButton

+ (double)outerCircleDiameter;

@end
