/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

@interface TPSimpleNumberPadButton : TPNumberPadLightStyleButton

+ (id)disabledImageForCharacter:(unsigned int)arg1;

- (void)setGreyedOut:(bool)arg1;

@end
