/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

@interface TPSuperBottomBar : UIView

+ (double)defaultBottomMargin;
+ (double)defaultInterButtonSpacing;
+ (double)defaultSideMarginForDoubleButton;
+ (double)defaultSideMarginForSingleButton;
+ (double)defaultWidth;

@end
