/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AAAppleTVRequest : AARequest {
    ACAccount * _account;
}

- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1;

@end
