/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AACloudKitDevicesListRequest : _AABasicGetRequest

+ (Class)responseClass;

- (id)urlString;

@end
