/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AACompleteEmailVettingResponse : AAResponse

@property (nonatomic, readonly) int vettingStatus;

- (int)vettingStatus;

@end
