/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AAiCloudTermsStringResponse : AAGenericTermsUIResponse

@property (nonatomic, readonly) NSString *termsString;

- (id)termsString;

@end
