/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AAInitiateEmailVettingRequest : AAEmailVettingRequest

- (id)bodyDictionary;
- (id)urlString;

@end
