/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AASetupAssistantAuthenticateRequest : AAAuthenticateRequest

- (id)urlString;

@end
