/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AASetupAssistantUpgradeStatusResponse : AAResponse

@property (nonatomic, readonly) NSNumber *upgradeStatus;

- (id)upgradeStatus;

@end
