/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface ATVHighSecurityAccountDeviceList : AAAppleTVRequest

+ (Class)responseClass;

- (id)urlRequest;
- (id)urlString;

@end
