/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface ATVHighSecurityAccountSendCode : AAAppleTVRequest {
    NSDictionary * _device;
}

+ (Class)responseClass;

- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1 device:(id)arg2;
- (id)urlRequest;
- (id)urlString;

@end
