/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFAbstractAlarmStatusItem : HFStatusItem

- (id)_entireHomeString;
- (id)_multipleTriggeredRoomsFormatString;
- (id)_serviceType;
- (id)_singleTriggeredRoomFormatString;
- (id)_subclass_updateWithOptions:(id)arg1;

@end
