/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFAbstractBinaryStatusItem : HFStatusItem

- (id)_subclass_updateWithOptions:(id)arg1;
- (id)multipleAbnormalServicesFormatString;
- (id)multipleAbnormalServicesWithRoomFormatString;
- (id)oneAbnormalServiceFormatString;
- (id)oneAbnormalServiceWithRoomFormatString;
- (id)serviceTypes;

@end
