/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFCarbonMonoxideAlarmStatusItem : HFAbstractAlarmStatusItem

- (id)_entireHomeString;
- (id)_serviceType;
- (id)_singleTriggeredRoomFormatString;

@end
