/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFLockStatusItem : HFAbstractBinaryStatusItem

- (id)multipleAbnormalServicesFormatString;
- (id)multipleAbnormalServicesWithRoomFormatString;
- (id)oneAbnormalServiceFormatString;
- (id)oneAbnormalServiceWithRoomFormatString;
- (id)serviceTypes;

@end
