/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFTimeIntervalFormatter : NSDateComponentsFormatter

- (id)stringForObjectValue:(id)arg1;

@end
