/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKBrowseForShareTargetsRequest : CATTaskRequest

+ (bool)supportsSecureCoding;

- (id)init;

@end
