/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKFetchActiveInstructorsRequest : CATTaskRequest

+ (bool)supportsSecureCoding;
+ (Class)whitelistedClassForResultObject;

@end
