/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface _MFNSShadowTransformer : _MFValueTransformer

- (id)transformValue:(id)arg1 inverse:(bool)arg2;

@end
