/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface _MFPlaceholderComposeRecipient : MFComposeRecipient

- (void)dealloc;
- (id)displayString;
- (void)setDisplayString:(id)arg1;

@end
