/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

@interface BBBulletinModifyUpdate : BBBulletinUpdate

+ (id)updateWithBulletin:(id)arg1 feeds:(unsigned long long)arg2;

- (id)typeDescription;

@end
