/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

@interface BBObjectCache : NSObject {
    NSHashTable * _cache;
}

- (void).cxx_destruct;
- (id)cacheObject:(id)arg1;
- (id)init;

@end
