/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHPersonPLAdapter : PHObjectPLAdapter

- (id)objectForKey:(id)arg1;
- (id)objectWithPropertySets:(id)arg1;

@end
