/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMMutableMediaSystemComponent : HMMediaSystemComponent

@property (nonatomic, retain) HMMediaSystemRole *role;

@end
