/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

@interface PTPInitEventACKPacket : NSObject

- (id)contentForTCP;
- (id)description;
- (id)initWithTCPBuffer:(void*)arg1;

@end
