/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
 */

@interface AKFollowUpServerPayloadFormatter : NSObject

+ (id)pendingAuthKitFollowUpPayload:(id)arg1;

@end
