/* Generated by EzioChiu.
 */

@protocol _MKInfoCardChildViewControllerAnalyticsDelegate <NSObject>

@optional

- (NSArray *)infoCardChildPossibleActions;
- (NSArray *)infoCardChildUnactionableUIElements;

@end
