/* Generated by EzioChiu.
 */

@protocol _SFAppleConnectExtensionMessageReceiver <NSObject>

@required

- (void)dispatchMessageToContentScriptWithName:(NSString *)arg1 userInfo:(NSDictionary *)arg2;

@end
