/* Generated by EzioChiu.
 */

@protocol _TVIKAppDocumentDelegate <IKAppDocumentDelegate>

@required

- (struct CGSize { double x1; double x2; })tv_adjustedWindowSizeForDocument:(IKAppDocument *)arg1;

@end
