/* Generated by EzioChiu.
 */

@protocol _UIFocusFastScrollingRecognizerDelegate <NSObject>

@required

- (void)fastScrollingRecognizer:(_UIFocusFastScrollingRecognizer *)arg1 didRecognizeFastScrollingRequest:(_UIFocusFastScrollingRequest *)arg2;

@end
