/* Generated by EzioChiu.
 */

@protocol _VMSpeechRecognitionTaskDelegatePrivate <VMSpeechRecognitionTaskDelegate>

@optional

- (void)speechRecognitionTask:(id <VMSpeechRecognitionTask>)arg1 didProcessAudioDuration:(double)arg2;

@end
