/* Generated by EzioChiu.
 */

@protocol ADWebViewActionViewControllerDelegate <SFSafariViewControllerDelegate>

@optional

- (void)webViewActionViewControllerHomeButtonWasTapped:(ADWebViewActionViewController *)arg1;

@end
