/* Generated by EzioChiu.
 */

@protocol AFInterstitialConfigurationMutating <NSObject>

@required

- (void)setGender:(long long)arg1;
- (void)setLanguageCode:(NSString *)arg1;
- (void)setStyle:(long long)arg1;

@end
