/* Generated by EzioChiu.
 */

@protocol AKSignatureCreationControllerDelegate <NSObject>

@required

- (void)signatureCreationControllerDidCreateSignature:(AKSignatureCreationViewController_iOS *)arg1;

@end
