/* Generated by EzioChiu.
 */

@protocol BCDictionaryImageSerializable <BCDictionarySerializable>

@required

- (id)initWithDictionary:(NSDictionary *)arg1 imageDictionary:(NSDictionary *)arg2;

@end
