/* Generated by EzioChiu.
 */

@protocol BDSServiceProtocol <BCCloudAssetDetailManager, BCCloudReadingNowDetailManager, BCCloudAssetReviewManager, BCCloudStoreAssetManager, BCCloudCollectionDetailManager, BCCloudCollectionMemberManager, BCCloudKitSyncEnablement, BDSCloudKitSupportSignOut, BCCloudKitTransactionManagerService, BCCloudSecureUserDataManager>

@end
