/* Generated by EzioChiu.
 */

@protocol BWIrisStagingNodeEmitIrisRequestDelegate <NSObject>

@required

- (void)stagingNode:(BWIrisStagingNode *)arg1 willEmitIrisRequest:(BWIrisMovieInfo *)arg2;

@end
