/* Generated by EzioChiu.
 */

@protocol CAMFocusIndicatorViewDelegate <NSObject>

@optional

- (UIView *)focusIndicatorViewBoundingViewForClippingFocusIndicatorView:(CAMFocusIndicatorView *)arg1;

@end
