/* Generated by EzioChiu.
 */

@protocol CAMLightingCubeStyle

@required

+ (CAMLightingCubeAppearance *)contourAppearance;
+ (CAMLightingCubeAppearance *)naturalAppearance;
+ (CAMLightingCubeAppearance *)stageAppearance;
+ (CAMLightingCubeAppearance *)stageMonoAppearance;
+ (CAMLightingCubeAppearance *)studioAppearance;

@end
