/* Generated by EzioChiu.
 */

@protocol CAMNebulaDaemonIrisClientProtocol <NSObject>

@required

- (void)nebulaDaemonDidCompleteLocalVideoPersistenceWithResult:(CAMVideoLocalPersistenceResult *)arg1;

@end
