/* Generated by EzioChiu.
 */

@protocol CKAppManagerViewControllerDelegate <CKBrowserAppManagerViewControllerDelegate>

@required

- (void)appManagerViewControllerDidFinish:(CKAppManagerViewController *)arg1;

@end
