/* Generated by EzioChiu.
 */

@protocol CKConversationListCellDelegate <NSObject>

@optional

- (void)avatarHeaderWasTappedForConversation:(CKConversation *)arg1 inCell:(CKConversationListCell *)arg2;

@end
