/* Generated by EzioChiu.
 */

@protocol CKDetailsDownloadAttachmentsHeaderFooterViewDelegate <NSObject>

@required

- (void)userDidTapDownloadForAttachmentsFooterView:(CKDetailsDownloadAttachmentsHeaderFooterView *)arg1;

@end
