/* Generated by EzioChiu.
 */

@protocol CKImpactEffectAnimationProvider

@required

- (void)beginAnimationWithSendAnimationContext:(id <CKSendAnimationContext>)arg1;
- (void)stopAnimationWithSendAnimationContext:(id <CKSendAnimationContext>)arg1;

@end
