/* Generated by EzioChiu.
 */

@protocol CKInlineNotificationViewDelegate <NSObject>

@required

- (void)inlineNotificationView:(CKInlineNotificationView *)arg1 didChangeRequestedHeight:(double)arg2;

@end
