/* Generated by EzioChiu.
 */

@protocol CKMessageEntryRecordedAudioViewDelegate <NSObject>

@required

- (void)messageEntryRecordedAudioView:(CKMessageEntryRecordedAudioView *)arg1 mediaObjectDidFinishPlaying:(CKMediaObject *)arg2;

@end
