/* Generated by EzioChiu.
 */

@protocol CKPhotoPickerCollectionViewDelegate <NSObject>

@required

- (void)photoPickerCollectionViewAssetSelectionDidChange:(CKPhotoPickerCollectionViewController *)arg1;

@end
