/* Generated by EzioChiu.
 */

@protocol CKUnexpectedlyLoggedOutNotificationViewDelegate

@required

- (void)unexpectedlyLoggedOutNotificationView:(CKUnexpectedlyLoggedOutNotificationView *)arg1 didChangeRequestedHeight:(double)arg2;

@end
