/* Generated by EzioChiu.
 */

@protocol CNAccountsAndGroupsViewControllerDelegate <NSObject>

@required

- (void)accountsAndGroupsViewControllerDidFinish:(CNAccountsAndGroupsViewController *)arg1;

@end
