/* Generated by EzioChiu.
 */

@protocol CNContactActionsControllerDelegate <NSObject>

@required

- (void)contactActionsController:(CNContactActionsController *)arg1 didSelectAction:(CNUIUserActionItem *)arg2;

@end
