/* Generated by EzioChiu.
 */

@protocol CNContactListViewControllerDelegateInternal <CNContactListViewControllerDelegate>

@optional

- (UIResponder *)nextResponderForContactListViewController:(CNContactListViewController *)arg1;

@end
