/* Generated by EzioChiu.
 */

@protocol CNUIFavoritesEntryPickerDelegate <NSObject>

@required

- (void)favoritesEntryPicker:(CNUIFavoritesEntryPicker *)arg1 didPickEntry:(CNFavoritesEntry *)arg2;

@end
