/* Generated by EzioChiu.
 */

@protocol CNUIPeopleGroupsGridViewControllerDelegate <NSObject>

@required

- (void)peopleGroupsGridViewControllerDidChange:(CNUIPeopleGroupsGridViewController *)arg1;

@end
