/* Generated by EzioChiu.
 */

@protocol CNUIUserActionTemplateImage <NSObject>

@required

- (UIImage *)systemBlueImage;
- (UIImage *)systemDarkGrayImage;
- (UIImage *)systemMidGrayImage;
- (UIImage *)templateImage;
- (UIImage *)thirtyPercentAlphaWhiteImage;
- (UIImage *)whiteImage;

@end
