/* Generated by EzioChiu.
 */

@protocol CRKUserEditorTableViewControllerDelegate <NSObject>

@required

- (void)userEditorTableViewControllerDidFinishEditingUser:(CRKUserEditorTableViewController *)arg1;

@end
