/* Generated by EzioChiu.
 */

@protocol DNDRemoteServiceClientModeAssertionProtocol <NSObject>

@required

- (void)deliverModeAssertionInvalidation:(DNDModeAssertionInvalidation *)arg1 forClientIdentifier:(NSString *)arg2;

@end
