/* Generated by EzioChiu.
 */

@protocol DNDSRemoteServiceProviderDelegate <DNDSRemoteServiceProviderBehaviorResolutionDelegate, DNDSRemoteServiceProviderAssertionDelegate, DNDSRemoteServiceProviderStateDelegate, DNDSRemoteServiceProviderSettingsDelegate>

@end
