/* Generated by EzioChiu.
 */

@protocol DNDSLegacyAssertionSyncManagerDataSource <DNDSAssertionSyncManagerDataSource>

@required

- (NSDateInterval *)legacyAssertionSyncManager:(id <DNDSAssertionSyncManager>)arg1 activeDateIntervalForModeAssertion:(DNDModeAssertion *)arg2;

@end
