/* Generated by EzioChiu.
 */

@protocol DNDSRemoteServiceProviderBehaviorResolutionDelegate <NSObject>

@required

- (DNDClientEventBehavior *)remoteServiceProvider:(DNDSRemoteServiceProvider *)arg1 resolveBehaviorForEventDetails:(DNDClientEventDetails *)arg2 clientIdentifier:(NSString *)arg3 date:(NSDate *)arg4 error:(id*)arg5;

@end
