/* Generated by EzioChiu.
 */

@protocol DOCHostTargetSelectionBrowserViewControllerProxy

@required

- (void)cancelPresentation;
- (void)dismissViewController;
- (void)filesExportedAtURLs:(NSArray *)arg1;

@end
