/* Generated by EzioChiu.
 */

@protocol EKEventAttachmentEditViewControllerDelegate <NSObject>

@optional

- (EKEvent *)owningEventForAttachmentEditViewController:(EKEventAttachmentEditViewController *)arg1;

@end
