/* Generated by EzioChiu.
 */

@protocol EQKitLayoutSchemataSubsuperscript <NSObject>

@required

- (<EQKitLayoutNode> *)schemataKernel;
- (<EQKitLayoutNode> *)schemataSubscript;
- (<EQKitLayoutNode> *)schemataSuperscript;

@end
