/* Generated by EzioChiu.
 */

@protocol FACircleRemoteUIDelegateDelegate <NSObject>

@required

- (void)FACircleRemoteUIDelegate:(FACircleRemoteUIDelegate *)arg1 completedWithSuccess:(bool)arg2 error:(NSError *)arg3;

@end
