/* Generated by EzioChiu.
 */

@protocol FCReadingListContentControllerObserving <NSObject>

@required

- (void)readingListContentControllerDidUpdateArticleAvailabilityInOfflineMode:(FCReadingListContentController *)arg1;

@end
