/* Generated by EzioChiu.
 */

@protocol FMMapAnnotationGestureRecognizerDelegate <UIGestureRecognizerDelegate>

@required

- (void)fingerOffAnnotation:(FMMapAnnotationGestureRecognizer *)arg1;
- (void)fingerOnAnnotation:(FMMapAnnotationGestureRecognizer *)arg1;

@end
