/* Generated by EzioChiu.
 */

@protocol HKDisplayTypeContextCollectionViewCellDelegate <NSObject>

@required

- (void)didTapOnInfoButtonForCollectionViewCell:(HKDisplayTypeContextCollectionViewCell *)arg1;

@end
