/* Generated by EzioChiu.
 */

@protocol HMDCameraSettingProactiveReaderDelegate <NSObject>

@required

- (void)cameraSettingProactiveReaderDidCompleteRead:(HMDCameraSettingProactiveReader *)arg1 negotiateStreamMessageWasHandled:(bool)arg2;

@end
