/* Generated by EzioChiu.
 */

@protocol HROnboardingPageViewControllerDelegate <NSObject>

@required

- (HKDateCache *)dateCache;
- (HKHealthStore *)healthStore;
- (<HROnboardingManagerDelegate> *)onboardingManagerDelegate;
- (void)stepForward;

@optional

- (void)notNowTapped;
- (void)setUserInfo:(NSMutableDictionary *)arg1;
- (NSMutableDictionary *)userInfo;

@end
