/* Generated by EzioChiu.
 */

@protocol HUAboutResidentDeviceViewControllerDelegate <NSObject>

@required

- (void)aboutResidentDeviceViewControllerDidFinish:(HUAboutResidentDeviceViewController *)arg1;

@end
