/* Generated by EzioChiu.
 */

@protocol HUQuickControlColorPaletteViewInteractionDelegate <HUQuickControlViewInteractionDelegate>

@required

- (void)controlView:(id <HUQuickControlInteractiveView>)arg1 colorPaletteDidChange:(HFColorPalette *)arg2;

@end
