/* Generated by EzioChiu.
 */

@protocol ICDocCamImageQuadEditPanGestureRecognizerDelegate <NSObject>

@required

- (void)touchesBeganOnQuadEditPanGestureRecognizerDelegate:(ICDocCamImageQuadEditPanGestureRecognizer *)arg1;

@end
