/* Generated by EzioChiu.
 */

@protocol LPLinkMetadataPresentationTransformerAdaptor

@required

- (LPWebLinkPresentationProperties *)presentationPropertiesForTransformer:(LPLinkMetadataPresentationTransformer *)arg1;

@end
