/* Generated by EzioChiu.
 */

@protocol MCProfileViewControllerDelegate <NSObject>

@optional

- (void)profileViewControllerDidSelectRemoveProfile:(MCProfileViewController *)arg1;
- (void)profileViewControllerDidSelectUpdateProfile:(MCProfileViewController *)arg1;

@end
