/* Generated by EzioChiu.
 */

@protocol MFMessageBodyConsumableInnerTextNode <NSObject>

@required

- (NSArray *)copyConsumableNodesAndAppendInnerTextToStringAccumulator:(id <MFMessageBodyStringAccumulator>)arg1;

@end
