/* Generated by EzioChiu.
 */

@protocol MKPlaceCardEncyclopedicControllerDelegate <NSObject>

@optional

- (void)placeCardEncyclopedicControllerDidExpandTextBlock:(MKPlaceEncyclopedicViewController *)arg1;
- (void)placeCardEncyclopedicControllerDidSelectShowArticle:(MKPlaceEncyclopedicViewController *)arg1;

@end
