/* Generated by EzioChiu.
 */

@protocol MKPlaceVenueBrowseViewControllerDelegate <NSObject>

@required

- (void)placeVenueBrowseViewController:(MKPlaceVenueBrowseViewController *)arg1 didTapOnSearchCategory:(GEOSearchCategory *)arg2;

@end
