/* Generated by EzioChiu.
 */

@protocol MNNavigationServiceRemoteProxyDelegate <MNNavigationServiceClientInterface>

@required

- (void)remoteProxyDidFinishReconnecting:(MNNavigationServiceRemoteProxy *)arg1;

@end
