/* Generated by EzioChiu.
 */

@protocol MPModelRequestDetailedKeepLocalStatusRequesting <NSObject>

@required

- (void)setWantsDetailedKeepLocalRequestableResponse:(bool)arg1;
- (bool)wantsDetailedKeepLocalRequestableResponse;

@end
