/* Generated by EzioChiu.
 */

@protocol MPMusicSubscriptionLeasePlaybackParticipating <NSObject>

@required

- (long long)leasePlaybackPreventionState;
- (ICMusicSubscriptionLeaseStatus *)leaseStatus;

@end
