/* Generated by EzioChiu.
 */

@protocol MTSpringboardStartMonitorDelegate <NSObject>

@required

- (void)springboardStartMonitor:(MTSpringboardStartMonitor *)arg1 didReceiveStarted:(bool)arg2;

@end
