/* Generated by EzioChiu.
 */

@protocol MusicSearchRecentsViewControllerDelegate <NSObject>

@optional

- (void)searchRecentsViewController:(MusicSearchRecentsViewController *)arg1 didSelectSearchTerm:(NSString *)arg2;

@end
