/* Generated by EzioChiu.
 */

@protocol MusicEntityVerticalSectionHeaderViewDelegate <NSObject>

@optional

- (void)sectionHeaderViewDidSelectButton:(MusicEntityVerticalSectionHeaderView *)arg1;

@end
