/* Generated by EzioChiu.
 */

@protocol MusicProductDescriptionTableViewCellDelegate <NSObject>

@optional

- (void)productDescriptionDidChangeForProductDescriptionTableViewCell:(MusicProductDescriptionTableViewCell *)arg1;

@end
