/* Generated by EzioChiu.
 */

@protocol MusicProductMetadataTableViewCellDelegate <NSObject>

@optional

- (void)switchDidChangeStateInProductMetadataTableViewCell:(MusicProductMetadataTableViewCell *)arg1;

@end
