/* Generated by EzioChiu.
 */

@protocol MusicLibraryBrowseCollectionViewControllerDelegate <NSObject>

@optional

- (void)collectionViewFlowLayoutLayoutMetricsWereUpdatedForLibraryBrowseCollectionViewController:(MusicLibraryBrowseCollectionViewController *)arg1;

@end
