/* Generated by EzioChiu.
 */

@protocol MusicMediaDetailHeaderViewControllerDelegate <NSObject>

@required

- (void)maximumMediaDetailHeaderHeightDidChangeForHeaderViewController:(UIViewController *)arg1;

@end
