/* Generated by EzioChiu.
 */

@protocol MusicEntityEditableVerticalLockupViewDelegate <MusicEntityVerticalLockupViewDelegate>

@optional

- (void)editableVerticalLockupView:(MusicEntityEditableVerticalLockupView *)arg1 didSelectCameraButton:(UIButton *)arg2;

@end
