/* Generated by EzioChiu.
 */

@protocol NCNotificationLongLookViewDelegate <PLExpandedPlatterViewDelegate>

@required

- (void)notificationLongLookView:(NCNotificationLongLookView *)arg1 willInteractWithURL:(NSURL *)arg2;

@end
