/* Generated by EzioChiu.
 */

@protocol NCViewControllerTransitioningDelegateObserver <NSObject>

@optional

- (void)transitioningDelegate:(id <NCViewControllerTransitioningDelegate>)arg1 animatorDidCommitToTransitionWithCoordinator:(id <UIViewControllerTransitionCoordinator>)arg2;

@end
