/* Generated by EzioChiu.
 */

@protocol NPTOImageViewDelegate <NSObject>

@optional

- (void)imageViewDidBeginPlaying:(NPTOImageView *)arg1;
- (void)imageViewDidEndPlaying:(NPTOImageView *)arg1;

@end
