/* Generated by EzioChiu.
 */

@protocol NTKCFaceDetailExpandableDescriptionCellDelegate <NSObject>

@required

- (void)descriptionCellDidExpand:(NTKCFaceDetailExpandableDescriptionCell *)arg1;

@end
