/* Generated by EzioChiu.
 */

@protocol NTKCompanionAppDelegate <NSObject>

@required

- (void)companionAppUpdatedIcon:(NTKCompanionApp *)arg1;
- (void)companionAppWasUpdated:(NTKCompanionApp *)arg1;

@end
