/* Generated by EzioChiu.
 */

@protocol NTKRichComplicationBezelViewDelegate <NSObject>

@optional

- (void)didUpdateBezelTextForRichComplicationBezelView:(NTKRichComplicationBezelView *)arg1;

@end
