/* Generated by EzioChiu.
 */

@protocol NUReportConcernViewPresenter <NSObject>

@required

- (void)presentReportConcernViewForHeadline:(id <FCHeadlineProviding>)arg1;
- (void)presentReportConcernViewForHeadline:(id <FCHeadlineProviding>)arg1;

@end
