/* Generated by EzioChiu.
 */

@protocol PHAGraphRegistration <PHAGraphManagerClientMessagesReceiver, PGGraphUpdateListener>

@required

- (bool)wantsGraphUpdateNotifications;
- (bool)wantsLiveGraphUpdates;

@end
