/* Generated by EzioChiu.
 */

@protocol PHAVisionServiceAssetsAnalyzingOperationDelegate <NSObject>

@optional

- (void)visionServiceAssetsProcessingOperation:(PHAVisionServiceAssetsAnalyzingOperation *)arg1 didExecuteToCompletion:(bool)arg2;

@end
