/* Generated by EzioChiu.
 */

@protocol PHClientSenderPropertySet <PHChangeRequest>

@required

- (PLAssetsdClientServiceSender *)clientSender;
- (void)setClientSender:(PLAssetsdClientServiceSender *)arg1;

@end
