/* Generated by EzioChiu.
 */

@protocol PKCompactNavigationContainerControllerDelegate <NSObject>

@optional

- (void)compactNavigationContainerControllerReceivedExternalTap:(PKCompactNavigationContainerController *)arg1;

@end
