/* Generated by EzioChiu.
 */

@protocol PKCommutePlanRenewalReminderSetupViewControllerDelegate <NSObject>

@required

- (void)commutePlanRenewalReminderValueDidChange:(PKCommutePlanRenewalReminderSetupViewController *)arg1;

@end
