/* Generated by EzioChiu.
 */

@protocol PKLowBalanceReminderSetupViewControllerDelegate <NSObject>

@required

- (void)lowBalanceReminderValueDidChange:(PKLowBalanceReminderSetupViewController *)arg1;

@end
