/* Generated by EzioChiu.
 */

@protocol PKPassPersonalizationFooterViewDelegate <NSObject>

@required

- (void)passPersonalizationFooterViewPrivacyLinkPressed:(PKPassPersonalizationFooterView *)arg1;

@end
