/* Generated by EzioChiu.
 */

@protocol PLAlbumStreamingOptionsViewControllerDelegate <NSObject>

@required

- (void)albumStreamingOptionsViewController:(PLAlbumStreamingOptionsViewController *)arg1 didCompleteWithReason:(int)arg2;

@end
