/* Generated by EzioChiu.
 */

@protocol PSKeyboardNavigationSearchResultsController

@required

- (void)selectNextSearchResult;
- (void)selectPreviousSearchResult;
- (void)showSelectedSearchResult;

@end
