/* Generated by EzioChiu.
 */

@protocol PUActivityViewControllerDelegate <NSObject>

@optional

- (bool)activityViewControllerShouldCancelAfterPreparationCanceled:(PUActivityViewController *)arg1;

@end
