/* Generated by EzioChiu.
 */

@protocol PUFeedImageCellDelegate <PUFeedCellDelegate>

@optional

- (void)didTapCommentButtonInFeedImageCell:(PUFeedImageCell *)arg1;
- (void)didTapOverlayPlayButtonInFeedImageCell:(PUFeedImageCell *)arg1;

@end
