/* Generated by EzioChiu.
 */

@protocol PULivePhotoKeyFrameSelectionViewControllerDelegate <NSObject>

@required

- (void)userDidRequestToMakeKeyPhoto:(PULivePhotoKeyFrameSelectionViewController *)arg1;

@end
