/* Generated by EzioChiu.
 */

@protocol PUOneUpPhotosSharingTransitionViewController <PUPhotosSharingTransitionViewController>

@required

- (void)setOneUpPhotosSharingTransitionContext:(PUOneUpPhotosSharingTransitionContext *)arg1;
- (void)setOneUpPhotosSharingTransitionInfo:(PUOneUpAssetTransitionInfo *)arg1;

@end
