/* Generated by EzioChiu.
 */

@protocol PUOverOneUpPresentationSessionViewController <NSObject>

@required

- (PUOverOneUpPresentationSession *)overOneUpPresentationSessionCreateIfNeeded:(bool)arg1;

@end
