/* Generated by EzioChiu.
 */

@protocol PUPhotoBrowserTitleViewControllerDelegate <NSObject>

@optional

- (void)photoBrowserTitleViewControllerTapped:(PUPhotoBrowserTitleViewController *)arg1;

@end
