/* Generated by EzioChiu.
 */

@protocol PUPlayButtonTileViewControllerDelegate <NSObject>

@optional

- (double)playButtonTileViewController:(PUPlayButtonTileViewController *)arg1 delayForButtonAnimation:(bool)arg2;
- (void)playButtonTileViewController:(PUPlayButtonTileViewController *)arg1 didTapButton:(bool)arg2;

@end
