/* Generated by EzioChiu.
 */

@protocol PXCMMComposeRecipientDataSourceManagerDelegate <NSObject>

@required

- (void)composeRecipientDataSourceManager:(PXCMMComposeRecipientDataSourceManager *)arg1 didUpdateDataSourceWithChangeDetails:(PXArrayChangeDetails *)arg2;

@end
