/* Generated by EzioChiu.
 */

@protocol PXFeedSectionInfosManagerDelegate <NSObject>

@required

- (void)feedSectionInfosManager:(PXFeedSectionInfosManager *)arg1 sectionInfosDidChange:(PXFeedSectionInfosChange *)arg2;

@end
