/* Generated by EzioChiu.
 */

@protocol PXForYouRankable

@required

- (long long)defaultPriority;
- (unsigned long long)gadgetType;
- (NSDate *)priorityDate;
- (long long)priorityType;
- (void)resetPriorityDate;

@end
