/* Generated by EzioChiu.
 */

@protocol PXGadgetNavigating <NSObject>

@required

- (void)navigateToGadgetForCMMInvitationWithIdentifier:(NSString *)arg1;
- (void)navigateToGadgetForCMMSuggestions;
- (void)presentWelcomeCloudPhotosViewController;

@end
