/* Generated by EzioChiu.
 */

@protocol PXImportStatusObserver <NSObject>

@required

- (void)importStatusManager:(id <PXImportStatusManager>)arg1 didChangeStatusForAssetReference:(PXAssetReference *)arg2;

@end
