/* Generated by EzioChiu.
 */

@protocol PXMemoriesOnboardingViewControllerDelegate <NSObject>

@required

- (void)memoriesOnboardingViewControllerDidTapContinueButton:(PXMemoriesOnboardingUIViewController *)arg1;

@end
