/* Generated by EzioChiu.
 */

@protocol PXPhotosGlobalFooterViewModelPresentationDelegate

@required

- (UIViewController *)presentingViewControllerForViewModel:(PXPhotosGlobalFooterViewModel *)arg1;

@end
