/* Generated by EzioChiu.
 */

@protocol PXSearchRecipientControllerDelegate <NSObject>

@optional

- (void)searchRecipientController:(PXSearchRecipientController *)arg1 didSelectRecipient:(PXRecipient *)arg2;

@end
