/* Generated by EzioChiu.
 */

@protocol PXSlideshowSessionDelegate <NSObject>

@optional

- (void)slideshowSession:(PXSlideshowSession *)arg1 didPrepareSlideshow:(OKPresentationViewController *)arg2;

@end
