/* Generated by EzioChiu.
 */

@protocol PXUIViewControllerZoomTransitionEndPoint <PXUIViewControllerTransitionEndPoint>

@optional

- (PXZoomAnimationCoordinator *)zoomAnimationCoordinatorForZoomTransition:(PXUIViewControllerZoomTransition *)arg1;

@end
