/* Generated by EzioChiu.
 */

@protocol SBUIIconForceTouchViewControllerDelegate <NSObject>

@required

- (void)iconForceTouchViewControllerDidDismiss:(SBUIIconForceTouchViewController *)arg1;
- (void)iconForceTouchViewControllerWillDismiss:(SBUIIconForceTouchViewController *)arg1;

@end
