/* Generated by EzioChiu.
 */

@protocol SBUIRemoteAlertServiceInterface_Internal <SBUIRemoteAlertServiceInterface>

@required

- (void)sb_becomeFirstResponder;
- (void)sb_resignFirstResponder;

@end
