/* Generated by EzioChiu.
 */

@protocol SearchUISelectableTextViewDelegate <UITextViewDelegate>

@required

- (void)selectableTextView:(SearchUISelectableTextView *)arg1 presentViewController:(UIViewController *)arg2;

@end
