/* Generated by EzioChiu.
 */

@protocol SegmentStatsDelegate <NSObject>

@required

- (unsigned int)audioErasureCount;
- (double)audioErasureTotalTime;
- (unsigned int)significantVideoStallCount;
- (double)significantVideoStallTotalTime;
- (double)timeWeightedNumberOfParticipants;

@end
