/* Generated by EzioChiu.
 */

@protocol SFCertificateWarningJSControllerMethods <JSExport>

@required

- (void)goBackSelected;
- (void)openClockSettings;
- (void)pageLoaded;
- (void)showCertificateInformation;
- (void)visitInsecureWebsite;
- (void)visitInsecureWebsiteWithTemporaryBypass;

@end
