/* Generated by EzioChiu.
 */

@protocol SFCredentialProviderExtensionManagerObserver <NSObject>

@required

- (void)credentialProviderExtensionManagerExtensionListDidChange:(SFCredentialProviderExtensionManager *)arg1;

@end
