/* Generated by EzioChiu.
 */

@protocol SFExternalPasswordCredentialRemoteViewControllerDelegate <SFPasswordRemoteViewControllerDelegate>

@required

- (void)presentExternalPasswordCredentialRemoteViewController:(SFExternalPasswordCredentialRemoteViewController *)arg1;

@end
