/* Generated by EzioChiu.
 */

@protocol SFQueueingServiceViewControllerProxyDelegate <NSObject>

@required

- (void)serviceProxyWillQueueInvocation:(SFQueueingServiceViewControllerProxy *)arg1;

@end
