/* Generated by EzioChiu.
 */

@protocol SFReaderAppearanceThemeSelectorTableViewCellDelegate <NSObject>

@required

- (void)readerAppearanceThemeSelectorDidChangeTheme:(SFReaderAppearanceThemeSelectorTableViewCell *)arg1;

@end
