/* Generated by EzioChiu.
 */

@protocol SKUIComposeReviewFormDelegate <NSObject>

@optional

- (void)composeReviewFormDidCancel:(SKUIComposeReviewFormViewController *)arg1;
- (void)composeReviewFormDidSubmit:(SKUIComposeReviewFormViewController *)arg1;

@end
