/* Generated by EzioChiu.
 */

@protocol SKUIScrollingSegmentedControllerItemContextDelegate <NSObject>

@optional

- (void)contentScrollViewDidChangeForScrollingSegmentedControllerItemContext:(SKUIScrollingSegmentedControllerItemContext *)arg1;

@end
