/* Generated by EzioChiu.
 */

@protocol SKUIMoreNavigationControllerDelegate <NSObject>

@optional

- (void)moreNavigationController:(SKUIMoreNavigationController *)arg1 didSelectItemAtIndex:(long long)arg2;

@end
