/* Generated by EzioChiu.
 */

@protocol SKUIScrollingSegmentedControllerCollectionViewDelegate <UICollectionViewDelegate>

@optional

- (void)scrollingSegmentedControllerCollectionViewDidLayoutSubviews:(SKUIScrollingSegmentedControllerCollectionView *)arg1;

@end
