/* Generated by EzioChiu.
 */

@protocol SKUINavigationControllerDelegate <UINavigationControllerDelegate>

@optional

- (IKJSNavigationDocument *)jsNavigationDocumentForNavigationController:(UINavigationController *)arg1 inContext:(JSContext *)arg2;

@end
