/* Generated by EzioChiu.
 */

@protocol SKUIScrollingTabBarContentCollectionViewDelegate <UICollectionViewDelegate>

@optional

- (void)scrollingTabBarContentCollectionViewDidLayoutSubviews:(SKUIScrollingTabBarContentCollectionView *)arg1;

@end
