/* Generated by EzioChiu.
 */

@protocol SLFacebookVideoOptionsDelegate

@required

- (void)videoOptionsViewController:(SLFacebookVideoOptionsViewController *)arg1 didSelectVideoQualityOption:(SLVideoQualityOption *)arg2;

@end
