/* Generated by EzioChiu.
 */

@protocol SLFacebookAlbumChooserViewControllerDelegate <NSObject>

@required

- (void)albumChooserViewController:(SLFacebookAlbumChooserViewController *)arg1 didSelectAlbum:(id)arg2;

@end
