/* Generated by EzioChiu.
 */

@protocol SSAuthorizationRequestDelegate <SSRequestDelegate>

@optional

- (void)authorizationRequest:(SSAuthorizationRequest *)arg1 didReceiveResponse:(SSURLConnectionResponse *)arg2;

@end
