/* Generated by EzioChiu.
 */

@protocol SSTestingCoordinatorDelegate

@required

- (void)testingCoordinator:(SSTestingCoordinator *)arg1 requestsTakingScreenshotForRunPPTRequest:(SSUIRunPPTServiceRequest *)arg2;

@end
