/* Generated by EzioChiu.
 */

@protocol STDeviceBedtimeListControllerDelegate <NSObject>

@required

- (void)bedtimeListController:(STDeviceBedtimeListController *)arg1 didFinishEditingBedtime:(STDeviceBedtime *)arg2;

@end
