/* Generated by EzioChiu.
 */

@protocol STTextTangierRepAccessibilityElement

@required

- (<STTextTangierRepAccessibilityDataSource> *)accessibilityDataSource;
- (void)setAccessibilityDataSource:(id <STTextTangierRepAccessibilityDataSource>)arg1;

@end
