/* Generated by EzioChiu.
 */

@protocol SUInstallationConstraintObserverDelegate <SUInstallationConstraintMonitorDelegate>

@required

- (void)installationConstraintObserverDidRemoveAllObserverBlocks:(SUInstallationConstraintObserver *)arg1;

@end
