/* Generated by EzioChiu.
 */

@protocol SVPlaybackTransitionCoordinatorFactory <NSObject>

@required

- (<SVInteractivePlaybackTransitioning><SVPlaybackTransitionCoordinator> *)createTransitionCoordinator;

@end
