/* Generated by EzioChiu.
 */

@protocol SVVideoPresentationSizeObserverFactory <NSObject>

@required

- (<SVVideoPresentationSizeObserving> *)createPresentationSizeObserverForVideo:(id <SVVideo>)arg1;

@end
