/* Generated by EzioChiu.
 */

@protocol SVVideoAdActionAvailabilityObserverFactory <NSObject>

@required

- (<SVVideoAdActionAvailabilityObserver> *)createActionAvailabilityObserverForVideo:(id <SVVideo>)arg1;

@end
