/* Generated by EzioChiu.
 */

@protocol SVVideoAccessoryItemDisplayModeTransitionCoordinatorProviding <NSObject>

@required

- (<SVVideoAccessoryItemDisplayModeTransitioning> *)displayModeTransitionCoordinatorForAnimatedTransition:(bool)arg1;

@end
