/* Generated by EzioChiu.
 */

@protocol SVVideoPlaybackAttemptTrackerFactory <NSObject>

@required

- (<SVVideoPlaybackAttemptTracking> *)createPlaybackAttemptTrackerForVideo:(id <SVVideo>)arg1;

@end
