/* Generated by EzioChiu.
 */

@protocol SXAutomaticFullscreenVideoPlaybackBehaviorManagerDelegate <NSObject>

@required

- (void)fullscreenBehaviorManagerRequiresFullscreenPlayback:(SXAutomaticFullscreenVideoPlaybackBehaviorManager *)arg1;

@end
