/* Generated by EzioChiu.
 */

@protocol SXForceTouchComponentInteractionHandler <NSObject>

@required

- (void)commitViewController:(UIViewController *)arg1;
- (UIViewController *)previewViewController;

@end
