/* Generated by EzioChiu.
 */

@protocol SXFullscreenNavigationBarViewDelegate <NSObject>

@required

- (void)fullscreenNavigationBarViewDoneButtonPressed:(SXFullscreenNavigationBarView *)arg1;

@end
