/* Generated by EzioChiu.
 */

@protocol SXWebContentComponentInteractionHandlerFactory <NSObject>

@required

- (<SXComponentInteractionHandler> *)componentInteractionHandlerForInteraction:(id <SXWebContentInteraction>)arg1;

@end
