/* Generated by EzioChiu.
 */

@protocol TKVibrationPickerCollectionViewCellDelegate <NSObject>

@optional

- (void)vibrationPickerCollectionViewCell:(TKVibrationPickerCollectionViewCell *)arg1 endedEditingWithText:(NSString *)arg2;

@end
