/* Generated by EzioChiu.
 */

@protocol TSArticleRecirculationRoutedType

@required

- (<TSArticleRecirculationRoutableFeedDelegate> *)routableDelegate;
- (void)setRoutableDelegate:(id <TSArticleRecirculationRoutableFeedDelegate>)arg1;

@end
