/* Generated by EzioChiu.
 */

@protocol TSArticleRecirculationModuleType

@required

- (<TSArticleRecirculationViewControllersProviderType> *)createViewControllersWithData:(TSArticleRecirculationData *)arg1 nativeAdCellDataProvider:(id <TSNativeAdDataProviderType>)arg2;

@end
