/* Generated by EzioChiu.
 */

@protocol TSArticleRecirculationViewControllerDelegate

@required

- (void)shouldPresentRecirculationController:(UIViewController<TSArticleRecirculationViewControllerType> *)arg1;

@end
