/* Generated by EzioChiu.
 */

@protocol TSCellularPlanQRCodeScannerCaptureDelegate <AVCaptureMetadataOutputObjectsDelegate>

@optional

- (void)captureSession:(TSCellularPlanQRCodeScannerView *)arg1 isRunning:(bool)arg2;

@end
