/* Generated by EzioChiu.
 */

@protocol TSNavigationBarHeightManagerProviding

@required

- (<TSNavigationBarHeightManager> *)navigationBarHeightManager;
- (void)setNavigationBarHeightManager:(id <TSNavigationBarHeightManager>)arg1;

@end
