/* Generated by EzioChiu.
 */

@protocol TSSwipeActionControllerType <NSObject>

@required

- (void)ts_restoreSwipedIndexPath:(NSIndexPath *)arg1 animated:(bool)arg2;
- (NSIndexPath *)ts_swipedIndexPath;

@end
