/* Generated by EzioChiu.
 */

@protocol TSTabBarSplitViewPresentable

@required

- (NSString *)tabBarSplitViewIdentifier;
- (TSTabBarSplitViewPresentable *)tabBarSplitViewPresentationFor:(long long)arg1;

@end
