/* Generated by EzioChiu.
 */

@protocol TSTStrokeLayerEnumerating

@required

- (void)replaceStrokeLayerAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (TSTStrokeLayer *)strokeLayerAtIndex:(unsigned long long)arg1;
- (unsigned long long)strokeLayerCount;

@end
