/* Generated by EzioChiu.
 */

@protocol TSVideoPlayerModuleType

@required

- (UIViewController *)createViewControllerWithArticleIDs:(NSArray *)arg1 referral:(TSAnalyticsReferral *)arg2;
- (UIViewController *)createViewControllerWithWidgetVideoPlaylist:(TSNewsReferralItemWidgetVideoPlaylist *)arg1 referral:(TSAnalyticsReferral *)arg2;

@end
