/* Generated by EzioChiu.
 */

@protocol TSVideoGroupRoutedType

@required

- (<TSVideoGroupRoutableFeedDelegate> *)routableDelegate;
- (void)setRoutableDelegate:(id <TSVideoGroupRoutableFeedDelegate>)arg1;

@end
