/* Generated by EzioChiu.
 */

@protocol TURouteControllerDelegate <NSObject>

@optional

- (void)routesChangedForRouteController:(TURouteController *)arg1;
- (void)routesChangedForRouteController:(TURouteController *)arg1;

@end
