/* Generated by EzioChiu.
 */

@protocol UIActivityItemApplicationExtensionSource <NSObject>

@required

- (NSItemProvider *)activityViewControllerApplicationExtensionItem:(UIActivityViewController *)arg1;

@end
