/* Generated by EzioChiu.
 */

@protocol UIActivityViewControllerDelegate <NSObject>

@optional

- (void)activityViewControllerDidFinishAirdropTransfer:(UIActivityViewController *)arg1;
- (void)activityViewControllerWillStartAirdropTransfer:(UIActivityViewController *)arg1;

@end
