/* Generated by EzioChiu.
 */

@protocol VCUIActionStatusViewDelegate <VCUIActionStatusViewProgressViewControllerProviding>

@required

- (void)actionStatusView:(VCUIActionStatusView *)arg1 didAddViewFromProgressViewController:(UIViewController *)arg2;

@end
