/* Generated by EzioChiu.
 */

@protocol VCUIAlternativeTranscriptionsViewDelegate

@required

- (void)alternativeTranscriptionsView:(VCUIAlternativeTranscriptionsView *)arg1 didSelectTranscription:(NSString *)arg2;

@end
