/* Generated by EzioChiu.
 */

@protocol VideosExtrasZoomingImageInteractiveTransitionSource <NSObject>

@required

- (void)handlePinchGestureForZoomingImageInteractiveTransitionWithContext:(VideosExtrasZoomingImageInteractiveTransitionSourceContext *)arg1;

@end
