/* Generated by EzioChiu.
 */

@protocol VSAutoAuthenticationViewModelDelegate <NSObject>

@required

- (void)autoAuthenticationViewModelDidManualSignInButton:(VSAutoAuthenticationViewModel *)arg1;

@end
