/* Generated by EzioChiu.
 */

@protocol VUIMediaLibraryFetchControllerQueueDelegate <NSObject>

@required

- (void)fetchDidCompleteForMediaLibraryFetchControllerQueue:(VUIMediaLibraryFetchControllerQueue *)arg1;

@end
