/* Generated by EzioChiu.
 */

@protocol WBSCoalescedAsynchronousWriterDelegate <NSObject>

@optional

- (void)coalescedAsynchronousWriter:(WBSCoalescedAsynchronousWriter *)arg1 didFinishWritingData:(NSData *)arg2;

@end
