/* Generated by EzioChiu.
 */

@protocol WBSParsecSearchMapsResultFeedbackSenderClient

@required

- (WBSParsecSearchMapsResultFeedbackSender *)mapsFeedbackSender;
- (void)setMapsFeedbackSender:(WBSParsecSearchMapsResultFeedbackSender *)arg1;

@end
