/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADEventAndReminderOperationProxy : CADOperationProxy

+ (id)allOperationGroupClasses;

@end
