/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADRemindersOperationProxy : CADReminderOnlyOperationProxy

+ (id)allOperationGroupClasses;

@end
