/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADSpringBoardOperationProxy : CADEventAndReminderOperationProxy

+ (id)allOperationGroupClasses;

@end
