/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPAppleTVMetadataProviderSpecialization : LPMetadataProviderSpecialization

+ (id)specializedMetadataForCompleteMetadata:(id)arg1 URL:(id)arg2;

@end
