/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPHTMLGlyphComponent : LPHTMLComponent

+ (id)ruleDictionaryForStyle:(id)arg1;
+ (id)styleSet;

- (id)initWithStyle:(id)arg1 generator:(id)arg2;

@end
