/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPPlaceholderPlayButton : LPPlayButton

- (id)initWithStyle:(id)arg1;

@end
