/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPSettings : NSObject

+ (bool)disableLegacyStoreLookups;
+ (void)initialize;
+ (bool)showDebugIndicators;
+ (bool)subsampleImagesToScreenSize;

@end
