/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface VCMovieWriterUtil : NSObject

+ (id)getMetaDataArrayWithIndentifier:(id)arg1;

@end
