/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface VCSessionErrorUtils : NSObject

+ (id)VCSessionErrorEvent:(unsigned int)arg1 errorPath:(id)arg2;
+ (id)VCSessionParticipantErrorEvent:(unsigned int)arg1 errorPath:(id)arg2;

@end
