/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface VCVideoRuleCollectionsMoments : NSObject

+ (id)sharedInstance;

- (int)getMomentsCapabilities;

@end
