/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMTranscoderAgent.framework/IMTranscoderAgent
 */

@interface IMTranscoder_TextRendering : IMTranscoder

+ (id)supportedUTIs;

- (void)validateTextRenderingForMessage:(id)arg1 completionBlock:(id /* block */)arg2;

@end
