/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface CNKBuzzedAnimator : NSObject <UIViewControllerAnimatedTransitioning>

- (void)animateTransition:(id)arg1;
- (id)init;
- (double)transitionDuration:(id)arg1;

@end
