/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface CNKFaceTimeCameraViewController : CFXCameraViewController {
    void cameraDelegate;
}

@property (nonatomic) <CNKFaceTimeCameraViewControllerDelegate> *cameraDelegate;

- (id /* block */).cxx_destruct;
- (id)cameraDelegate;
- (void)effectBrowserViewController:(id)arg1 didSelectApp:(id)arg2;
- (id)initWithCaptureMode:(long long)arg1 devicePosition:(long long)arg2 flashMode:(long long)arg3;
- (void)setCameraDelegate:(id)arg1;

@end
