/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.StagingAreaViewControllerLayout : SwiftObject {
    void currentConstraints;
    void effectsConstraintManagers;
    void stateConstraints;
}

@end
