/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.LargeStagingAreaViewControllerLayout : SwiftObject {
    void constraintManagers;
    void containingView;
    void currentConstraints;
    void currentDeviceOrientation;
    void currentSize;
    void effectsConstraintManagers;
}

@end
