/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.PlatformDisplayLink : ConversationKit.PlatformDisplayLinkBase {
    void isRunning;
    void observers;
}

@end
