/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.GridViewConstraintManager : SwiftObject {
    void constraints;
}

@end
