/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.RadarSession : SwiftObject {
    void decoder;
    void encoder.storage;
    void pendingTask;
    void session;
}

@end
