/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.InCallControlsFramesCache : SwiftObject {
    void inCallControlsViewFrames;
}

@end
