/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.PlatformDisplayLinkBase : SwiftObject {
    void callbackWrapper;
    void displayLink.storage;
}

@end
