/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIChineseShared : NSObject

+ (id)defaultFuzzyPinyinPairs;
+ (id)validFuzzyPinyinPairs;

@end
