/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIKeyboardBehaviors_Cangjie : TIKeyboardBehaviors

- (id)keyBehaviorsForState:(id)arg1;

@end
