/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIMutableCharacterSetDescription : TICharacterSetDescription

+ (bool)supportsSecureCoding;

- (void)addCharactersInString:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
