/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoAudioControl.framework/NanoAudioControl
 */

@interface NACRoutingController : NSObject

+ (id)companionRoutingControllerWithAudioCategory:(id)arg1;
+ (id)localRoutingControllerWithAudioCategory:(id)arg1;
+ (id)proxyRoutingControllerWithAudioCategory:(id)arg1;

@end
