/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebBookmarks.framework/WebBookmarks
 */

@interface WebBookmarkCloudKitSyncCollection : WebBookmarkCollection

- (void)dealloc;

@end
