/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSDNoDefaultImplicitActionShapeLayer : CAShapeLayer

+ (id)defaultActionForKey:(id)arg1;

@end
