/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSDNonInteractiveFloatingInsertionContext : TSDNonInteractiveInsertionContext

- (bool)insertFloating;

@end
