/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSDNoDefaultImplicitActionTransformLayer : CATransformLayer

+ (id)defaultActionForKey:(id)arg1;

@end
