/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSDTrackingController : NSObject

- (void)interactiveCanvasControllerUpdatedRepsFromLayouts:(id)arg1;
- (void)popDisableUpdates;
- (void)pushDisableUpdates;
- (void)teardown;

@end
