/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSKReverseShadowButton : UIButton

- (void)setHighlighted:(bool)arg1;
- (void)setSelected:(bool)arg1;

@end
