/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
 */

@interface TSWPLongPressGestureRecognizer : UILongPressGestureRecognizer

- (void)reset;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end
