/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVSecondScreenPlayerLayerView : UIView {
    AVPlayerLayer * _activeSourcePlayerLayer;
}

@property (nonatomic) AVPlayerLayer *activeSourcePlayerLayer;
@property (nonatomic, readonly) AVPlayerLayer *layer;

+ (Class)layerClass;

- (void).cxx_destruct;
- (id)activeSourcePlayerLayer;
- (void)dealloc;
- (void)setActiveSourcePlayerLayer:(id)arg1;
- (void)startShowingContentFromSourcePlayerLayer:(id)arg1;
- (void)stopShowingContentFromActiveSourcePlayerLayer;

@end
