/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
 */

@interface SignpostSupportUniquePIDWhitelist : SignpostSupportUniquePIDFilter

- (unsigned long long)_compoundPredicateType;
- (bool)_wantsNotEqual;
- (bool)passesUniquePIDNumber:(id)arg1;

@end
