/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
 */

@interface SignpostSupportPIDWhitelist : SignpostSupportPIDFilter

- (unsigned long long)_compoundPredicateType;
- (bool)_wantsNotEqual;
- (bool)passesPIDNumber:(id)arg1;

@end
