/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
 */

@interface SignpostSupportExactProcessNameBlacklist : SignpostSupportExactProcessNameFilter

- (unsigned long long)_compoundPredicateType;
- (bool)_wantsNotEqual;
- (bool)passesProcessName:(id)arg1;

@end
