/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

@interface ICSTimeZoneTranslator : NSObject

+ (void)initializeTimeZoneIDTranslation;
+ (id)timeZoneNameForTimeZoneID:(id)arg1;

@end
