/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProactiveSupport.framework/ProactiveSupport
 */

@interface _PASCrashHelper : NSObject

+ (void)simulateCrashWithDescription:(id)arg1;

@end
