/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface __UIAccessibilityValidateBlockSignatureSentinel : NSObject

@end
