/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface AXMobileConfigurationInterface : NSObject

+ (id)activeRestrictionIdentifiers;

@end
