/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface AXSubsystemSpeakThis : AXLoggingSubsystem

+ (id)identifier;

@end
