/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PlacesKit.framework/PlacesKit
 */

@interface PXPlacesMapInPlaceLayoutDiffer : PXPlacesMapLayoutDiffer

- (void)_computeChanges;

@end
