/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PlacesKit.framework/PlacesKit
 */

@interface PXPlacesMapDefaultLayoutDiffer : PXPlacesMapLayoutDiffer

- (id)_allGeotaggablesForLayoutResult:(id)arg1;
- (void)_computeChanges;
- (id)_geotaggableToLayoutItemMapForLayoutResult:(id)arg1;

@end
