/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFFetchGlobalRestrictionsResultObject : DMFFetchRestrictionsResultObject

@end
