/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

@interface DAAggDReporter : NSObject

+ (void)endDailyAggDReporter;
+ (void)reportActiveExchangeOAuthAccountsCount;
+ (void)startDailyAggDReporter;

@end
