/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SilexVideo.framework/SilexVideo
 */

@interface SVPlayer : AVPlayer {
    int  _audioMode;
}

@property (nonatomic, readonly) int audioMode;

- (int)audioMode;
- (void)dealloc;
- (id)initWithAudioMode:(int)arg1;

@end
