/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoSubscriberAccountUI.framework/VideoSubscriberAccountUI
 */

@interface VSAppDocumentControllerFactory : NSObject

+ (id)appDocumentControllerForAppDocument:(id)arg1 error:(id*)arg2;

@end
