/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoSubscriberAccountUI.framework/VideoSubscriberAccountUI
 */

@interface VSStoreIdentityProviderResponseValueTransformer : VSCompoundValueTransformer

- (id)init;

@end
