/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeedLayout.framework/NewsFeedLayout
 */

@interface NFLGenericCellImageOnTopProperties : NFLAbstractHeadlineProperties

- (double)imageAspectRatio;
- (double)maxWhiteSpace;
- (double)topImageToPublisherLogoSpacing;

@end
