/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeedLayout.framework/NewsFeedLayout
 */

@interface NFLHorizontalTwoSubBatchLayout : NFLHorizontalSubBatchLayout

- (bool)isValid;

@end
