/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccountModel : HMDBackingStoreModelObject

@property (nonatomic, retain) HMDAccountIdentifier *identifier;

+ (id)properties;

@end
