/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingUpdateRelayReceiver : HMDAccessorySettingUpdateReceiver

+ (id)logCategory;

- (id)description;

@end
