/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDBackingStoreLogPrunePushedOperation : HMDBackingStoreOperation

- (id)init;
- (void)main;

@end
