/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHomeZoneUploadLogEvent : HMDLogEvent

+ (id)uploadToHomeZone;
+ (id)uuid;

@end
