/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHomeZoneFetchLogEvent : HMDLogEvent

+ (id)fetchFromHomeZone;
+ (id)uuid;

@end
