/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHelperExternalProtocolImpl : NSObject <HMDHelperExternalProtocol>

- (id)createAFSecurityConnection;
- (id)init;

@end
