/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHomeManagerFetchLogEvent : HMDLogEvent

+ (id)fetchFromHomeManager;
+ (id)uuid;

@end
