/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHomeKitVersion : HMFVersion <NSCopying, NSSecureCoding>

+ (id)version;

@end
