/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDRelayAccessTokenModel : HMDBackingStoreModelObject

@property (nonatomic, retain) NSData *accessToken;
@property (nonatomic, retain) NSString *accessoryIdentifier;

+ (id)properties;

- (id)dependentUUIDs;

@end
