/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDUploadMaximumDelayEvent : HMDLogEvent

+ (id)uploadMaximumDelay;
+ (id)uuid;

@end
