/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface CFXAnalyticsKeys : NSObject

+ (id)allDistributionEvents;
+ (id)allEventNames;
+ (id)allIncrementScalarEffectEvents;
+ (id)allIncrementScalarEvents;

@end
