/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface CFXBundleUtils : NSObject

+ (id)bundleForAnalytics;
+ (bool)isRunningFacetime;
+ (bool)isRunningMessagesExtension;

@end
