/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface CFXClipPlayerViewController : JTClipPlayerViewController

- (void)displayCompositionUpdateLoadingView:(id)arg1;

@end
