/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/EmbeddedAcousticRecognition.framework/EmbeddedAcousticRecognition
 */

@interface EARSdapiHelper : NSObject

+ (void)EnsureSDAPIInitialized;

@end
