/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataDetectorsNaturalLanguage.framework/DataDetectorsNaturalLanguage
 */

@interface IPTenseDetector : NSObject

+ (long long)tenseOfString:(id)arg1 languageID:(id)arg2;

@end
