/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface _MPAVRoutingSheetSecureWindow : UIWindow

+ (bool)_isSecure;

- (bool)_canAffectStatusBarAppearance;

@end
