/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface _MPMediaControlsPresentationController : UIPresentationController

- (bool)shouldRemovePresentersView;

@end
