/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPAdvanceRepeatModeCommand : MPRemoteCommand

- (id)newCommandEventWithPreservesRepeatMode:(bool)arg1;

@end
