/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPAlternateTracksContainerViewController : UIViewController

- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;

@end
