/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPEmptyPlaybackQueue : MPRemotePlaybackQueue

+ (bool)supportsSecureCoding;

- (id)description;
- (id)init;

@end
