/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPModelTVShowCreator : MPModelPerson

@property (nonatomic, copy) id /* block */ artworkCatalogBlock;

+ (id)__artworkCatalogBlock_KEY;

- (id)artworkCatalog;

@end
