/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPMRAVOutputContextWrapper : MPCFWrapper

@property (nonatomic, readonly) void*unwrappedValue;

- (id)initWithMRAVOutputContext:(void*)arg1;
- (void*)unwrappedValue;

@end
