/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPMRAVEndpointWrapper : MPCFWrapper

@property (nonatomic, readonly) void*unwrappedValue;

- (id)initWithMRAVEndpoint:(void*)arg1;
- (void*)unwrappedValue;

@end
