/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPPlaceholderArtwork : NSObject

+ (id)noArtPlaceholderImageForMediaType:(unsigned long long)arg1;

@end
