/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPStoreOfferMediaItemArtwork : MPConcreteMediaItemArtwork

- (id)_artworkDescriptor;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
