/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib
 */

@interface Swift._ContiguousArrayStorageBase : Swift._SwiftNativeNSArrayWithContiguousStorage {
    void countAndCapacity;
}

@end
