/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MusicCarDisplayUI.framework/MusicCarDisplayUI
 */

@interface _MCDBrowsableTableView : UITableView

- (bool)canBecomeFirstResponder;

@end
