/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SilexText.framework/SilexText
 */

@interface STTextTangierApplicationDelegate : TSKApplicationDelegate

+ (void)setup;

- (id)createCompatibilityDelegate;

@end
