/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SilexText.framework/SilexText
 */

@interface STTextTangierContainerRep : TSDContainerRep

- (void)dealloc;
- (bool)directlyManagesLayerContent;

@end
