/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WelcomeKitCore.framework/WelcomeKitCore
 */

@interface WLProgressWebService : WLMigrationWebService {
    bool  _doneSent;
}

- (void)updateRemoteUIWithProgress:(double)arg1 completion:(id /* block */)arg2;

@end
