/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface _NTKTemporaryResourceRootDirectory : NSObject

+ (void)initialize;
+ (id)path;

@end
