/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKCFaceDetailSyncedAlbumCell : NTKCFaceDetailDescriptionCell

+ (id)reuseIdentifier;

- (id)init;

@end
