/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKCompanion1stPartyStocksApp : NTKCompanion3rdPartyApp

- (id)complication;
- (id)init;
- (void)install;

@end
