/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKDateRichComplicationBezelCircularView : NTKRichComplicationBezelBaseCircularView

- (id)_circularTemplateFromTemplate:(id)arg1;
- (Class)_circularViewClassFromFromTemplate:(id)arg1;

@end
