/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKDate : CLKDate

+ (id)faceDate;
+ (id)faceDateWithTimeIntervalSinceNow:(double)arg1;

@end
