/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKGradientView : UIView

@property (nonatomic, readonly) CAGradientLayer *gradientLayer;

+ (Class)layerClass;

- (id)gradientLayer;

@end
