/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKPillCollectionNode : NTKCollectionNode

- (void)createSubNodes;

@end
