/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKStopwatchComplication : NTKComplication

- (bool)appearsInDailySnapshotForFamily:(long long)arg1;

@end
