/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKSolarRichComplicationBezelCircularView : NTKRichComplicationBezelBaseCircularView

- (Class)_circularViewClassFromFromTemplate:(id)arg1;

@end
