/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKVictoryAppLauncher : NSObject

+ (void)attemptLaunchWithDelegate:(id)arg1;
+ (id)complication;
+ (id)prelaunchApplicationIdentifiers;

@end
