/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKVictoryAnalogColorEditOption : NTKVictoryColorEditOption

+ (id)_orderedValuesForDevice:(id)arg1;

@end
