/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKWellnessRichComplicationBezelCircularView : NTKRichComplicationBezelBaseCircularView

- (id)_bezelTextProviderFromTemplate:(id)arg1;
- (Class)_circularViewClassFromFromTemplate:(id)arg1;

@end
