/* Generated by EzioChiu
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKEventEditableDetailGroup : EKEventDetailGroup

- (id)itemAtIndex:(unsigned long long)arg1;

@end
