/* Generated by EzioChiu
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKUILocationSearchResultCell : UITableViewCell

- (id)description;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
