/* Generated by EzioChiu
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKUIInviteesViewSomeInviteesCanAttendCell : EKUIInviteesViewTimeSlotCell

- (id)participantsTextColor;
- (id)timeTextColor;

@end
