/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
 */

@interface PCCancelAllProcessWakesOperation : NSOperation

- (void)main;

@end
