/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SAML.framework/SAML
 */

@interface SAMLLogoutResponseElement : SAMLResponseElement

- (bool)assertionMeetsConditions:(id*)arg1;
- (id)assertions;

@end
