/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionClient.framework/AppPredictionClient
 */

@interface ATXDeviceClass : NSObject

+ (bool)isConstrainedForActions;
+ (bool)shouldComputeActions;

@end
