/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DiagnosticExtensionsDaemon.framework/DiagnosticExtensionsDaemon
 */

@interface DEDConstants : NSObject

+ (id)DEDAddEmptyFile;
+ (id)DEDExtensionAttachmentsParamBundleIDKey;
+ (id)DEDExtensionCompressOnAttach;
+ (id)DEDExtensionHostAppKey;
+ (id)allPlatforms;

@end
