/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3AnyCompoundPredicate : ML3CompoundPredicate

+ (bool)supportsSecureCoding;

- (id)compoundOperatorJoiner;

@end
