/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface MLMediaLibraryServiceInterface : NSObject

+ (id)clientInterface;
+ (id)serviceInterface;

@end
