/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface __TVAnimatedImageView : UIImageView

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end
