/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface _TVConfirmationBlurEffect : UIBlurEffect

+ (id)effectWithStyle:(long long)arg1;

- (id)effectSettings;

@end
