/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface _TVDecoratorRequest : NSObject {
    bool  _statusCancelled;
}

@property bool statusCancelled;

- (void)setStatusCancelled:(bool)arg1;
- (bool)statusCancelled;

@end
