/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface _TVLoadingOverlayWindow : UIWindow

- (bool)_canBecomeKeyWindow;
- (bool)_wantsFocusEngine;

@end
