/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface _TVSplitTemplateController : UISplitViewController

- (void)updateWithSplitTemplate:(id)arg1;

@end
