/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface TVJSConfirmationDialog : IKJSObject <TVJSConfirmationDialog>

- (void)presentConfirmation:(id)arg1 :(id)arg2;

@end
