/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit
 */

@interface TVPlaylistElement : TVViewElement

@property (nonatomic, readonly, copy) NSArray *videos;

- (id)videos;

@end
