/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSAppImageDatabaseCacheEntry : SSDatabaseCacheEntry

+ (id)databaseTable;

@end
