/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSHasAccountCondition : SSProtocolCondition

- (bool)evaluateWithContext:(id)arg1;

@end
