/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSLockdown : NSObject

+ (id)sharedInstance;

- (struct __CFString { }*)copyDeviceGUID;

@end
