/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSMetricsCustomEvent : SSMetricsMutableEvent

- (bool)isFieldBlacklistEnabled;

@end
