/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AddressBookLegacy.framework/AddressBookLegacy
 */

@interface ABPhoneFormatting : NSObject

+ (id)abCopyPhoneNumberFromString:(id)arg1;
+ (id)abDefaultCountryCode;
+ (id)abNormalizedPhoneNumberFromString:(id)arg1;

@end
