/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AddressBookLegacy.framework/AddressBookLegacy
 */

@interface ABVCardCardDAVExporter : ABVCardExporter

+ (id)copyVCardRepresentationOfRecord:(void*)arg1 withPhoto:(id)arg2 extraPhotoParameters:(id)arg3;

@end
