/* Generated by EzioChiu
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEAppProxyProviderManager : NETunnelProviderManager

+ (void)loadAllFromPreferencesWithCompletionHandler:(id /* block */)arg1;

- (id)init;

@end
