/* Generated by EzioChiu
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEOnDemandRuleDisconnect : NEOnDemandRule

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
