/* Generated by EzioChiu
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEProfilePayloadContentFilter : NEProfilePayloadBase

- (id)validatePayload;

@end
