/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FMCore.framework/FMCore
 */

@interface FMPastDateComponentsFormatter : NSDateComponentsFormatter

- (id)stringForObjectValue:(id)arg1 withReferenceDate:(id)arg2;

@end
