/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FMCore.framework/FMCore
 */

@interface FMSystemInfo_osx : FMSystemInfo

- (id)deviceClass;
- (id)deviceModelName;
- (id)deviceName;
- (id)deviceUDID;
- (id)osVersion;
- (id)productName;
- (id)productType;

@end
