/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
 */

@interface AVTAvatarContainerViewController : UIViewController

- (void)willMoveToParentViewController:(id)arg1;

@end
