/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
 */

@interface AVTEditingModelBuilder : NSObject

+ (id)buildCoreModelFromPlist;
+ (id)buildCoreModelFromPlistWithLogger:(id)arg1;

@end
