/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
 */

@interface AVTTransparentNavigationController : UINavigationController

- (id)initWithRootViewController:(id)arg1;

@end
