/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitSyncProgressRuntimeTestPaused : IMCloudKitSyncProgressRuntimeTest

- (void)willUpdateSyncState:(id)arg1;

@end
