/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitAccountNeedsRepairSyncProgress : IMCloudKitSyncProgress

- (void)configureSelf;

@end
