/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitHiddenSyncProgress : IMCloudKitSyncProgress

- (id)description;
- (bool)isHidden;

@end
