/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMSendProgressRealTimeDataSource : NSObject <IMSendProgressTimeDataSource>

@property (readonly) double timeIntervalSinceReferenceDate;

- (double)timeIntervalSinceReferenceDate;

@end
