/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VisualVoicemail.framework/VisualVoicemail
 */

@interface VVNotificationInterpreter : NSObject

+ (id)interpretedDictionaryForNotificationUserInfo:(struct __CFDictionary { }*)arg1;

@end
