/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCBaselineFeature : FCPersonalizationFeature

+ (id)baselineFeature;

- (id)fr_description;
- (id)init;

@end
