/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCFDBFeedItem : NSManagedObject

@property (nonatomic, retain) NTPBFeedItem *pbFeedItem;

@end
