/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCFeedTransformationSortByOrder : FCFeedTransformationSort

- (id)transformFeedItems:(id)arg1;

@end
