/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCFeedTransformationSortByGlobalScore : FCFeedTransformationSort

- (id)transformFeedItems:(id)arg1;

@end
