/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCHeadlineFeatureArticleTypeFlint : FCPersonalizationFeature

+ (id)articleTypeFlintFeature;

- (id)fr_description;
- (id)init;

@end
