/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCHeadlineFeatureArticleWithVideoContent : FCPersonalizationFeature

+ (id)articleWithVideoContentFeature;

- (id)fr_description;
- (id)init;

@end
