/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCPersonalizationMappingUtilities : NSObject

+ (id)scoredTagsDictionaryFromScoredTags:(id)arg1;

@end
