/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCPublisherVideoContentFeature : FCPersonalizationFeature

- (id)fr_description;
- (id)init;
- (id)initWithPersonalizationIdentifier:(id)arg1;
- (id)initWithPublisherTagID:(id)arg1;

@end
