/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCRemoveFromReadingListCommand : FCRemoveRecordsCommand

- (id)initWithEntryID:(id)arg1;

@end
