/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCSingleTopicFeedGroupEmitter : FCSingleTagFeedGroupEmitter

- (Class)classForGroupEmittingOperation;
- (id)groupEmitterIdentifier;

@end
