/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCSolUtilities : NSObject

+ (double)randomGaussWithMean:(double)arg1 std:(double)arg2;
+ (id)shuffleArray:(id)arg1;

@end
