/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCTagIDFeature : FCPersonalizationFeature

- (id)fr_description;
- (id)init;
- (id)initWithPersonalizationIdentifier:(id)arg1;
- (id)initWithTagID:(id)arg1;

@end
