/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchListKitUI.framework/WatchListKitUI
 */

@interface _SBIconProgressWaitingLoadingStateTransition : _SBInstallProgressStateTransition

- (void)_updateView:(id)arg1;

@end
