/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKAchievementDescriptionInternal : GKAchievementInternal

+ (id)secureCodedPropertyKeys;

@end
