/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKBulletinServiceInterface : GKServiceInterface

+ (id)interfaceProtocol;

@end
