/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKUnknownPlayerInternal : GKSpecialPlayerInternal

+ (bool)supportsSecureCoding;

- (bool)isUnknownPlayer;
- (id)playerID;

@end
