/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
 */

@interface ClockManager : NSObject

+ (void)loadUserPreferences;
+ (void)saveAndNotifyForUserPreferences:(bool)arg1 localNotifications:(bool)arg2;

@end
