/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
 */

@interface MTUpdateAlarmIntent : INIntent

@property (nonatomic, copy) INObject *alarmID;

@end
