/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileContainerManager.framework/MobileContainerManager
 */

@interface MCMPluginKitPluginContainer : MCMContainer

+ (long long)typeContainerClass;

@end
