/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileContainerManager.framework/MobileContainerManager
 */

@interface MCMSharedSystemDataContainer : MCMContainer

+ (long long)typeContainerClass;

@end
