/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileContainerManager.framework/MobileContainerManager
 */

@interface MCMTempDirDataContainer : MCMDataContainer

+ (long long)typeContainerClass;

@end
