/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSButtonHapticsController : NSObject

+ (id)sharedInstance;

- (void)applyDefinitions:(id)arg1;

@end
