/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSDefaults : NSObject

+ (id)externalDefaults;
+ (id)localDefaults;

@end
