/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSSystemGesturesTouchStreamPolicy : BKSTouchStreamPolicy

- (id)init;

@end
