/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCManagedMediaSummaryCell : MCItemSummaryCell

- (id)_managedBookIconImage;
- (void)setManagedBook:(id)arg1;

@end
