/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCManagedMediaDetailsCell : MCItemDetailsSummaryCell

- (void)setManagedBook:(id)arg1;

@end
