/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCManagedAppSummaryCell : MCItemSummaryCell

- (id)_managedAppIconImage:(id)arg1;
- (void)setManagedApp:(id)arg1;

@end
