/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCMoreDetailsCertificateDetailsController : MCCertificateDetailsController

- (id)specifiers;

@end
