/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@interface HSDatabasesRequest : HSRequest

- (id)canonicalResponseForResponse:(id)arg1;
- (id)init;

@end
