/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface VCActionDonationDefaultsRecommender : NSObject

+ (id)defaultRecommendations;

@end
