/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Categories.framework/Categories
 */

@interface CTLogging : NSObject

+ (id)appHandle;
+ (id)contextKitHandle;
+ (id)domainHandle;

@end
