/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@interface RCDataStoreServerRequestHandlingPolicy : NSXPCStoreServerRequestHandlingPolicy

- (bool)shouldAcceptConnectionsFromClientWithContext:(id)arg1;

@end
