/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@interface RCDebugRecordingController : NSObject

+ (id)sharedInstance;

- (void)promptUserAndCreateDebugRecordingWithSource:(id)arg1;
- (void)startCreatingDebugContentIfRequested;

@end
