/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@interface RCDevice : NSObject

+ (double)audioInputWaveformFlushInterval;
+ (unsigned long long)timeDisplayUpdateFrameInterval;

@end
