/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AXHearingSupport.framework/AXHearingSupport
 */

@interface AXTTYSimulatorSubscriptionContext : CTXPCServiceSubscriptionContext

- (id)uuid;

@end
