/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Cards.framework/Cards
 */

@interface CRMockAsyncCard : CRBasicCard

- (bool)asynchronous;
- (void)loadCardWithCompletion:(id /* block */)arg1;

@end
