/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PencilKit.framework/PencilKit
 */

@interface PKTextAttachmentDrawingViewProvider : NSTextAttachmentViewProvider

+ (void)didInsertDrawingAttachment:(id)arg1;
+ (void)registerViewProviderClassIfNecessary;

- (void)loadView;

@end
