/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSPathProviderFactory : NSObject

+ (id)pathProviderForCurrentContainer;
+ (id)pathProviderForSystemContainerForCurrentProcess;

@end
