/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
 */

@interface BLTPBActionFactory : NSObject

+ (id)bltVersionToFactories;
+ (id)sharedInstance;

- (id)actionWithBBAction:(id)arg1;

@end
