/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
 */

@interface BLTSectionConfigurationCMASItem : BLTSectionConfigurationItem

- (bool)optOutOfCoordination;

@end
