/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MetalTools.framework/MetalTools
 */

@interface MTLDebugCommandQueue : MTLToolsCommandQueue

- (id)commandBuffer;
- (id)commandBufferWithUnretainedReferences;

@end
