/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VisualAlert.framework/VisualAlert
 */

@interface __AXVisualAlertSBUIFlashlightController_super : UIAccessibilitySafeCategory

@end
