/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Messages.framework/Messages
 */

@interface MSStickerBrowserViewLayoutSpecStandard : MSStickerBrowserViewLayoutSpec

- (struct CGSize { double x1; double x2; })itemSize;

@end
