/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface _AFInterstitialConfigurationMutation : NSObject <AFInterstitialConfigurationMutating> {
    AFInterstitialConfiguration * _baseModel;
    long long  _gender;
    NSString * _languageCode;
    struct _mutationFlags { 
        unsigned int isDirty : 1; 
        unsigned int hasStyle : 1; 
        unsigned int hasLanguageCode : 1; 
        unsigned int hasGender : 1; 
    }  _mutationFlags;
    long long  _style;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)generate;
- (id)init;
- (id)initWithBaseModel:(id)arg1;
- (void)setGender:(long long)arg1;
- (void)setLanguageCode:(id)arg1;
- (void)setStyle:(long long)arg1;

@end
