/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFInterstitialProvider : NSObject <AFInvalidating> {
    AFInterstitialConfiguration * _configuration;
    id  _context;
    <AFInterstitialProviderDelegate> * _delegate;
    NSMutableArray * _pendingActions;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_invalidate;
- (void)_performNextAction;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 context:(id)arg2 delegate:(id)arg3;
- (void)invalidate;

@end
