/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFInterstitialConfiguration : NSObject <NSCopying, NSSecureCoding> {
    long long  _gender;
    NSString * _languageCode;
    long long  _style;
}

@property (nonatomic, readonly) long long gender;
@property (nonatomic, readonly, copy) NSString *languageCode;
@property (nonatomic, readonly) long long style;

+ (id)newWithBuilder:(id /* block */)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_descriptionWithIndent:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (long long)gender;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 languageCode:(id)arg2 gender:(long long)arg3;
- (bool)isEqual:(id)arg1;
- (id)languageCode;
- (id)mutatedCopyWithMutator:(id /* block */)arg1;
- (long long)style;

@end
