/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFSiriAcousticIDRequest : NSObject <AFSiriExternalRequest>

- (void)performRequestWithCompletion:(id /* block */)arg1;

@end
