/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManagerUICore.framework/DocumentManagerUICore
 */

@interface DOCDateFormatter : NSObject

+ (id)longDateStringFromDate:(id)arg1;
+ (id)sharedLongDateFormatter;

@end
