/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManagerUICore.framework/DocumentManagerUICore
 */

@interface RecentDocumentsItemQueryDescriptor : DOCItemQueryDescriptor

- (void)augmentQueryContext:(id)arg1;
- (unsigned long long)maxCount;
- (id)queryString;

@end
