/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManagerUICore.framework/DocumentManagerUICore
 */

@interface SharedDocumentsQueryDescriptor : DOCItemQueryDescriptor

- (id)queryString;

@end
