/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManagerUICore.framework/DocumentManagerUICore
 */

@interface TrashedItemsQueryDescriptor : DOCItemQueryDescriptor

- (id)queryString;
- (bool)requiresFastUpdates;

@end
