/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBSUILoginUISceneSpecification : UIApplicationSceneSpecification

- (Class)clientSettingsClass;

@end
