/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STDailyAverageSummaryTableViewCell : UITableViewCell

- (id)initWithUsageReport:(id)arg1;

@end
