/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STFamilyRootViewController : STListViewController {
    NSObject<STRootViewModelCoordinator> * _coordinator;
}

@property (nonatomic, readonly) NSObject<STRootViewModelCoordinator> *coordinator;

- (void).cxx_destruct;
- (id)coordinator;
- (id)init;

@end
