/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STIntroContentPrivacyViewController : STIntroSplashViewController

- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end
