/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STIntroIdentityViewController : STIntroSplashViewController

- (void)viewDidLoad;

@end
