/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STSetupClient : NSObject

+ (void)enableScreenTimeWithCompletionHandler:(id /* block */)arg1;

@end
