/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PLSnapshot.framework/PLSnapshot
 */

@interface PLSnapshotUtilities : NSObject

+ (double)secondsFromMachTime:(unsigned long long)arg1;

@end
