/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKBridgeWatchAttributeController : NSObject

+ (id)_watchAttributeController;
+ (long long)heroWatchSize;
+ (unsigned long long)material;

@end
