/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPaymentSetupBankAppProductCell : PKPaymentSetupProductCell

- (id)init;
- (void)layoutSubviews;

@end
