/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPassGiftCardFrontFaceView : PKPassFrontFaceView

- (id)templateForLayoutMode:(long long)arg1;

@end
