/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKTableViewCellWithValue1Style : PKTableViewCell

- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
