/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INIntentVocabularyKnowledge : _INVocabulary

+ (id)sharedKnowledge;

- (void)removeAllVocabularyFromDevice;

@end
