/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DigitalTouchShared.framework/DigitalTouchShared
 */

@interface ETQuickTapMessage : ETTapMessage

+ (id)doubleTapMessageWithColor:(id)arg1;

- (id)messageTypeAsString;

@end
