/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DigitalTouchShared.framework/DigitalTouchShared
 */

@interface ETReadReceiptMessage : ETMessage

+ (unsigned short)messageType;

@end
