/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@interface ISPasswordSettingsUtility : NSObject

+ (bool)serverPasswordSettingsEnabled:(id)arg1;

@end
