/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

@interface RUISetupAssistantModalStyle : RUISetupAssistantStyle

- (void)applyToObjectModel:(id)arg1;

@end
