/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCFinderBookmarkItem : BRCDocumentItem

- (id)asFinderBookmark;
- (id)baseContentsRecord;
- (id)contentsRecordID;
- (bool)isFinderBookmark;

@end
