/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICalendarStore : NSObject

+ (id)eventControllerFromResult:(id)arg1;
+ (id)sharedCalendarStore;

@end
