/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIPrivacyDetailsViewController : UINavigationController

- (void)dismiss;
- (id)init;

@end
