/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIMediaPlayerViewController : AVPlayerViewController

- (id)initWithDestination:(id)arg1;
- (void)viewDidAppear:(bool)arg1;

@end
