/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUINowPlayingLabelContainer : TLKStackView

- (id)initWithMovie:(id)arg1 style:(unsigned long long)arg2;

@end
