/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PlatterKit.framework/PlatterKit
 */

@interface PLPlatterHeaderViewDateLabelFactory : BSUIDateLabelFactory

+ (id)sharedInstance;

@end
