/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleBasebandManager.framework/AppleBasebandManager
 */

@interface ABMDiagnosticExtensionLogging : NSObject

+ (struct os_log_s { }*)getOSLogHandler;

@end
