/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
 */

@interface NRMagicSwitchHelper : NSObject

+ (void)clearCompanionSeed;
+ (id)companionSeed;

@end
