/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
 */

@interface NRMockRegistryClient : NRRegistryClient

+ (Class)xpcConnectionClass;

- (id)init;

@end
