/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
 */

@interface WBSAllowedPasswordRule : WBSPasswordRule

+ (id)allowedRuleWithCharacterClasses:(id)arg1;

@end
