/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
 */

@interface WBSMaxConsecutivePasswordRule : WBSPasswordRule

+ (id)maxConsecutiveRuleWithValue:(id)arg1;

@end
