/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebDarkSystemBackdropLayer : WebSystemBackdropLayer

- (id)init;
- (void)setBackgroundColor:(struct CGColor { }*)arg1;

@end
