/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebDatabaseTransactionBackgroundTaskController : NSObject

+ (void)endBackgroundTask;
+ (void)startBackgroundTask;

@end
