/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GKConstraintLeadingInfo : NSObject {
    NSString * _fontTextStyle;
    double  _leading;
}

@property (nonatomic, retain) NSString *fontTextStyle;
@property (nonatomic) double leading;

- (void)dealloc;
- (id)fontTextStyle;
- (double)leading;
- (void)setFontTextStyle:(id)arg1;
- (void)setLeading:(double)arg1;

@end
