/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GKFocusableDarkColorPalette : GKInGameColorPalette

- (id)emphasizedTextColor;
- (id)standardTextColor;
- (long long)windowBackgroundBlurStyle;

@end
