/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GKInGameColorPalette : GKColorPalette

- (id)floatingHeaderViewBackgroundColor;
- (id)monogramBackgroundColor;
- (id)textOnDarkBackgroundColor;
- (id)viewBackgroundColor;
- (id)windowBackgroundColor;

@end
