/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKTwoFingerPanGestureRecognizer : MKTiltGestureRecognizer

- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end
