/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MapsSupport.framework/MapsSupport
 */

@interface _MSPCloudKitAccountAccessFixZonesAndSubscriptionsTask : MSPCloudRepeatableTask

@end
