/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

@interface VSFormatArgument : NSObject {
    NSDictionary * attributes;
    NSString * formatSpecifier;
    NSString * formattedArg;
}

- (void)dealloc;

@end
