/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosFormats.framework/PhotosFormats
 */

@interface PFVideoEncoding : NSObject

+ (bool)deviceSupportsHardwareHEVCEncoding;

@end
