/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKTravelAdvisoryUtilities : NSObject

+ (bool)doesHypothesisSatisfyMinimumAllowableTravelTime:(id)arg1;

@end
