/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKSplashScreenStrings : NSObject

+ (id)configurationText;
+ (id)continueButtonText;
+ (id)suggestedEventsFeatureText;
+ (id)suggestedEventsTitleText;
+ (id)suggestedLocationsFeatureText;
+ (id)suggestedLocationsTitleText;
+ (id)timeToLeaveAndAutomaticGeocodingFeatureText;
+ (id)timeToLeaveAndAutomaticGeocodingTitleText;
+ (id)title;

@end
