/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNLeechedLocationProvider : MNCoreLocationProvider

- (id)init;
- (void)setDesiredAccuracy:(double)arg1;

@end
