/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNNavigationStateGuidanceStepping : MNNavigationStateGuidance

- (unsigned long long)desiredResourcePolicy;
- (unsigned long long)type;

@end
