/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNNotificationManager : NSObject

- (void)showPredictedRouteTrafficIncidentBulletinForCommuteDetails:(id)arg1;

@end
