/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface BHBehaviorsBundle : NSObject

- (void)applicationDidFinishLaunching;
- (id)init;

@end
