/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface DoneDrawingObserver : NSObject

+ (id)sharedDoneDrawingObserver;

- (void)doneDrawing:(id)arg1;

@end
