/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface PAEFracturedTransition_Radial : PAEFracturedTransition

- (id)initWithAPIManager:(id)arg1;

@end
