/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface PAETransfer : PAEPhotosFilters

- (bool)addParameters;
- (id)initWithAPIManager:(id)arg1;

@end
