/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProVideo.framework/ProVideo
 */

@interface PVVideoCompositingExporter : PVVideoCompositing

- (id)init;
- (id)requiredPixelBufferAttributesForRenderContext;
- (void)setupEffectScheduler;
- (void)setupTextureFactories;

@end
