/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKPaymentProvisioningFlowStepContext : NSObject

- (id)manualEntryStepContext;
- (id)provisioningProgressStepContext;
- (id)provisioningResultStepContext;
- (id)remoteCredentialsStepContext;
- (id)termsAndConditionsStepContext;
- (id)welcomeStepContext;

@end
