/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKPaymentProvisioningFlowControllerIssuerVerificationStepContext : NPKPaymentProvisioningFlowStepContext

@end
