/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
 */

@interface FAClearFamilyCircleCacheRequest : FAFamilyCircleRequest

- (void)startRequestWithCompletionHandler:(id /* block */)arg1;

@end
