/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PIApertureRedEyeFilter : CIFilter {
    CIImage * inputImage;
    NSArray * inputSpots;
}

- (void).cxx_destruct;
- (id)outputImage;

@end
