/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PIAutoLoopExportClient : NURenderClient

- (void)setCompletionBlock:(id /* block */)arg1;
- (void)submitRequest:(id)arg1;

@end
