/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PIDepthEffectApertureAutoCalculator : NUAutoCalculator

- (void)calculate:(id /* block */)arg1;

@end
