/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PILevelsLuminanceAutoCalculator : PILevelsAutoAbstractCalculator

- (id)calculateSettingsForImageHistogram:(id)arg1;

@end
