/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PILevelsAutoAbstractCalculator : NUAutoCalculator

- (void)calculate:(id /* block */)arg1;
- (id)calculateSettingsForImageHistogram:(id)arg1;
- (id)calculateSettingsForSingleChannelHistogram:(id)arg1 suffix:(id)arg2;

@end
