/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PILongExposureFusionAutoCalculator : NUAutoCalculator

- (void)_computeCleanAperture:(id /* block */)arg1;
- (void)calculate:(id /* block */)arg1;

@end
