/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PISmartBlackAndWhiteAutoCalculator : NUAutoCalculator

- (id)_calculateBlackAndWhiteSettingsFromBufferImage:(id)arg1;
- (void)calculate:(id /* block */)arg1;

@end
