/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHBLineType : NSObject

+ (void)readWithState:(id)arg1 chartType:(id)arg2;

@end
