/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDLineType : CHDChartTypeWithGrouping

- (int)defaultLabelPosition;
- (id)initWithChart:(id)arg1;

@end
