/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDScatterType : CHDChartType

- (int)defaultLabelPosition;
- (bool)isSmoothType;

@end
