/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDScatterSeries : CHDLineSeries

- (id)categoryData;
- (void)setCategoryData:(id)arg1;

@end
