/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHPScatterWithStringValueX : EDProcessor

- (void)applyProcessorToObject:(id)arg1 sheet:(id)arg2;
- (bool)isObjectSupported:(id)arg1;

@end
