/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHXDrawingState : OAXDrawingState {
    CHXReadState * mCHXState;
}

- (id)chxState;
- (id)initWithCHXState:(id)arg1;

@end
