/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EBOfficeArtReaderState : OABReaderState {
    EBReaderState * mReaderState;
    EXReadState * mXmlDocumentState;
}

- (void)dealloc;
- (id)initWithReaderState:(id)arg1;
- (id)readerState;
- (id)xmlDrawingState;

@end
