/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDCollectionWithPointerEquality : EDCollection

- (bool)isEqualToCollection:(id)arg1;

@end
