/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDFontsCollection : EDCollection

- (unsigned long long)indexOfObjectWithFontName:(id)arg1 color:(id)arg2;

@end
