/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EXOfficeArtState : OAXDrawingState {
    EXReadState * mExcelState;
}

- (id)excelState;
- (id)initWithExcelState:(id)arg1;

@end
