/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADBulletFontFollowText : OADBulletFont

- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
