/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADFlattenedGroup : OADDrawable {
    NSMutableArray * mDrawables;
}

- (void)addDrawable:(id)arg1;
- (void)dealloc;
- (id)drawables;
- (id)init;

@end
