/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADGrayscaleEffect : OADBlipEffect

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
