/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADLineJoin : OADProperties <NSCopying>

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
