/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OAXBlipContext : OCXDelayedMediaContext

- (id)description;
- (bool)loadDelayedNode:(id)arg1;

@end
