/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OAXMovieContext : OCXDelayedMediaContext

- (id)dataRep;
- (bool)loadDelayedNode:(id)arg1;

@end
