/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface ODDIteratorSpecification : NSObject {
    NSMutableArray * mAttributesList;
}

- (void)addAttributes:(id)arg1;
- (id)attributesList;
- (void)dealloc;
- (id)init;

@end
