/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface ODDLayoutObjectList : ODDLayoutObject {
    NSMutableArray * mChildren;
}

- (void)addChild:(id)arg1;
- (id)children;
- (void)dealloc;
- (id)init;

@end
