/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OITSUPositiveZeroNumberFormatter : NSNumberFormatter

- (id)stringForObjectValue:(id)arg1;

@end
