/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OITSUPointerKeyDictionary : OITSUNoCopyDictionary

- (id)initWithCapacity:(unsigned long long)arg1;

@end
