/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OITSUMutableShallowCopyPair : OITSUShallowCopyPair

- (void)setFirst:(id)arg1;
- (void)setSecond:(id)arg1;

@end
