/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface PDCornerDirectionOptions : PDTransitionOptions {
    int  mDirection;
}

- (int)direction;
- (void)setDirection:(int)arg1;

@end
