/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface PDVideoNode : PDMediaNode {
    bool  mIsFullScreen;
}

- (bool)isFullScreen;
- (void)setIsFullScreen:(bool)arg1;

@end
