/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface TCDumpSettings : NSObject

+ (bool)isDumpForQA;
+ (void)setDumpForQA:(bool)arg1;

@end
