/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface TCExportTracing : TCTracing

- (void)dealloc;
- (id)initWithFilename:(id)arg1;
- (void)startExporting;
- (void)startWriting;
- (void)stopExporting;
- (void)stopWriting;

@end
