/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface WBRevisionAuthorTable : NSObject

+ (void)readFrom:(id)arg1 revisionAuthorTable:(id)arg2;

@end
