/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreIndoor.framework/CoreIndoor
 */

@interface CLLocationContextUtil : NSObject

+ (bool)isIndoor:(long long)arg1;
+ (bool)isRegional:(long long)arg1;

@end
