/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
 */

@interface MPUActionCellConfiguration : MPUCellConfiguration

+ (void)performActionForCell:(id)arg1 withViewController:(id)arg2;

@end
