/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AccountNotification.framework/AccountNotification
 */

@interface ANDaemonInterface : NSObject

+ (id)XPCInterface;
+ (id)_buildXPCInterface;

@end
