/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNAvatarCardActionsTableView : UITableView

- (struct CGSize { double x1; double x2; })intrinsicContentSize;

@end
