/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNContactShareContactAction : CNContactAction

- (bool)canPerformAction;
- (void)performActionWithSender:(id)arg1;

@end
