/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNContactCreateReminderAction : CNContactAction

- (void)performActionWithSender:(id)arg1;
- (id)title;

@end
