/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNMapsTabletStyleProvider : CNTabletStyleProvider

- (id)cardActionConferenceIcon;
- (id)cardLabelTextColor;
- (id)personActionColor;

@end
