/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPhoneStyleProvider : CNStyleProvider

- (bool)cardActionsAllowFaceTimeFavorites;
- (bool)cardActionsAllowVoiceFavorites;

@end
