/* Generated by EzioChiu
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPropertyGroupBirthdayItem : CNPropertyGroupDateItem

+ (id)emptyValueForLabel:(id)arg1;

- (id)displayLabel;
- (void)updateLabeledValueWithLabel:(id)arg1;

@end
