/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
 */

@interface CoreSpotlightUtils : NSObject

+ (bool)detailedLoggingEnabled;
+ (bool)disabledUserActivities;
+ (bool)fastUserActivites;
+ (bool)forceDataMigration;
+ (void)initialize;

@end
