/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserFS.framework/UserFS
 */

@interface UserFSFile : UserFSItem

- (bool)isDirectory;
- (id)openStreamWithOptions:(unsigned int)arg1 error:(id*)arg2;

@end
