/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMPhotoKitDeclineActionPerformer : PXCMMPhotoKitDeleteActionPerformer

- (void)performUserInteractionTask;

@end
