/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMPublishToSharedStreamActionPerformer : PXCMMPublishActionPerformer

- (void)performBackgroundTask;

@end
