/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMInvitationsDataSourceManager : PXSectionedDataSourceManager

@property (nonatomic, readonly) PXCMMInvitationsDataSource *dataSource;

@end
