/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMAssetSelectionActionPerformer : PXCMMAssetActionPerformer

- (void)performUserInteractionTask;

@end
