/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMFileBackedActionManager : PXCMMActionManager

@property (nonatomic) <PXCMMFileBackedActionPerformerDelegate> *performerDelegate;

- (id)init;

@end
