/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMPhotoKitForceSyncMomentShareActionPerformer : PXCMMActionPerformer

- (bool)canPerformActionWithSession:(id)arg1;
- (void)performBackgroundTask;

@end
