/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCMMPeopleSuggestionsDataSourceManager : PXSectionedDataSourceManager

@property (nonatomic, readonly) PXCMMPeopleSuggestionsDataSource *dataSource;

- (void)boostLoading;
- (void)cancelLoading;
- (bool)isLoading;
- (void)startLoading;

@end
