/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCollectionsDataSource : PXSectionedDataSource

- (id)collectionAtIndexPath:(id)arg1;
- (id)collectionListForSection:(long long)arg1;
- (long long)countForCollection:(id)arg1;
- (id)indexPathForCollection:(id)arg1;

@end
