/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCollectionsDataSourceChangeDetails : PXSectionedDataSourceChangeDetails {
    bool  _countUpdateChange;
}

@property (getter=isCountUpdateChange, nonatomic) bool countUpdateChange;

- (bool)isCountUpdateChange;
- (void)setCountUpdateChange:(bool)arg1;

@end
