/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXDemoViewWidgetUIViewController : UIViewController

- (id)init;
- (void)viewDidLoad;

@end
