/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXLocalization : NSObject

+ (id)currentDeviceCanonicalModel;
+ (id)messageForEmptyPhotoLibrary;
+ (id)openCameraButtonTitleForEmptyPhotoLibrary;
+ (id)titleForEmptyPhotoLibrary;

@end
