/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXMemoriesBlacklistPlaceAreaAccesoryViewSpec : PXMemoriesBlacklistAccessoryViewSpec

+ (id)spec;

- (id)init;

@end
