/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXMemoriesDataSourceManager : PXSectionedDataSourceManager

@property (nonatomic, readonly) PXMemoriesDataSource *dataSource;

@end
