/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXMemoriesTVViewController : UIViewController {
    PXMemoriesDataSourceManager * _dataSourceManager;
    PXMemoriesUIViewController * _memoriesController;
}

- (void).cxx_destruct;
- (id)initWithDataSourceManager:(id)arg1;
- (void)viewDidLoad;

@end
