/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPhotoKitSelectAutoloopVariationAssetActionPerformer : PXPhotoKitSelectVariationAssetActionPerformer

+ (id)editOperationType;

@end
