/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXRelatedSpecManager : PXFeatureSpecManager

@property (nonatomic, readonly) PXRelatedSpec *spec;

- (Class)specClass;

@end
