/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXSampleAlbumInvitationModel : PXSampleInboxModel

- (id)init;
- (id)leftPreviewItems;

@end
