/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXStaticAssetsDataSourceManager : PXAssetsDataSourceManager

- (id)initWithDataSource:(id)arg1;

@end
