/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXTapToRadarGadgetProvider : PXGadgetProvider

- (unsigned long long)estimatedNumberOfGadgets;
- (void)generateGadgets;

@end
