/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXTestBubbleViewController : PXTranscriptBubbleViewController

- (void)viewDidLoad;

@end
