/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXUITilingControllerZoomAnimationCoordinator : PXTilingControllerZoomAnimationCoordinator

- (void)moveTile:(id)arg1 toView:(id)arg2 restorationBlock:(out id /* block */*)arg3;

@end
