/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXUITapGestureRecognizer : UITapGestureRecognizer

- (struct CGPoint { double x1; double x2; })locationInView:(id)arg1;

@end
