/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface TestPLCloudSharedComment : PLCloudSharedComment

- (id)commentText;
- (id)commenterEmail;
- (id)commenterFirstName;
- (id)commenterFullName;
- (id)commenterLastName;
- (id)isMyComment;

@end
