/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface _AXMSettingObserver : NSObject {
    id /* block */  callback;
    id  observer;
}

- (void).cxx_destruct;

@end
