/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface AXMEmailAddressSpeechFormatter : AXMSpeechFormatter

- (id)speechStringForObjectValue:(id)arg1;

@end
