/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface AXMTagger : NSObject {
    void * _tagger;
}

- (void)dealloc;
- (void)enumerateText:(id)arg1 locale:(id)arg2 block:(id /* block */)arg3;
- (id)init;

@end
