/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLIOAccelFragmentRenderCommandEncoder : MTLIOAccelCommandEncoder

- (unsigned long long)getType;

@end
