/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

@interface YQLConstants : NSObject

+ (id)YQLDataSourceToStocksKeyMap;
+ (id)YQLExchangeToStocksKeyMap;
+ (id)YQLQuoteToStocksKeyMap;

@end
