/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@interface CPGraphicMaker : NSObject

+ (void)combineShapesIn:(id)arg1;
+ (void)makeCombinedShapesIn:(id)arg1;

@end
