/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AttentionAwareness.framework/AttentionAwareness
 */

@interface AWClientPreferences : NSObject

+ (void)initialize;
+ (void)initializePreferences;

@end
