/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideosExtras.framework/VideosExtras
 */

@interface VideosExtrasActivityIndicatorElementViewController : VideosExtrasViewElementViewController {
    VideosExtrasActivityIndicator * _activityView;
}

- (void).cxx_destruct;
- (void)_prepareLayout;
- (bool)matchParentHeight;
- (void)viewDidLoad;

@end
