/* Generated by EzioChiu
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNExportOperation : NSOperation

- (bool)canceled;
- (id)error;
- (double)progress;
- (bool)succeded;

@end
