/* Generated by EzioChiu
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNMutableGeometrySource : SCNGeometrySource

@property (nonatomic, readonly) NSMutableData *mutableData;

- (id)mutableData;

@end
