/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface __UIKeyboardCanvas : __UIScreenCanvas

+ (id)_keyboardCanvasForScreen:(id)arg1;
+ (bool)alwaysKeepContexts;

- (void)detachWindow:(id)arg1;

@end
