/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface __UIAtomTextViewBaselineLayoutStrut : UILabel

- (struct CGSize { double x1; double x2; })intrinsicContentSize;

@end
