/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIActivityAlertVisualStylingAlertSheet : UIAlertControllerVisualStyleActionSheet

- (Class)interfaceActionVisualStyleClassForManagingConcreteVisualStyle;

@end
