/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIActivityInterfaceActionGroupVisualStylingAlertSheet : UIInterfaceActionVisualStyle

- (struct CGSize { double x1; double x2; })minimumActionContentSize;

@end
