/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIAlertControllerActionSheetRegularPresentationController : UIPopoverPresentationController

- (id)_alertController;
- (id)_alertControllerContainer;
- (id)_compactPresentationController;
- (id)_exceptionStringForNilSourceViewOrBarButtonItem;
- (id)_presentationControllerForTraitCollection:(id)arg1;
- (void)dimmingViewWasTapped:(id)arg1;

@end
