/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIBackdropViewSettingsATVSemiLight : _UIBackdropViewSettings

- (void)setDefaultValues;

@end
