/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIBackdropViewSettingsFlatSemiLight : _UIBackdropViewSettingsLight

- (void)setDefaultValues;

@end
