/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIButtonFeedbackGeneratorConfiguration : _UIFeedbackGeneratorUserInteractionDrivenConfiguration

+ (id)defaultConfiguration;
+ (id)destructiveConfiguration;

- (long long)requiredSupportLevel;

@end
