/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIBackdropViewSettingsDarkWithZoom : _UIBackdropViewSettingsDark

- (void)setDefaultValues;

@end
