/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIBackdropViewSettingsUltraDarkWithZoom : _UIBackdropViewSettingsUltraDark

- (void)setDefaultValues;

@end
