/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICompatibilityTextViewPrintFormatter : UIWebDocumentViewPrintFormatter

- (id)_webDocumentView;

@end
