/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIDropInteractionWeakWrapper : NSObject {
    UIDropInteraction * _dropInteraction;
}

@property (nonatomic, readonly) UIDropInteraction *dropInteraction;

- (void).cxx_destruct;
- (id)dropInteraction;
- (id)initWithDropInteraction:(id)arg1;

@end
