/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIDocumentPickerRemoteViewControllerTintColorView : UIView

- (void)tintColorDidChange;

@end
