/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIEditableTextSelectionTwoFingerPanGesture : _UIPanOrFlickGestureRecognizer

- (id)init;
- (id)initWithTextInput:(id)arg1;

@end
