/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFeedbackEventBehaviorConfiguration : _UINotificationFeedbackGeneratorConfiguration

@end
