/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFocusFastScrollingDataAggregator : NSObject

+ (void)scrollingBeganWithStyle:(long long)arg1;
+ (void)scrollingEnded;

@end
