/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFeedbackKeyboardBehaviorConfiguration : _UIKeyboardFeedbackGeneratorConfiguration

@end
