/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIKeyboardChangedInformationWithFencing : _UIKeyboardChangedInformation

+ (id)animationFence;

@end
