/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIOverCurrentContextPresentationController : _UICurrentContextPresentationController

- (bool)_shouldPresentedViewControllerControlStatusBarAppearance;
- (long long)presentationStyle;
- (bool)shouldRemovePresentersView;

@end
