/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIPanelControllerMeshAnimatingTransitionView : UIView

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)initWithView:(id)arg1;

@end
