/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIPreviewInteractionTouchObservingGestureRecognizer : _UITouchesObservingGestureRecognizer

@end
