/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIReflectingGradientView : UIView

+ (Class)layerClass;

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end
