/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIScrollViewIndexBarIndicator : UIView

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end
