/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarIndicatorRotationLockItem : _UIStatusBarIndicatorItem

- (id)imageNameForUpdate:(id)arg1;
- (id)indicatorEntryKey;
- (bool)isTemplateImage;

@end
