/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIScrollViewAutomaticContentSizeConstraint : NSAutoresizingMaskLayoutConstraint

- (id)description;

@end
