/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarVisualProvider_Split65_Zoomed : _UIStatusBarVisualProvider_Split58

+ (double)baselineBottomInset;
+ (double)leadingCenteringEdgeInset;
+ (double)referenceScale;

@end
