/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarSecondaryCellularExpandedItem : _UIStatusBarCellularExpandedItem

- (id)cellularDataEntryKey;

@end
