/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarVisualProvider_Pad_ForcedCellular : _UIStatusBarVisualProvider_Pad

+ (bool)hasCellularCapability;

@end
