/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UISegmentedControlDividerImage : UIImage

+ (bool)supportsSecureCoding;

- (bool)_suppressesAccessibilityHairlineThickening;

@end
