/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarRegionFillingLayout : _UIStatusBarRegionLinearLayout

- (id)_horizontalConstraintsForLayoutItems:(id)arg1 layoutGuides:(id)arg2;

@end
