/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarActivityItem_SyncOnly : _UIStatusBarActivityItem

- (bool)_enableForType:(long long)arg1;

@end
