/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarRoundedCornerView : _UIStatusBarPersistentAnimationView

- (void)layoutSubviews;

@end
