/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarDisplayItemPlacementExpandedIndicatorsGroup : _UIStatusBarDisplayItemPlacementIndicatorsGroup

+ (id)activityItemDisplayIdentifier;

@end
