/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UISearchControllerInPlaceSearchBarAnimator : _UISearchControllerAnimator

- (void)animateTransition:(id)arg1;

@end
