/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UITableViewCellRemoveControl : UIRemoveControl {
    float  _verticalOffset;
}

- (float)_verticalOffsetFromTarget;
- (id)initWithTarget:(id)arg1;

@end
