/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIViewServiceReplyAwaitingTrampoline : _UIViewServiceReplyControlTrampoline

- (void)forwardInvocation:(id)arg1;

@end
