/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIWebVideoUploadItem : _UIWebFileUploadItem

- (id)displayImage;
- (bool)isVideo;

@end
