/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIWebHighlightLongPressGestureRecognizer : UILongPressGestureRecognizer

- (void)cancel;

@end
