/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIAccessibilityCustomViewHUDLayoutManager : UIAccessibilityHUDLayoutManager

- (void)layoutSubviewsOfHUD:(id)arg1;

@end
