/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UICABackdropLayer : CABackdropLayer

- (void)setValue:(id)arg1 forKeyPath:(id)arg2;

@end
