/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIDebuggingInformationRootTableViewController : UIDebuggingInformationListTableViewController

- (id)initWithStyle:(long long)arg1;

@end
