/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIInterfaceActionConcreteVisualStyle_CarPlayAlert : UIInterfaceActionConcreteVisualStyle_CarPlay

@end
