/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIInterfaceActionConcreteVisualStyle_iOSActivitySheet : UIInterfaceActionConcreteVisualStyle_iOSSheet

@end
