/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIInputViewSetPlacement_DragToDismissApplicator : UIInputViewSetPlacement_GenericApplicator

- (void)checkVerticalConstraint;

@end
