/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIInterfaceActionConcreteVisualStyleAlert_AppleTVAlert : UIInterfaceActionConcreteVisualStyle_AppleTV

@end
