/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardHiddenViewController_ExternalCredential : UIKeyboardHiddenViewController

- (void)setAutofillVC:(id)arg1;

@end
