/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardCandidateInlineFloatingToggleButton : UIKeyboardCandidateToggleButton

+ (id)arrowImageName;

@end
