/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrinterPickerControllerInternals : NSObject {
    UIPrinterPickerViewController * _printerPickerViewController;
    bool  _supressNotifyDismissed;
}

- (void).cxx_destruct;

@end
