/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIPrintPanelNavigationController : UINavigationController

- (void)__viewWillLayoutSubviews;

@end
