/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarCarPlayItemView : UIStatusBarIndicatorItemView

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (id)accessibilityHUDRepresentation;

@end
