/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarActionableLockScreenStyleAttributes : UIStatusBarLockScreenStyleAttributes

- (bool)shouldProduceReturnEvent;

@end
