/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStoryboardViewControllerPlaceholder : NSObject

- (id)initWithCoder:(id)arg1;

@end
