/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarLiquidDetectionItemView : UIStatusBarItemView

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (id)accessibilityHUDRepresentation;
- (id)contentsImage;

@end
