/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UISUIAirdropSecurityScopedResource : UISUISecurityScopedResource

+ (id)readonlySandboxExtensionClassString;
+ (bool)supportsSecureCoding;

@end
