/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITextMagnifierRangedRenderer : UITextMagnifierCommonRenderer

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (id)visualsForMagnifier;

@end
