/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITextDragDropSupport : NSObject

+ (id)installTextDragDropOnView:(id)arg1;
+ (id)installTextDragOnView:(id)arg1;

@end
