/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITextEffectsWindowNoAbove : UITextEffectsWindow

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (id)aboveStatusBar;

@end
