/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITextCheckerDictionaryEntry : NSObject {
    NSData * data;
    struct __CFSet { } * dictionary;
    long long  size;
}

- (void)dealloc;

@end
