/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITextGestureClusterKeyboardTextSelectionForTextField : UITextGestureCluster

- (id)initWithView:(id)arg1;

@end
