/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIUnhandledMenuButtonAction : BSAction

- (long long)UIActionType;
- (id)init;

@end
