/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIViewProgressAnimatableProperty : UIViewFloatAnimatableProperty

+ (id)progressAnimatablePropertyByPerforming:(id /* block */)arg1;
+ (id)propertyAnimatorByPerforming:(id /* block */)arg1;

@end
