/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface WebPDFNSNumberFormatter : NSNumberFormatter

+ (id)copyNumberFormater;

- (void)dealloc;

@end
