/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreRoutine.framework/CoreRoutine
 */

@interface RTScenarioTriggerDisconnectedFromCar : RTScenarioTrigger

- (id)description;
- (id)init;

@end
