/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreRoutine.framework/CoreRoutine
 */

@interface RTSourceMapsSupportHistoryEntryPlaceDisplay : RTSourceMapsSupportHistoryEntry

@end
