/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchListKit.framework/WatchListKit
 */

@interface WLKContinueWatchingRequestOperation : WLKNetworkRequestOperation

- (id)init;
- (id)responseProcessor;

@end
