/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchListKit.framework/WatchListKit
 */

@interface WLKCanonicalContainerRequestOperation : WLKCanonicalPlayablesRequestOperation

- (id)responseProcessor;

@end
