/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WatchListKit.framework/WatchListKit
 */

@interface WLKFavoritesRequest : WLKRequest

- (void)makeRequestWithCompletion:(id /* block */)arg1;

@end
