/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FamilyCircleUI.framework/FamilyCircleUI
 */

@interface _FASharedServiceImage : UIImage

- (struct CGSize { double x1; double x2; })size;

@end
