/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FamilyCircleUI.framework/FamilyCircleUI
 */

@interface FAFamilyPaymentInfoRequest : AAFamilyRequest

+ (Class)responseClass;

- (id)urlString;

@end
