/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FamilyCircleUI.framework/FamilyCircleUI
 */

@interface FASharedServicesSpecifierCell : PSTableCell {
    NSLayoutConstraint * _widthConstraint;
}

- (void).cxx_destruct;
- (id)blankIcon;
- (id)getLazyIcon;
- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
