/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAssetBase : CEMDeclarationBase

+ (id)declarationClass;

@end
