/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FlightUtilities.framework/FlightUtilities
 */

@interface FUStyleProviderLight : FUStyleProviderVibrantLight

- (id)lightTextColor;
- (id)separatorColor;

@end
