/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Engram.framework/Engram
 */

@interface ENKeyClassRegister : NSObject

+ (id)_queue;
+ (void)registerKeyClass:(Class)arg1;
+ (id)registeredKeyClasses;

@end
