/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleServiceToolkit.framework/AppleServiceToolkit
 */

@interface ASTConnectionSession : ASTMaterializedConnection

- (id)initWithIdentities:(id)arg1 ticket:(id)arg2;

@end
