/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleServiceToolkit.framework/AppleServiceToolkit
 */

@interface ASTConnectionAuthInfo : ASTMaterializedConnection

- (id)endpoint;
- (id)initWithAuthInfo:(id)arg1;

@end
