/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleServiceToolkit.framework/AppleServiceToolkit
 */

@interface ASTLocalization : NSObject

+ (id)localizedStringForKey:(id)arg1;
+ (void)prepareLocalizedStringsWithCompletionHandler:(id /* block */)arg1;

@end
