/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
 */

@interface CMKFocusPointView : CMKFocusView

- (double)dimAfterInteractionDelay;
- (id)nameForDarkImage;
- (id)nameForLightImage;

@end
