/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
 */

@interface _CNSortingResponsePreparer : _CNAutocompleteResponsePreparerDecorator

- (id)prepareResults:(id)arg1;

@end
