/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
 */

@interface CNAutocompleteProbeProviderFactory : NSObject

+ (id)defaultProbeProvider;

@end
