/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
 */

@interface CNAutocompleteSearchProviderFactory : NSObject

+ (id)cachingProvider;
+ (id)nonCachingProvider;

@end
