/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
 */

@interface CNAutocompleteDuetContactResult : CNAutocompleteResult

+ (unsigned long long)category;

@end
