/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleCVAPhoto.framework/AppleCVAPhoto
 */

@interface ImageSaverAndFileConfigRegistrator : ImageSaverRegistrator

- (void)dealloc;
- (id)init;

@end
