/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAssetManagerEnablePolicy : CSPolicy

- (void)_addAssetManagerEnabledConditions;
- (void)_subscribeEventMonitors;
- (id)init;

@end
