/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAssetManagerEnablePolicyFactory : NSObject

+ (id)assetManagerEnabledPolicy;

@end
