/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAssetManagerEnablePolicyMac : CSPolicy

- (void)_addAssetManagerEnabledConditions;
- (id)init;

@end
