/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSVoiceTriggerEnabledPolicyNonAOP : CSPolicy

- (void)_addVoiceTriggerEnabledConditions;
- (void)_subscribeEventMonitors;
- (id)init;

@end
