/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSVoiceTriggerEnabledPolicyFactory : NSObject

+ (id)voiceTriggerEnabledPolicy;

@end
