/* Generated by EzioChiu
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSStoreAllAppsResponseValueTransformer : VSCompoundValueTransformer

- (id)init;

@end
