/* Generated by EzioChiu
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSViewServiceXPCInterface : NSObject

+ (id)viewServiceHostInterface;
+ (id)viewServiceInterface;

@end
