/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBApplicationDataStoreInProcessRepositoryClientInvalidationSentinel : NSObject

+ (id)sentinel;

@end
