/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBSystemAppSceneSpecification : UIApplicationSceneSpecification

- (Class)clientAgentClass;
- (Class)hostAgentClass;

@end
