/* Generated by EzioChiu
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface _GCMFiDigitalExtendedGamepadControllerProfile : _GCMFiExtendedGamepadControllerProfile <_GCACHomeButtonDelegate>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)initWithCoder:(id)arg1;
- (id)initWithController:(id)arg1;

@end
