/* Generated by EzioChiu
   Image: /System/Library/Frameworks/StoreKit.framework/StoreKit
 */

@interface SKCloudServiceSetupExtension : NSObject

+ (id)clientInterface;
+ (id)serviceInterface;

@end
