/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AMPCoreUI.framework/AMPCoreUI
 */

@interface AMPPrivacyViewController : UIAlertController

+ (id)privacyControllerWithIdentifier:(id)arg1 acknowledgementHandler:(id /* block */)arg2;

@end
