/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AMPCoreUI.framework/AMPCoreUI
 */

@interface AMPTintedBackgroundButton : UIButton

- (void)setHighlighted:(bool)arg1;
- (void)tintColorDidChange;
- (void)updateBackgroundColor;

@end
