/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPCNNPoolingBlockVector : VCPCNNPoolingBlock

- (int)forward;
- (int)initializeRest;

@end
