/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPPhotoLibraryManager : NSObject

+ (id)sharedManager;

- (id)init;
- (id)systemPhotoLibrary;

@end
