/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeMonitor.framework/KnowledgeMonitor
 */

@interface _DKInteractionUtility : NSObject

+ (id)_participantToContact:(id)arg1;
+ (id)interactionFromCalendarEvent:(id)arg1;

@end
