/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeMonitor.framework/KnowledgeMonitor
 */

@interface _DKWiredNetworkQualityMonitor : _DKNetworkQualityMonitor

+ (id)eventStream;

- (id)init;

@end
