/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI
 */

@interface AKAppleIDAuthenticationInAppExtensionContext : AKAppleIDAuthenticationInAppContext

- (void)remoteUIController:(id)arg1 didFinishLoadWithError:(id)arg2;

@end
