/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKAttributionTextView : UITextView

- (id)initWithAttributedText:(id)arg1 selectable:(bool)arg2;

@end
