/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKAxisLabelDimensionInteger : HKAxisLabelDimensionScalar

- (double)niceStepSizeLargerThan:(double)arg1;
- (void)setStepSizeForLabels:(double)arg1;

@end
