/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKDateCoordinateTransform : HKCoordinateTransform

- (double)coordinateForValue:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)valueForCoordinate:(double)arg1;

@end
