/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKInteractiveChartCategoryValueFormatter : HKInteractiveChartDataFormatter

- (id)_formattedStringWithValue:(long long)arg1;
- (id)formattedSelectedRangeLabelDataWithChartData:(id)arg1;
- (id)formattedValueStringForChartData:(id)arg1 options:(long long)arg2;

@end
