/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKLastUpdatedDayCurrentValueDataProvider : HKMostRecentValueDataProvider

- (id)currentValue;

@end
