/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKNumericMinimumRangeAxisScalingRule : HKAbstractMinimumRangeScalingRule

+ (id)ruleWithDefaultYAxisRange:(double)arg1 axisRangeOverrides:(id)arg2;

@end
