/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKTableViewController : UITableViewController

- (unsigned long long)supportedInterfaceOrientations;

@end
