/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKUIConnectedGymIconUtilties : NSObject

+ (id)iconForConnectedGymDevice:(id)arg1 preferredIconWidth:(double)arg2;
+ (void)initialize;

@end
