/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSCKServerChangeToken : NSObject <NSCopying, NSSecureCoding>

+ (Class)__class;
+ (id)alloc;

@end
