/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSSocketPairExpiredAckMessage : IDSSocketPairAckMessage

- (unsigned char)command;

@end
