/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSSocketPairSMSReadReceipt : IDSSocketPairDataMessage

- (unsigned char)command;

@end
