/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Spotlight.framework/Spotlight
 */

@interface SPZKWSession : NSObject

+ (id)cachedZKWAppBundleIDs;

- (id)queryWithContext:(id)arg1;

@end
