/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVModifySharedCalendarShareeListPostTask : CoreDAVPostTask

- (id)copyDefaultParserForContentType:(id)arg1;

@end
