/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVGetCalendarItemTask : CoreDAVGetTask

- (void)finishCoreDAVTaskWithError:(id)arg1;

@end
