/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

@interface ASViewControllerFactory : SUViewControllerFactory

- (id)newNetworkLockoutViewControllerWithSection:(id)arg1;
- (id)newPlaceholderViewController;

@end
