/* Generated by EzioChiu
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKNSString : WKObject <NSCopying>

- (id)_web_createTarget;
- (Class)class;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (Class)superclass;

@end
