/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICACAccountVerificationOperation : ICUserVerificationOperation

- (void)execute;

@end
