/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICPurchaseRedownloadRequest : ICMediaRedownloadRequest

- (id)init;
- (id)initWithRequestContext:(id)arg1 storeItemID:(unsigned long long)arg2;

@end
