/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Social.framework/Social
 */

@interface SLGoogleClient : NSObject

+ (id)clientID;
+ (id)clientRedirect;
+ (id)clientRedirectForAppOpenURL;
+ (id)clientSecret;
+ (id)defaultScope;
+ (id)youTubeScope;

@end
