/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Social.framework/Social
 */

@interface SLRemoteServicePlistLoader : NSObject

+ (id)allServices;
+ (id)loadRemoteServicesFromPlistResourceName:(id)arg1 inBundle:(id)arg2;

@end
