/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Social.framework/Social
 */

@interface SLYouTubeAuthFlowController : SLGoogleAuthFlowController

- (id)authURLForUsername:(id)arg1;

@end
