/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIFourfoldReflectedTile : CITile2Filter

- (id)_kernel_name;
- (id)_kernel_source;
- (id)outputImage;

@end
