/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIGenericMetalProcessorSingleChannel : CIGenericMetalProcessor

+ (int)formatForInputAtIndex:(int)arg1;
+ (int)outputFormat;

@end
