/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CILuminosityBlendMode : CIPDFNonSeparableBlendMode

- (id)_kernel_v0;
- (id)_kernel_v1;

@end
