/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIPhotoEffect3DSilverplate : CIPhotoEffect3D

- (int)_defaultVersion;
- (int)_maxVersion;

@end
