/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIPlusLighterCompositing : _CICompositeFilter

+ (id)_kernel;
+ (id)customAttributes;

- (id)outputImage;

@end
