/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TemplateKit.framework/TemplateKit
 */

@interface TLKFormattedTextItem : TLKObject

- (unsigned long long)_itemType;
- (bool)hasContent;

@end
