/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionPredictionHeuristicsInternal.framework/ActionPredictionHeuristicsInternal
 */

@interface ATXBestContactHandleGuardedData : NSObject {
    NSString * contactIdentifier;
}

- (void).cxx_destruct;

@end
