/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarNotification.framework/CalendarNotification
 */

@interface CALNNotificationFilter : NSObject

+ (bool)shouldIgnoreNotificationForEvent:(id)arg1;

@end
