/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXAppearComponentAnimation : SXComponentAnimation

+ (id)typeString;

- (Class)handlerClass;

@end
