/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXAppearComponentAnimationHandler : SXComponentAnimationHandler

- (void)finishAnimation;
- (void)prepareAnimation;
- (void)startAnimation;

@end
