/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXAXCustomRotorDefinition : NSObject

+ (id)audioVideoRotor;
+ (id)headingsRotor;
+ (id)imagesRotor;
+ (id)linksRotor;

@end
