/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXBookmarkAction : SXAction {
    <SXBookmark> * _bookmark;
}

@property (nonatomic, readonly) <SXBookmark> *bookmark;

- (void).cxx_destruct;
- (id)bookmark;
- (id)initWithBookmark:(id)arg1;

@end
