/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXChapterComponentClassification : SXDefaultSectionComponentClassification

+ (int)role;
+ (id)roleString;

- (id)accessibilityContextualLabel;

@end
