/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXDefaultImageComponentClassification : SXComponentClassification

+ (int)role;
+ (id)roleString;
+ (id)typeString;

- (Class)componentModelClass;
- (bool)hasAffiliationWithClassification:(id)arg1 forDirection:(long long)arg2;

@end
