/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXDefaultTwitterEmbedComponentClassification : SXDefaultEmbedComponentClassification

+ (bool)shouldRegister;
+ (id)typeString;

- (Class)componentModelClass;

@end
