/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXDefaultMapComponentClassification : SXComponentClassification

+ (int)role;
+ (id)roleString;
+ (id)typeString;

- (Class)componentModelClass;

@end
