/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXDividerComponentClassification : SXDefaultLineComponentClassification

+ (int)role;
+ (id)roleString;
+ (id)typeString;

- (unsigned long long)contentRelevance;

@end
