/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXEmbedVideoComponentSizer : SXComponentSizer

- (double)calculateHeightForWidth:(double)arg1 inColumnLayout:(id)arg2;

@end
