/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXFadeComponentAnimationHandler : SXComponentAnimationHandler

- (void)finishAnimation;
- (double)initialAlpha;
- (void)prepareAnimation;
- (void)startAnimation;
- (void)updateAnimationWithFactor:(double)arg1;

@end
