/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXLineComponent : SXComponent

@property (nonatomic, readonly) SXStrokeStyle *stroke;

+ (id)typeString;

@end
