/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXParallaxScaleScene : SXComponentAnimation

+ (id)typeString;

- (Class)handlerClass;
- (bool)userControllable;

@end
