/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXParallaxFadeScene : SXComponentAnimation

@property (nonatomic, readonly) UIColor *fadeColor;

+ (id)typeString;

- (Class)handlerClass;
- (bool)userControllable;

@end
