/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXPhoneNumberAddition : SXAddition

@property (nonatomic, readonly) NSString *phoneNumber;

+ (id)typeString;

- (id)action;

@end
