/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXScaleAndFadeComponentAnimation : SXComponentAnimation

@property (nonatomic, readonly) double initialAlpha;
@property (nonatomic, readonly) double initialScale;

+ (id)typeString;

- (Class)handlerClass;

@end
