/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXSectionComponentClassification : SXDefaultSectionComponentClassification

+ (int)role;
+ (id)roleString;

@end
