/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXTextStroke : SXJSONObject

@property (nonatomic, readonly) UIColor *color;
@property (nonatomic, readonly) double width;

@end
