/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HeartRhythmUI.framework/HeartRhythmUI
 */

@interface HROnboardingElectrocardiogramCheckRhythmViewController : HROnboardingAgeGateViewController

- (id)ageIneligiblePromptAckButtonString;
- (id)ageIneligiblePromptBodyString;
- (id)ageIneligiblePromptTitleString;
- (id)ageLimit;
- (id)bodyString;
- (id)buttonTitleString;
- (id)createHeroView;
- (id)disclaimerString;
- (id)initForOnboarding:(bool)arg1;
- (id)learnMoreString;
- (id)titleString;

@end
