/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVRemoteUI.framework/TVRemoteUI
 */

@interface _TVRPresentationController : UIPresentationController

- (bool)_shouldRespectDefinesPresentationContext;
- (bool)shouldPresentInFullscreen;

@end
