/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AssetViewer.framework/AssetViewer
 */

@interface ASVARSnapshotManager : NSObject

+ (void)showARSnapshotUIForImage:(id)arg1;

@end
