/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSParsecSearchUtilities : NSObject

+ (bool)anyParsecSearchResult:(id)arg1 fuzzyMatchesSuggestedSiteURLString:(id)arg2;

@end
