/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSReaderLocalizedFonts : NSObject

+ (id)defaultFontFamilyNameForLanguage:(id)arg1;
+ (id)fontsForLanguage:(id)arg1;

@end
