/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSSiteIconKeyColorExtractor : NSObject

+ (char *)_createRGBAPixelBufferFromImage:(struct CGImage { }*)arg1;
+ (id)keyColorForIcon:(id)arg1;

@end
