/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpotlightDaemon.framework/SpotlightDaemon
 */

@interface MDAgent : NSObject

+ (id)sharedAgent;

- (void)handleLogInOut;
- (id)init;

@end
