/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSCFMemoryURLCredentialStorage : NSURLCredentialStorage

- (id)description;
- (id)init;

@end
