/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSURLRequestInternal : NSObject {
    struct _CFURLRequest { } * request;
}

- (void)dealloc;

@end
