/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextToSpeech.framework/TextToSpeech
 */

@interface TTSFormatArgument : NSObject {
    NSDictionary * attributes;
    NSString * formatSpecifier;
    NSString * formattedArg;
}

- (void)dealloc;

@end
