/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface FigCaptureAudioPreviewSinkConfiguration : FigCaptureSinkConfiguration

- (int)sinkType;

@end
