/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface FigDepthDataCaptureConnectionConfiguration : FigVideoCaptureConnectionConfiguration

- (id)description;

@end
