/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface FigVisionDataCaptureConnectionConfiguration : FigVideoCaptureConnectionConfiguration

- (id)description;
- (id)init;

@end
