/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDBradycardiaDataAggregator : HDHeartEventDataAggregator

- (id)_categoryType;

@end
