/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDDNDModeAssertionService : NSObject <HDDNDModeAssertionService>

- (void)invalidateAssertion;
- (void)requestQuietModeOverrideAssertion;

@end
