/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDHeartRateVariabilityDataAggregator : HDQuantityDatumPassthroughAggregator

+ (id)quantityTypeIdentifier;

@end
