/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDWorkoutRouteBuilderEntity : HDSeriesBuilderEntity

+ (Class)seriesEntityClass;

@end
