/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAlbumListViewControllerPadImagePickerSpec : PUAlbumListViewControllerCommonImagePickerSpec

- (id)albumViewControllerSpec;
- (id)gridViewControllerSpec;

@end
