/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUBlackOneUpWhiteTintInterfaceTheme : PUBlackOneUpInterfaceTheme

- (id)tintColorForBarStyle:(long long)arg1;

@end
