/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUCrossfadeModalTransition : PUModalTransition

- (void)animateDismissTransition;
- (void)animatePresentTransition;
- (id)init;

@end
