/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PULegacyViewControllerSpec : NSObject

+ (id)padSpec;
+ (id)phoneSpec;
+ (id)specForIdiom:(long long)arg1;

@end
