/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotosMapGridViewControllerPhoneSpec : PUPhotosGridViewControllerPhoneSpec

- (bool)usesStackPopTransition;

@end
