/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotoKitRevealInMomentActionPerformer : PUPhotoKitNavigateToPhotosActionPerformer

+ (bool)canPerformOnAsset:(id)arg1 inAssetCollection:(id)arg2;

@end
