/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotosMapGridViewControllerPadSpec : PUPhotosGridViewControllerPadSpec

- (bool)usesStackPopTransition;

@end
