/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotosAlbumViewControllerPadImagePickerSpec : PUPhotosAlbumViewControllerPadSpec

- (id)gridSpec;

@end
