/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotoKitRemoveNoConfirmActionPerformer : PUPhotoKitRemoveActionPerformer

- (bool)shouldShowConfirmation;

@end
