/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUSlideshowSettingsPersistency : NSObject

+ (id)createSlideshowSettingsViewModel;
+ (void)saveSlideshowSettingsViewModel:(id)arg1;

@end
