/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUVideoListBrowsingSession : PUBrowsingSession

+ (id)newBrowsingSessionWithDataSource:(id)arg1 actionPerformerDelegate:(id)arg2;

@end
