/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUWallpaperNavigationController : UINavigationController

- (unsigned long long)supportedInterfaceOrientations;

@end
