/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
 */

@interface CKAccountsSelectionList : PSListItemsController

- (id)specifiers;

@end
