/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
 */

@interface CNFRegAddAliasTableCell : PSTableCell

- (void)layoutSubviews;

@end
