/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DAEASOAuthFramework.framework/DAEASOAuthFramework
 */

@interface DAEASOpenIDMetadataRequest : NSObject

+ (id)openIDrequestURLFor:(id)arg1;

@end
