/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@interface MSVArtworkServiceConversionOperation : MSVArtworkServiceOperation

- (void)main;

@end
