/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
 */

@interface FIUINavigationController : UINavigationController

- (id)initWithRootViewController:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;

@end
