/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
 */

@interface FIUIWorkoutActivityDefaultPaceMigrator : NSObject

+ (void)migrateDefaultOutdoorRunningWalkingPaceFromCurrentToAverage;
+ (void)migrateDefaultOutdoorRunningWalkingPaceFromCurrentToAverageWithSyncManager:(id)arg1 domainAccessor:(id)arg2;

@end
