/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
 */

@interface FIUIActivitySharingNotificationIcons : NSObject

+ (id)activitySharingIconOfType:(unsigned long long)arg1;

@end
