/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WiFiKit.framework/WiFiKit
 */

@interface WFHotspotProfile : WFNetworkProfile

- (id)initWithProfile:(id)arg1 anqpResponse:(id)arg2;

@end
