/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WiFiKit.framework/WiFiKit
 */

@interface WFMISDisablePromptOperation : WFUserPromptOperation

+ (id)misDisablePromptOperation;

@end
