/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenReaderOutput.framework/ScreenReaderOutput
 */

@interface SCROIOUSBElement : SCROIOElement

- (id)initWithIOObject:(unsigned int)arg1;
- (int)transport;

@end
