/* Generated by EzioChiu
   Image: /System/Library/Frameworks/GameplayKit.framework/GameplayKit
 */

@interface GKNoiseSourceUtils : NSObject

+ (double)radialLerpValueForDistanceToOrigin:(double)arg1 frequency:(double)arg2;

@end
