/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKKnowledgeStoreUtils : NSObject

+ (bool)isHexaKey:(id)arg1;

- (id)init;

@end
