/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CoreKnowledge.Matcher : SwiftObject {
    void comparison;
    void sql.storage;
    void value;
}

@end
