/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CoreKnowledge.INInteractionEncoder : SwiftObject {
    void interaction;
}

@end
