/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PPLocalNamedEntityStoreGuardedData : NSObject {
    NSMutableArray * _namedEntitiesForOverride;
    bool  _pendingNamedEntityChangeNotification;
}

- (void).cxx_destruct;

@end
