/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKCollectionListElement : IKViewElement

@property (nonatomic, readonly, retain) NSArray *collections;

- (id)collections;

@end
