/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKCSSTypeInfo : NSObject

+ (id)getTypeInfoForPropertyName:(id)arg1;
+ (void)registerStyle:(id)arg1 type:(unsigned long long)arg2;
+ (void)unregisterStyles;

@end
