/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKLoadingTemplate : IKViewElement

@property (nonatomic, readonly, retain) IKViewElement *activityElement;

- (id)activityElement;

@end
