/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKMenuItemElement : IKViewElement

@property (nonatomic, readonly, retain) IKTextElement *title;

- (id)title;

@end
