/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKPreference : NSObject

+ (bool)ignoreHTTPCache;
+ (bool)logDocumentXML;
+ (void)setupJSCoreConsoleLogging;

@end
