/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKVideoElement : IKMediaElement

@property (nonatomic, readonly, retain) NSArray *timelines;

- (id)timelines;

@end
