/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKXMLSerializer : IKJSObject <IKJSXMLSerializer>

- (id)init;
- (id)serializeToString:(id)arg1;

@end
