/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaSocial.framework/MediaSocial
 */

@interface MSCLSettingsTableHeaderView : UITableViewHeaderFooterView

- (void)layoutSubviews;

@end
