/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPDeviceInfo : NSObject

+ (bool)isDataCollectionEnabled;
+ (bool)isDisabledByTasking;
+ (bool)isInternalBuild;
+ (id)osVersion;

@end
