/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPErrorUtilities : NSObject

+ (bool)isCoreDataFatalError:(id)arg1;

@end
