/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPHCMSWordMO : _DPCMSWordMO

@property (nonatomic) int fragmentBitIndex;
@property (nonatomic) int sequenceBitIndex;

+ (id)fetchRequest;

@end
