/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPHCMSSequenceMO : _DPCMSSequenceMO

@property (nonatomic) int sequenceBitIndex;

+ (id)fetchRequest;

@end
