/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPLog : NSObject

+ (id)daemon;
+ (id)framework;
+ (id)tool;

@end
