/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
 */

@interface _DPPrivacyBudgetManager : NSObject <_DPMaintenance>

- (void)scheduleMaintenanceWithName:(id)arg1 database:(id)arg2;

@end
