/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
 */

@interface UISApplicationSupportClient : FBSServiceFacilityClient

- (id)edgeInfoForDisplayConfiguration:(id)arg1;
- (id)init;
- (id)initialDisplayContext;
- (void)requestPasscodeUnlockUIWithCompletion:(id /* block */)arg1;

@end
