/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRGetVoiceInputDevicesMessage : MRProtocolMessage

- (unsigned long long)type;

@end
