/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRGetRemoteTextInputSessionMessage : MRProtocolMessage

- (id)init;
- (unsigned long long)type;

@end
