/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRRemoveFromParentGroupMessage : MRRemoveOutputDevicesMessage

- (unsigned long long)type;

@end
