/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKDecibelSPLUnit : HKPressureUnit

- (double)_convertFromBaseUnit:(double)arg1;
- (double)_convertToBaseUnit:(double)arg1;

@end
