/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKDiagnosticTestReportType : HKMedicalType

+ (id)allTypes;
+ (id)diagnosticTestReportType;

@end
