/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKDocumentSample : HKSample

@property (readonly) HKDocumentType *documentType;

- (id)documentType;

@end
