/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface _MFPlainAuthenticator : MFSASLAuthenticator

- (bool)justSentPlainTextPassword;
- (id)responseForServerData:(id)arg1;
- (id)saslName;

@end
