/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface _MFRootlessMailboxUid : MFMailboxUid

- (id)displayName;
- (id)fullPath;
- (id)storeForMailboxUid:(id)arg1;
- (id)tildeAbbreviatedPath;

@end
