/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFMailMimeTextAttachment : MFMimeTextAttachment

- (bool)shouldDownloadAttachmentOnDisplay;

@end
