/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFNTLMAuthScheme : MFAuthScheme

- (Class)authenticatorClass;
- (bool)hasEncryption;
- (id)humanReadableName;
- (id)name;
- (bool)sendsPlainTextPasswords;

@end
