/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSDictionaryObjectEnumerator : __NSFastEnumerationEnumerator

- (id)nextObject;

@end
