/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSAutoBlock : NSBlock

- (id)copy;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
