/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface CFPrefsConfigurationFileSource : CFPrefsSource

- (id)initWithConfigurationPropertyList:(struct __CFDictionary { }*)arg1 containingPreferences:(id)arg2;

@end
