/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface _ATXDataStoreMigrations : NSObject

+ (id)migrations;
+ (id)skipFromZeroSchema:(unsigned long long*)arg1;

@end
