/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface _ATXActionPredictionsLogger : NSObject

+ (void)logDailyActionPredictions;
+ (void)logDonatedNSUAs;
+ (void)logPreferenceSettings;

@end
