/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXCoalescingGuardedData : NSObject {
    NSMutableArray * pendingCompletions;
    NSObject<OS_os_transaction> * txn;
}

- (void).cxx_destruct;

@end
