/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXDigitalHealthBlacklistGuardedData : NSObject {
    NSSet * _blacklistedBundles;
}

- (void).cxx_destruct;
- (id)init;

@end
