/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXDuetGuardedRootOfAppData : NSObject {
    ATXRootOfAppData * _rootOfAppData;
    NSDate * _rootOfAppDataUpdateTime;
}

- (void).cxx_destruct;

@end
