/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXLockscreenBlacklistData : NSObject {
    NSSet * cachedBlacklist;
    NSNumber * cachedPredictionsDisabled;
}

- (void).cxx_destruct;

@end
