/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXPassAllBundleIdFilter : ATXBundleIdFilter

- (id)applyFilter:(id)arg1;

@end
