/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
 */

@interface CAMStopPanoramaCommand : CAMCaptureCommand

- (void)executeWithContext:(id)arg1;

@end
