/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP
 */

@interface CDPPCSUtilities : NSObject

+ (id)_pcsConfigForPrimaryAccount;
+ (id)setupDictionaryWithContext:(id)arg1;

@end
