/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface _NSOrderedSetDiffInsert : _NSOrderedSetDiffChange

- (void)applyToSet:(id)arg1;
- (id)description;

@end
