/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLEntityKey : NSSQLColumn

- (id)initWithEntity:(id)arg1 propertyDescription:(id)arg2;
- (id)name;

@end
