/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLXPCFetchRequestContext : NSSQLFetchRequestContext

- (void)executeEpilogue;
- (void)executeRequestCore:(id*)arg1;

@end
