/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SampleAnalysis.framework/SampleAnalysis
 */

@interface SAUserTruncatedBacktrace : SAFrame

- (bool)isTruncatedBacktraceFrame;

@end
