/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoFoundation.framework/PhotoFoundation
 */

@interface _PFMainThreadReleaseMethods : NSObject

- (void)mainThreadRelease;

@end
