/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoFoundation.framework/PhotoFoundation
 */

@interface PFAssertionPolicyAlertRadar : PFAssertionPolicyAlert

- (void)notifyAssertion:(id)arg1;

@end
