/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICBrickTextAttachment : ICTextAttachment

- (bool)supportsThumbnailView;
- (double)viewCornerRadius;

@end
