/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICHandwritingDebugUtilities : NSObject

+ (void)tapToRadarWithTitle:(id)arg1 forDrawings:(id)arg2;
+ (id)writeFileFromDrawings:(id)arg1;

@end
