/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICHelpViewNavigationController : UINavigationController

- (unsigned long long)supportedInterfaceOrientations;

@end
