/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICUnsupportedTextAttachmentWithFallbackImage : ICImageTextAttachment

- (id)attachmentAsNSTextAttachment;
- (bool)supportsMultipleThumbnailsOnSameLine;
- (bool)supportsThumbnailView;

@end
