/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteMediaServices.framework/RemoteMediaServices
 */

@interface RMSPairingSession : NSObject

+ (id)localPairingSession;
+ (id)proxyPairingSession;

@end
