/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIReviewListViewElement : SKUIViewElement

@property (nonatomic, readonly) NSArray *items;

- (id)items;
- (long long)pageComponentType;

@end
