/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIReportAConcernViewController : UINavigationController

- (id)initWithConfiguration:(id)arg1;

@end
