/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIViewControllerFactory : SUViewControllerFactory

- (id)newPlaceholderViewController;

@end
