/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIReviewListPageComponent : SKUIPageComponent

@property (nonatomic, readonly) SKUIReviewListViewElement *viewElement;

- (long long)componentType;
- (id)initWithViewElement:(id)arg1;

@end
