/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUISortDescriptorListViewElement : SKUIViewElement

@property (nonatomic, readonly, copy) NSArray *sortDescriptorViewElements;

- (id)sortDescriptorViewElements;

@end
