/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUICellImageView : UIImageView {
    UIColor * _cachedBackgroundColor;
}

- (void).cxx_destruct;
- (void)setHighlighted:(bool)arg1;

@end
