/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIBrowseHeaderPageComponent : SKUIPageComponent

- (long long)componentType;

@end
