/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIBannerCloseButton : UIButton

- (void)layoutSubviews;
- (void)setHighlighted:(bool)arg1;

@end
