/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIRatingResponseProvider : ISPropertyListProvider

- (bool)parseData:(id)arg1 returningError:(id*)arg2;

@end
