/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUISpacePageComponent : SKUIPageComponent {
    double  _height;
}

@property (nonatomic, readonly) double height;

- (long long)componentType;
- (double)height;
- (id)initWithCustomPageContext:(id)arg1;

@end
