/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIProductPageTableSeparatorView : UIView {
    UIView * _separatorView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;

@end
