/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIPaletteViewElement : SKUIViewElement

- (void)enumerateChildrenUsingBlock:(id /* block */)arg1;

@end
