/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIArtworkProvidingFactory : NSObject

+ (id)artworkCacheCandidatesForProvider:(id)arg1;
+ (id)artworkProviderForStoreResponse:(id)arg1;

@end
