/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUILimitListViewElement : SKUIViewElement

@property (nonatomic, readonly, copy) NSArray *limitViewElements;

- (id)limitViewElements;

@end
