/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIStarHistogramViewElement : SKUIViewElement

- (long long)pageComponentType;

@end
