/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIURLConnectionRequest : SSURLConnectionRequest

- (void)startWithConnectionResponseBlock:(id /* block */)arg1;

@end
