/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIDefaultSettingDescription : SKUISettingDescription

+ (Class)_viewClassForSettingDescription:(id)arg1;

@end
