/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUISettingsTableHeaderFooterView : UITableViewHeaderFooterView {
    SKUISettingsHeaderFooterDescriptionView * _settingsHeaderFooterDescriptionView;
}

- (void).cxx_destruct;
- (void)displaySettingsHeaderFooterDescriptionView:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;

@end
