/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iCloudQuotaUI.framework/iCloudQuotaUI
 */

@interface ICQPageView : UIView

- (id)horizontalConstraintsForView:(id)arg1 margin:(double)arg2;

@end
