/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TVRemoteCore.framework/TVRemoteCore
 */

@interface _TVRCXPCProtocolManager : NSObject

+ (id)requestInterface;
+ (id)responseInterface;

@end
