/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MailSupport.framework/MailSupport
 */

@interface MSAccountToEmailProvider : NSObject

+ (int)emailProviderFromAccountStatisticsKind:(id)arg1;

@end
