/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBAbstractSpringBoardDefaultDomain : BSAbstractDefaultDomain

- (id)init;

@end
