/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBFLockScreenWallpaperParallaxSettings : SBFWallpaperParallaxSettings

- (void)setDefaultValues;

@end
