/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBFPasscodeLockTrackerForPreventLockAssertions : SBFAuthenticationAssertionTracker

@end
