/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBFPasscodeLockTrackerForTransientAssertions : SBFAuthenticationAssertionTracker

- (bool)isAssertionValid:(id)arg1;
- (id)mkbAssertionOptions;

@end
