/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoAnalysis.framework/PhotoAnalysis
 */

@interface PHAAssetResourceDataLoadingOptions : NSObject {
    bool  _canUseNetwork;
}

@property (nonatomic) bool canUseNetwork;

- (bool)canUseNetwork;
- (void)setCanUseNetwork:(bool)arg1;

@end
