/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SetupAssistantSupport.framework/SetupAssistantSupport
 */

@interface SASProximityReadyAction : SASProximityAction

+ (unsigned long long)actionID;

@end
