/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SetupAssistantSupport.framework/SetupAssistantSupport
 */

@interface SASSystemInformation : NSObject

+ (long long)compareProductVersion:(id)arg1 toProductVersion:(id)arg2;
+ (id)productVersion;

@end
