/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface _CNReputationPhoneNumberHandle : CNReputationHandle

- (void)configureBuilder:(id)arg1;

@end
