/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNCFPhoneNumber : NSObject

+ (id)makeProxy;

- (struct __CFPhoneNumber { }*)create:(id)arg1 :(id)arg2;

@end
