/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNSecureCodingClassSets : NSObject

+ (id)contactStoreClasses;
+ (id)keyDescriptorClasses;

@end
