/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

@interface CalDefaults : NSObject

+ (void)initialize;
+ (id)shared;
+ (id)thisProcess;

@end
