/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

@interface CalLogUserNotificationWriter : CalLogWriter

- (void)write:(id)arg1;

@end
