/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

@interface EKProtocolObject_Shared : NSObject

+ (bool)shouldCreatePartialObjectForObject:(id)arg1;

@end
