/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDContactUtils : NSObject

+ (id)normalizedPhoneNumberFromString:(id)arg1;
+ (bool)phoneNumber:(id)arg1 isEqualToPhoneNumber:(id)arg2;

@end
