/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDFaceTimeAction : DDFaceTimeAudioAction

+ (bool)isAvailable;

- (id)dialRequest;
- (id)localizedName;
- (id)notificationTitle;

@end
