/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDMoreCallActionsAction : DDMoreActionsAction

+ (bool)isAvailable;

- (id)alertActions;

@end
