/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDRelayCallAction : DDAssistedCallAction

- (long long)TTYType;
- (id)localizedName;

@end
