/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface ___UIAccessibilityNSAttributedString_super : UIAccessibilitySafeCategory

@end
