/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface __NSConcreteMutableAttributedStringAccessibility_super : UIAccessibilitySafeCategory

@end
