/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface UIAccessibilityMathWebView : WKWebView

- (bool)_accessibilityIsMathTouchExplorationView;

@end
