/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Swift/libswiftFoundation.dylib
 */

@interface _TtCE10FoundationCSo12NSDictionary8Iterator : SwiftObject {
    void _fastIterator;
}

@end
