/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Swift/libswiftFoundation.dylib
 */

@interface Foundation.JSONDecoder : SwiftObject {
    void dataDecodingStrategy;
    void dateDecodingStrategy;
    void keyDecodingStrategy;
    void nonConformingFloatDecodingStrategy;
    void userInfo;
}

@end
