/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Swift/libswiftFoundation.dylib
 */

@interface Foundation.PropertyListEncoder : SwiftObject {
    void outputFormat;
    void userInfo;
}

@end
