/* Generated by EzioChiu
   Image: /System/Library/Frameworks/IntentsUI.framework/IntentsUI
 */

@interface _INUIXPCInterfaceUtilities : NSObject

+ (id)extensionContextHostingInterface;
+ (id)extensionContextVendingInterface;
+ (id)remoteViewControllerHostingInterface;
+ (id)remoteViewControllerServingInterface;

@end
