/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CompassUI.framework/CompassUI
 */

@interface CUICalibration : NSObject

+ (void)dismissCalibrationAlert;
+ (void)showCalibrationAlert;

@end
