/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKMinimalTextColorUserInterfaceItem : AKMinimalColorChooserUserInterfaceItem

- (id)convertTextAttributes:(id)arg1;

@end
