/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKSignatureAnnotationEventHandler : AKRectangularAnnotationEventHandler

- (bool)alwaysLockAspectRatio;
- (struct CGSize { double x1; double x2; })naturalSizeForAnnotation;

@end
