/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKSmoothPathView_iOS : AKSmoothPathView

- (void)handleForwardedEvent:(id)arg1;

@end
