/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKToolbarUtilities : NSObject

+ (long long)attributeTagForCurrentSelectionState:(id)arg1;

@end
