/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKTriangleAnnotationEventHandler : AKRectangularAnnotationEventHandler

- (double)naturalAspectRatioForAnnotation;

@end
