/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKUserInterfaceItemHelper : NSObject

+ (long long)highlightAttributeTagFromHighlightToolTag:(long long)arg1;

@end
