/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHManhattanLineSketchRecognitionResult : CHLineSketchRecognitionResult

@end
