/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHNormalizedDrawingAllVisualization : CHNormalizedDrawingVisualization

- (bool)shouldDrawStrokeGroup:(id)arg1;

@end
