/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMAbstractView : DOMObject

@property (readonly) DOMDocument *document;

- (void)_disconnectFrame;
- (void)dealloc;
- (id)document;

@end
