/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMCSSFontFaceRule : DOMCSSRule

@property (readonly) DOMCSSStyleDeclaration *style;

- (id)style;

@end
