/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMHTMLParagraphElement : DOMHTMLElement

@property (copy) NSString *align;

- (id)align;
- (void)setAlign:(id)arg1;

@end
