/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMHTMLDListElement : DOMHTMLElement

@property bool compact;

- (bool)compact;
- (void)setCompact:(bool)arg1;

@end
