/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMHTMLTitleElement : DOMHTMLElement

@property (copy) NSString *text;

- (void)setText:(id)arg1;
- (id)text;

@end
