/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMNodeList : DOMObject

@property (readonly) unsigned int length;

- (void)dealloc;
- (id)item:(unsigned int)arg1;
- (unsigned int)length;

@end
