/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface DOMProcessingInstruction : DOMCharacterData

@property (readonly) DOMStyleSheet *sheet;
@property (readonly, copy) NSString *target;

- (id)sheet;
- (id)target;

@end
