/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebEditorUndoTarget : NSObject

- (void)redoEditing:(id)arg1;
- (void)undoEditing:(id)arg1;

@end
