/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebKitStatistics : NSObject

+ (int)HTMLRepresentationCount;
+ (int)bridgeCount;
+ (int)dataSourceCount;
+ (int)frameCount;
+ (int)viewCount;
+ (int)webViewCount;

@end
