/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCAccountUtilities : NSObject

+ (id)accountDataclassesForBundleID:(id)arg1;
+ (bool)hasManagedAccountOfDataclasses:(id)arg1;

@end
