/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCAggregateLogProfileRestrictionKey : MCAggregateLogFeatureKey

+ (void)update;

- (id)name;
- (unsigned long long)value;

@end
