/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCRestrictionUtilities : NSObject

+ (id)intersectionFeatureForPayloadRestrictionKey:(id)arg1;
+ (id)intersectionFeaturesWithPayloadRestictionKeyAlias;
+ (id)intersectionPayloadRestrictionKeyForFeature:(id)arg1;

@end
