/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCVPNPayload : MCVPNPayloadBase

+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;

@end
