/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _CDDatePrinter : NSObject

+ (id)dateStringFromDate:(id)arg1;
+ (id)dateStringFromInterval:(double)arg1;

@end
