/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _CDLogging : NSObject

+ (id)admissionCheckChannel;
+ (id)autoSUChannel;
+ (id)communicatorChannel;
+ (id)contextChannel;
+ (id)instrumentationChannel;
+ (id)interactionChannel;
+ (id)interactionSignpost;
+ (id)knowledgeChannel;
+ (id)knowledgeSignpost;
+ (id)syncChannel;

@end
