/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKAppActivityStreamTombstoneRequirement : _DKTombstoneRequirement

- (id)eventPredicate;
- (id)predicate;

@end
