/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKCategoryMO : _DKObjectMO

@property (nonatomic) long long categoryType;
@property (nonatomic) long long integerValue;

@end
