/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKFetchRecordZoneChangesOperation : CKFetchRecordZoneChangesOperation

+ (bool)_removesDependenciesAfterFinish;

- (void)main;

@end
