/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKMetadataPersistenceLookupTable : NSObject

+ (id)attributeToKey;
+ (id)keyToAttribute;

@end
