/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKMicroLocationMetadataKey : NSObject

+ (id)locationDistribution;
+ (id)microLocationDistribution;

@end
