/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKPrivacyPolicyEnforcer : NSObject

+ (id)privacyPolicyEnforcer;

- (id)enforcePrivacy:(id)arg1;

@end
