/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKQueryOperation : CKQueryOperation

+ (bool)_removesDependenciesAfterFinish;

- (void)main;

@end
