/* Generated by EzioChiu
   Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CAMutableDisplayPreferences : CADisplayPreferences

@property (nonatomic) bool matchContent;
@property (nonatomic, copy) NSString *preferredHdrMode;

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
