/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface AllowChangesCell : PSTableCell {
    UIImageView * _lock;
}

- (void).cxx_destruct;
- (bool)canReload;
- (void)layoutSubviews;
- (void)setValue:(id)arg1;

@end
