/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface IgnoreLabelDisableCell : PSTableCell

- (void)setCellEnabled:(bool)arg1;

@end
