/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSPearlPINController : PSBiometricPINController

- (id)pinInstructionsPrompt;

@end
