/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSTouchIDPINController : PSBiometricPINController

- (id)pinInstructionsPrompt;

@end
