/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIAdvertisingController : PSListController

- (void)updateSpecifiersForImposedSettings;

@end
