/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIAllowTCCRestrictionsController : PSUITCCAccessController {
    PSSpecifier * _allowedGroup;
}

- (void).cxx_destruct;
- (id)specifiers;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

@end
