/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUITVOutManager : NSObject {
    int  _connectedAdapterType;
}

- (int)connectedAdapterType;
- (id)init;
- (void)refreshConnectedAdapterType;

@end
