/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIDefaultVoiceLineListItemsController : PSListItemsController

- (id)init;
- (void)reloadCache;
- (id)specifiers;

@end
