/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface StorageNeededLinkFooterView : PSFooterHyperlinkView

- (id)initWithSpecifier:(id)arg1;
- (void)setText:(id)arg1;

@end
