/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DuetExpertCenter.framework/DuetExpertCenter
 */

@interface _DKExpertConsumerCategory : NSObject

+ (id)spotlight;
+ (id)springboard;
+ (id)stark;
+ (id)type;

@end
