/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DuetExpertCenter.framework/DuetExpertCenter
 */

@interface _DKExpertFeedbackMetadataKey : NSObject

+ (id)category;
+ (id)expertIdentifier;
+ (id)feedback;

@end
