/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AirTrafficDevice.framework/AirTrafficDevice
 */

@interface ATDeviceMessageLink : ATConcreteMessageLink

+ (id)deviceMessageLink;

- (id)initWithSocket:(id)arg1;

@end
