/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
 */

@interface PBStreamWriter : NSObject

+ (id)writeProtoBuffers:(id)arg1 toFile:(id)arg2;

@end
