/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosImagingFoundation.framework/PhotosImagingFoundation
 */

@interface IPAIdentityOperator : IPAGeometryOperator

- (id)description;
- (id)transformForGeometry:(id)arg1;

@end
