/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosImagingFoundation.framework/PhotosImagingFoundation
 */

@interface IPALocalPreviewSizeRegistry : IPAPreviewSizeRegistry

+ (id)sharedInstance;

- (id)init;

@end
