/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosImagingFoundation.framework/PhotosImagingFoundation
 */

@interface IPARemoveAutoSettings : IPAAutoSettings

- (id)init;
- (id)initWithIdentifier:(id)arg1;

@end
