/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
 */

@interface DOCDocumentManagerDimmingView : UIView

- (id)init;
- (void)tapGestureRecognized:(id)arg1;

@end
