/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
 */

@interface DOCExtensionInterface : NSObject

+ (id)hostProtocol;
+ (id)vendorProtocol;

@end
