/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
 */

@interface DOCKeyCommandRegistry : NSObject

+ (id)_defaultIdentifiersAndKeyCommands;
+ (id)sharedInstance;

- (id)defaultKeyCommandsExcluding:(id)arg1;
- (void)keyCommandWasPerformed:(id)arg1;

@end
