/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDContentsName : NSManagedObject

@property (nonatomic, retain) NSString *name;

@end
