/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDLayerStackProduction : TDNamedArtworkProduction

@property (nonatomic, retain) TDNamedArtworkProduction *flattenedImageProduction;
@property (nonatomic, retain) TDSimpleArtworkElementProduction *radiosityImageProduction;

@end
