/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDLayerReference : TDAbstractLayerReference

@property (nonatomic, retain) TDNamedArtworkProduction *reference;
@property (nonatomic, retain) TDLayerStackRenditionSpec *stack;

- (id)cuiLayerReference;

@end
