/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDLayerMapping : NSManagedObject

- (id)copyDataFromAttributes;
- (void)setAttributesFromCopyData:(id)arg1;

@end
