/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDMetafontSelector : TDThemeConstant

@property (nonatomic, retain) TDFontDefinition *definition;

@end
