/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDNamedTextureProduction : TDElementProduction

@property (nonatomic) bool optOutOfThinning;
@property (nonatomic, retain) TDTextureInterpretation *textureInterpretation;

@end
