/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDSchemaRenditionSpec : TDSimpleArtworkRenditionSpec

- (id)_slicesToUseForCSI;

@end
