/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDTag : NSManagedObject

@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSSet *productions;

@end
