/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDThemeLook : TDThemeConstant {
    bool  _supportsContrastAdjustment;
}

- (void)setSupportsContrastAdjustment:(bool)arg1;
- (bool)supportsContrastAdjustment;

@end
