/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
 */

@interface AAUIBleachedNavigationController : UINavigationController

- (bool)shouldAutorotate;
- (void)viewDidLoad;

@end
