/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
 */

@interface AAUICustomStylingCell : PSTableCell

- (void)layoutSubviews;
- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
