/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface _PLJPEGThumbnailPreheatItem : PLFigPreheatItem

- (id)decodeSessionOptions;

@end
