/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLAggdLogging : NSObject

+ (id)_addPrefix:(id)arg1 toKeysInDictionary:(id)arg2;
+ (void)performAnalysisStateLogging:(id)arg1;
+ (void)performCollectionsStaticsLogging:(id)arg1;
+ (void)performHyperionLocalResourcesLogging:(id /* block */)arg1;
+ (void)performLibraryStatisticsLogging:(id /* block */)arg1;
+ (void)performLibrarySummaryLogging:(id)arg1;
+ (void)performMomentsStatisticsLogging:(id)arg1;
+ (void)performPersistentHistorySummaryLogging:(id)arg1;
+ (void)performYearsStaticsLogging:(id)arg1;

@end
