/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLLocalDerivativeValidatedExternalResource : PLValidatedExternalResource {
    short  localAvailabilityTarget;
}

@property (nonatomic) short localAvailabilityTarget;

- (short)localAvailabilityTarget;
- (void)setLocalAvailabilityTarget:(short)arg1;

@end
