/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLMediaMiningUtilities : NSObject

+ (id)sortDescriptorsForSortingItemsByTime;

@end
