/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLSearchData : PLManagedObject

@property (nonatomic, retain) PLManagedAsset *asset;
@property (nonatomic, retain) NSData *data;
@property (nonatomic) bool valid;

@end
