/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLVideoEditSource : PLEditSource

- (id)initWithVideoURL:(id)arg1;

@end
