/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLZeroKeywordStore : NSObject {
    NSString * _storePath;
}

+ (id)expectedClasses;

- (void).cxx_destruct;
- (id)currentZeroKeywords;
- (void)deleteStore;
- (id)initWithPath:(id)arg1;
- (void)updateZeroKeywordsTo:(id)arg1;

@end
