/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreCDPUI.framework/CoreCDPUI
 */

@interface CDPLocalSecretEntryPane : CDPPassphraseEntryPane

- (double)desiredMinPinHeight;
- (void)setTitle:(id)arg1;

@end
