/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface _CNUIDirectoryServicesPhotoFuture : NSObject

+ (id)photoForEmailAddresses:(id)arg1;

@end
