/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUILibraryFolderDiscovery : NSObject

+ (id)discoverFoldersWithPathComponents:(id)arg1 fileManager:(id)arg2;
+ (id)localImageFolders;

@end
