/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUIUserActionItemComparator : NSObject

+ (id /* block */)comparatorWithActionItemGrouping;
+ (id /* block */)comparatorWithAlphabeticalOrderByLabel;
+ (id /* block */)comparatorWithAlphabeticalOrderByTargetHandle;
+ (id /* block */)comparatorWithPreferredLabelsFirst;
+ (id)scoreForUserAction:(id)arg1;

@end
