/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUIPassKitWrapper : NSObject

+ (bool)isPeerPaymentAvailable;
+ (id)urlForPeerPaymentWithHandle:(id)arg1;

@end
