/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUIContactPropertyRanker : NSObject

+ (id /* block */)bestPropertyComparator;

@end
