/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/iCloudQuotaDaemon.framework/iCloudQuotaDaemon
 */

@interface ICQDaemonBuddyOffer : ICQDaemonOffer

+ (id)_mutablePlaceholderPersistanceDictionary;
+ (id)persistenceKey;

@end
