/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUICardKitProviderSupport.framework/SearchUICardKitProviderSupport
 */

@interface SUICKPWatchListCardSectionViewController : SUICKPMediaPunchoutCardSectionViewController

+ (id)cardSectionClasses;

@end
