/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUICardKitProviderSupport.framework/SearchUICardKitProviderSupport
 */

@interface SUICKPMediaPunchoutCardSectionViewController : SUICKPInteractiveCardSectionViewController

- (bool)shouldHandleEngagement:(id)arg1 forCardSection:(id)arg2;

@end
