/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AudioServerDriver.framework/AudioServerDriver
 */

@interface ASDDSPGraphLoader : NSObject

+ (bool)applyAUStrip:(id)arg1 toGraph:(id)arg2;
+ (bool)applyPropertyStrip:(id)arg1 toGraph:(id)arg2;
+ (id)graphWithConfiguration:(id)arg1;
+ (id)graphWithGraphInfo:(id)arg1;

@end
