/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKAcquireFocusWorkaroundView : UIView

- (bool)canBecomeFirstResponder;

@end
