/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKLoadableContentStateMachine : _GKStateMachine

- (id)init;

@end
