/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKPlaceholderContentStateMachine : _GKStateMachine

@property (nonatomic, readonly) bool isInPlaceholderState;

- (id)init;
- (bool)isInPlaceholderState;

@end
