/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKRectShadowCell : UICollectionViewCell

- (void)awakeFromNib;
- (bool)canBecomeFocused;
- (void)setHighlighted:(bool)arg1;
- (void)setSelected:(bool)arg1;

@end
