/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@interface GKSimpleSlideAnimator : GKBubblePathAnimator

- (void)animateTransition:(id)arg1;
- (long long)animatorType;
- (double)minimumDurationForViewAnimations;

@end
