/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface _CNCombineLatestObservableCancelationToken : CNCancelationToken

@end
