/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface _CNZombie_  {
    Class  isa;
}

+ (void)initialize;

- (id)methodSignatureForSelector:(SEL)arg1;

@end
