/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNEnvironment : NSObject

+ (id)currentEnvironment;

- (bool)isInternalBuild;

@end
