/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNMapObservable : _CNBlockObservable

+ (id)observableWithBlock:(id /* block */)arg1;

@end
