/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNObservedFailureResult : CNObservedResult

- (id)description;
- (bool)isResultEvent;

@end
