/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNOperationQueueSchedulerCancelationToken : CNCancelationToken

@end
