/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface SynchronousQueueSchedulerCancelationToken : CNCancelationToken

@end
