/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOLocationShiftRequestConfig : GEOServiceRequestDefaultConfig

+ (id)standardConfig;

- (int)dataRequestKindForRequest:(id)arg1;
- (id)serviceTypeNumber;
- (bool)shouldThrottleRequests;
- (unsigned long long)urlType;

@end
