/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOTileDBMarkCurrentOperation : _GEOTileDBAddTileOperation

- (void)performWithDB:(id)arg1;

@end
