/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOMapFeatureTileBorderJunction : GEOMapFeatureJunction

- (bool)isOnTileBorder;

@end
