/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEONavdPowerLogManager : NSObject

+ (void)_powerLogWithEventName:(id)arg1;

@end
