/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEORPProblemRequestConfig : GEOServiceRequestDefaultConfig

+ (id)standardConfig;

- (int)dataRequestKindForRequest:(id)arg1;
- (unsigned long long)urlType;

@end
