/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriClientFlow.framework/SiriClientFlow
 */

@interface CFServiceConnector : NSObject

+ (id)connectionToScripterWithCommandProcessor:(id)arg1;

@end
