/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@interface CardDAVFolderGetTask : CoreDAVGetTask

- (void)finishCoreDAVTaskWithError:(id)arg1;

@end
