/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
 */

@interface _REBoolFeatureValue : REFeatureValue

+ (id)featureValueWithBool:(bool)arg1;

- (unsigned long long)type;

@end
