/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
 */

@interface RERecentActionNotifier : NSObject

- (void)performedAction:(id)arg1;

@end
