/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetReaderOutputMetadataAdaptorInternal : NSObject {
    AVAssetReaderTrackOutput * trackOutput;
}

@end
