/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetDownloadCacheInternal : NSObject {
    AVAsset * asset;
    struct CMBaseObject { } * assetCacheInspector;
}

- (void).cxx_destruct;

@end
