/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetResourceLoadingRequestorInternal : NSObject {
    bool  providesExpiredSessionReports;
}

@end
