/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetWriterInputMetadataAdaptorInternal : NSObject {
    AVAssetWriterInput * input;
}

@end
