/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetReaderVideoCompositionOutputInternal : NSObject {
    AVCustomVideoCompositorSession * customVideoCompositorSession;
    void * figVideoCompositor;
    AVVideoComposition * videoComposition;
    AVVideoOutputSettings * videoOutputSettings;
    NSArray * videoTracks;
}

@end
