/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetWriterInputGroupInternal : NSObject {
    AVAssetWriterInput * defaultInput;
    NSArray * inputs;
    NSArray * provisionalInputs;
}

@end
