/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetLoggingIdentifierInternal : NSObject {
    unsigned int  derivedIdentifierCounter;
    NSString * identifierName;
}

@end
