/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetReaderSampleReferenceOutputInternal : NSObject {
    AVAssetTrack * track;
}

@end
