/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAudioMixEffectParameters : NSObject <NSCopying> {
    AVAudioMixEffectParametersInternal * _audioEffect;
}

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
