/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAudioMixSweepFilterEffectParametersInternal : NSObject {
    float  bypassThreshold;
    unsigned int  maximumCutOffFrequency;
    unsigned int  minimumCutOffFrequency;
    float  sweepValue;
}

@end
