/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureCoreMotionMetadataInputInternal : NSObject {
    NSArray * ports;
    NSString * sourceID;
}

@end
