/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureSynchronizedSampleBufferDataInternal : NSObject {
    long long  droppedReason;
    bool  hasCorrespondingDepthData;
    bool  hasCorrespondingVisionData;
    struct opaqueCMSampleBuffer { } * sampleBuffer;
    bool  sampleBufferWasDropped;
}

@end
