/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCapturePhotoBracketSettingsInternal : NSObject {
    NSArray * bracketedSettings;
    bool  lensStabilizationEnabled;
}

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
