/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureSynchronizedMetadataObjectDataInternal : NSObject {
    NSArray * metadataObjects;
}

@end
