/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCompositionTrackSegmentInternal : NSObject {
    int  editAssetTrackID;
    NSURL * editAssetURL;
}

@end
