/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFragmentedAssetTrack : AVAssetTrack {
    AVFragmentedAssetTrackInternal * _fragmentedAssetTrack;
}

@end
