/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVMediaSelectionGroupInternal : NSObject {
    AVWeakReference * weakReference;
}

@end
