/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputDeviceDiscoverySessionInternal : NSObject {
    long long  discoveryMode;
    <AVOutputDeviceDiscoverySessionImpl> * impl;
    NSObject<OS_dispatch_queue> * ivarAccessQueue;
}

@end
