/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPlayerLoggingIdentifierInternal : NSObject {
    NSString * identifierName;
}

@end
