/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPortraitEffectsMatteInternal : NSObject {
    struct __CVBuffer { } * pixelBuffer;
    int  version;
}

@end
