/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVVideoCompositionCoreAnimationToolInternal : NSObject {
    CALayer * animationLayer;
    int  auxiliaryTrackID;
    NSArray * postProcessingVideoLayers;
    long long  way;
}

@end
