/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsServices.framework/NewsServices
 */

@interface NWPNewsWidgetClientTypeLoader : NSObject

+ (id)setOfActiveRestrictionUUIDs;

@end
