/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TouchRemote.framework/TouchRemote
 */

@interface TRAnisetteDataHandler : NSObject

- (void)registerForAnisetteDataRequestsFromSession:(id)arg1;

@end
