/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityViewProfileAlbumsTracklistItemContentDescriptor : MusicEntityViewTracklistItemContentDescriptor

+ (Class)tableViewSectionHeaderClass;
+ (id)tableViewSectionHeaderReuseIdentifier;

@end
