/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicProfileDocumentContainerViewController : SKUIDocumentContainerViewController

+ (bool)allowsChildViewControllerNavigationBarManagement;

@end
