/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicMediaPlaylistDetailQueryDataSource : MusicMediaQueryDataSource

- (void)_invalidateForDisplayValuesChangeIfNeeded;

@end
