/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicLibraryAlbumsTableViewConfiguration : MusicLibraryCollectionBasedTableViewConfiguration

- (id)loadEntityViewDescriptor;

@end
