/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicLibraryMusicVideosViewConfiguration : MusicLibraryBrowseTableViewConfiguration

- (long long)handleSelectionOfEntityValueContext:(id)arg1 fromViewController:(id)arg2;
- (id)init;
- (id)loadEntityViewDescriptor;

@end
