/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityViewHorizontalLockupContentDescriptor : MusicEntityViewContentDescriptor

+ (Class)tableViewCellClass;
+ (id)tableViewCellReuseIdentifier;
+ (Class)tableViewSectionHeaderClass;
+ (id)tableViewSectionHeaderReuseIdentifier;

- (id)init;

@end
