/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/InstallCoordination.framework/InstallCoordination
 */

@interface IXAppInstallObserverProtocolInterface : NSObject

+ (void)configureInterface:(id)arg1;
+ (id)interface;
+ (id)interfaceProtocol;
+ (id)new;

- (id)init;

@end
